/* Code generated by protoc-gen-synurang-ffi. DO NOT EDIT. */
/* C Native API Header for volvoxgrid.activex */

#pragma once

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif


/* ═══════════════════════════════════════════════════════════ */
/* VolvoxGridService — Native C API                            */
/* ═══════════════════════════════════════════════════════════ */


/* CreateGrid */
int64_t volvox_grid_create_grid(
    int32_t viewport_width,
    int32_t viewport_height,
    int32_t rows,
    int32_t cols,
    int32_t fixed_rows,
    int32_t fixed_cols,
    float scale
);

/* DestroyGrid */
uint8_t* volvox_grid_destroy_grid(
    int64_t id,
    int32_t* out_len
);

/* SetRows */
uint8_t* volvox_grid_set_rows(
    int64_t grid_id,
    int32_t rows,
    int32_t* out_len
);

/* SetCols */
uint8_t* volvox_grid_set_cols(
    int64_t grid_id,
    int32_t cols,
    int32_t* out_len
);

/* GetRows */
uint8_t* volvox_grid_get_rows(
    int64_t id,
    int32_t* out_len
);

/* GetCols */
uint8_t* volvox_grid_get_cols(
    int64_t id,
    int32_t* out_len
);

/* SetFixedRows */
uint8_t* volvox_grid_set_fixed_rows(
    int64_t grid_id,
    int32_t fixed_rows,
    int32_t* out_len
);

/* SetFixedCols */
uint8_t* volvox_grid_set_fixed_cols(
    int64_t grid_id,
    int32_t fixed_cols,
    int32_t* out_len
);

/* SetFrozenRows */
uint8_t* volvox_grid_set_frozen_rows(
    int64_t grid_id,
    int32_t frozen_rows,
    int32_t* out_len
);

/* SetFrozenCols */
uint8_t* volvox_grid_set_frozen_cols(
    int64_t grid_id,
    int32_t frozen_cols,
    int32_t* out_len
);

/* SetRowHeight */
uint8_t* volvox_grid_set_row_height(
    int64_t grid_id,
    int32_t row,
    int32_t height,
    int32_t* out_len
);

/* SetColWidth */
uint8_t* volvox_grid_set_col_width(
    int64_t grid_id,
    int32_t col,
    int32_t width,
    int32_t* out_len
);

/* GetRowHeight */
uint8_t* volvox_grid_get_row_height(
    int64_t grid_id,
    int32_t index,
    int32_t* out_len
);

/* GetColWidth */
uint8_t* volvox_grid_get_col_width(
    int64_t grid_id,
    int32_t index,
    int32_t* out_len
);

/* SetRowHeightMin */
uint8_t* volvox_grid_set_row_height_min(
    int64_t grid_id,
    int32_t value,
    int32_t* out_len
);

/* SetRowHeightMax */
uint8_t* volvox_grid_set_row_height_max(
    int64_t grid_id,
    int32_t value,
    int32_t* out_len
);

/* SetColWidthMin */
uint8_t* volvox_grid_set_col_width_min(
    int64_t grid_id,
    int32_t col,
    int32_t value,
    int32_t* out_len
);

/* SetColWidthMax */
uint8_t* volvox_grid_set_col_width_max(
    int64_t grid_id,
    int32_t col,
    int32_t value,
    int32_t* out_len
);

/* SetRowHidden */
uint8_t* volvox_grid_set_row_hidden(
    int64_t grid_id,
    int32_t row,
    int32_t hidden,
    int32_t* out_len
);

/* SetColHidden */
uint8_t* volvox_grid_set_col_hidden(
    int64_t grid_id,
    int32_t col,
    int32_t hidden,
    int32_t* out_len
);

/* GetRowIsVisible */
uint8_t* volvox_grid_get_row_is_visible(
    int64_t grid_id,
    int32_t index,
    int32_t* out_len
);

/* GetColIsVisible */
uint8_t* volvox_grid_get_col_is_visible(
    int64_t grid_id,
    int32_t index,
    int32_t* out_len
);

/* SetColPosition */
uint8_t* volvox_grid_set_col_position(
    int64_t grid_id,
    int32_t col,
    int32_t position,
    int32_t* out_len
);

/* SetRowPosition */
uint8_t* volvox_grid_set_row_position(
    int64_t grid_id,
    int32_t row,
    int32_t position,
    int32_t* out_len
);

/* AutoSize */
uint8_t* volvox_grid_auto_size(
    int64_t grid_id,
    int32_t col_from,
    int32_t col_to,
    int32_t equal,
    int32_t max_width,
    int32_t* out_len
);

/* SetAutoSizeMode */
uint8_t* volvox_grid_set_auto_size_mode(
    int64_t grid_id,
    int32_t mode,
    int32_t* out_len
);

/* SetFormatString */
uint8_t* volvox_grid_set_format_string(
    int64_t grid_id,
    const uint8_t* format_string, int32_t format_string_len,
    int32_t* out_len
);

/* SetRightToLeft */
uint8_t* volvox_grid_set_right_to_left(
    int64_t grid_id,
    int32_t value,
    int32_t* out_len
);

/* SetExtendLastCol */
uint8_t* volvox_grid_set_extend_last_col(
    int64_t grid_id,
    int32_t value,
    int32_t* out_len
);

/* SetScrollBars */
uint8_t* volvox_grid_set_scroll_bars(
    int64_t grid_id,
    int32_t mode,
    int32_t* out_len
);

/* SetScrollTrack */
uint8_t* volvox_grid_set_scroll_track(
    int64_t grid_id,
    int32_t value,
    int32_t* out_len
);

/* SetFlingEnabled */
uint8_t* volvox_grid_set_fling_enabled(
    int64_t grid_id,
    int32_t value,
    int32_t* out_len
);

/* SetFlingImpulseGain */
uint8_t* volvox_grid_set_fling_impulse_gain(
    int64_t grid_id,
    float value,
    int32_t* out_len
);

/* SetFlingFriction */
uint8_t* volvox_grid_set_fling_friction(
    int64_t grid_id,
    float value,
    int32_t* out_len
);

/* ResizeViewport */
uint8_t* volvox_grid_resize_viewport(
    int64_t grid_id,
    int32_t width,
    int32_t height,
    int32_t* out_len
);

/* SetTopRow */
uint8_t* volvox_grid_set_top_row(
    int64_t grid_id,
    int32_t row,
    int32_t* out_len
);

/* GetTopRow */
uint8_t* volvox_grid_get_top_row(
    int64_t id,
    int32_t* out_len
);

/* SetLeftCol */
uint8_t* volvox_grid_set_left_col(
    int64_t grid_id,
    int32_t col,
    int32_t* out_len
);

/* GetLeftCol */
uint8_t* volvox_grid_get_left_col(
    int64_t id,
    int32_t* out_len
);

/* GetBottomRow */
uint8_t* volvox_grid_get_bottom_row(
    int64_t id,
    int32_t* out_len
);

/* GetRightCol */
uint8_t* volvox_grid_get_right_col(
    int64_t id,
    int32_t* out_len
);

/* GetRowPos */
uint8_t* volvox_grid_get_row_pos(
    int64_t grid_id,
    int32_t index,
    int32_t* out_len
);

/* GetColPos */
uint8_t* volvox_grid_get_col_pos(
    int64_t grid_id,
    int32_t index,
    int32_t* out_len
);

/* SetRow */
uint8_t* volvox_grid_set_row(
    int64_t grid_id,
    int32_t row,
    int32_t* out_len
);

/* SetCol */
uint8_t* volvox_grid_set_col(
    int64_t grid_id,
    int32_t col,
    int32_t* out_len
);

/* GetRow */
uint8_t* volvox_grid_get_row(
    int64_t id,
    int32_t* out_len
);

/* GetCol */
uint8_t* volvox_grid_get_col(
    int64_t id,
    int32_t* out_len
);

/* SetRowSel */
uint8_t* volvox_grid_set_row_sel(
    int64_t grid_id,
    int32_t row_sel,
    int32_t* out_len
);

/* SetColSel */
uint8_t* volvox_grid_set_col_sel(
    int64_t grid_id,
    int32_t col_sel,
    int32_t* out_len
);

/* Select */
uint8_t* volvox_grid_select(
    int64_t grid_id,
    int32_t row1,
    int32_t col1,
    int32_t row2,
    int32_t col2,
    int32_t* out_len
);

/* GetSelection */
uint8_t* volvox_grid_get_selection(
    int64_t id,
    int32_t* out_len
);

/* ShowCell */
uint8_t* volvox_grid_show_cell(
    int64_t grid_id,
    int32_t row,
    int32_t col,
    int32_t* out_len
);

/* SetAllowSelection */
uint8_t* volvox_grid_set_allow_selection(
    int64_t grid_id,
    int32_t value,
    int32_t* out_len
);

/* SetAllowBigSelection */
uint8_t* volvox_grid_set_allow_big_selection(
    int64_t grid_id,
    int32_t value,
    int32_t* out_len
);

/* SetSelectionMode */
uint8_t* volvox_grid_set_selection_mode(
    int64_t grid_id,
    int32_t mode,
    int32_t* out_len
);

/* SetFocusRect */
uint8_t* volvox_grid_set_focus_rect(
    int64_t grid_id,
    int32_t style,
    int32_t* out_len
);

/* SetHighLight */
uint8_t* volvox_grid_set_high_light(
    int64_t grid_id,
    int32_t style,
    int32_t* out_len
);

/* GetIsSelected */
uint8_t* volvox_grid_get_is_selected(
    int64_t grid_id,
    int32_t index,
    int32_t* out_len
);

/* GetSelectedRow */
uint8_t* volvox_grid_get_selected_row(
    int64_t grid_id,
    int32_t index,
    int32_t* out_len
);

/* GetSelectedRows */
uint8_t* volvox_grid_get_selected_rows(
    int64_t id,
    int32_t* out_len
);

/* GetMouseRow */
uint8_t* volvox_grid_get_mouse_row(
    int64_t id,
    int32_t* out_len
);

/* GetMouseCol */
uint8_t* volvox_grid_get_mouse_col(
    int64_t id,
    int32_t* out_len
);

/* SetText */
uint8_t* volvox_grid_set_text(
    int64_t grid_id,
    const uint8_t* text, int32_t text_len,
    int32_t* out_len
);

/* GetText */
uint8_t* volvox_grid_get_text(
    int64_t grid_id,
    int32_t* out_len
);

/* SetTextMatrix */
uint8_t* volvox_grid_set_text_matrix(
    int64_t grid_id,
    int32_t row,
    int32_t col,
    const uint8_t* text, int32_t text_len,
    int32_t* out_len
);

/* GetTextMatrix */
uint8_t* volvox_grid_get_text_matrix(
    int64_t grid_id,
    int32_t row,
    int32_t col,
    int32_t* out_len
);

/* SetTextArray */
uint8_t* volvox_grid_set_text_array(
    int64_t grid_id,
    int32_t index,
    const uint8_t* text, int32_t text_len,
    int32_t* out_len
);

/* GetTextArray */
uint8_t* volvox_grid_get_text_array(
    int64_t grid_id,
    int32_t index,
    int32_t* out_len
);

/* LoadArray (protobuf input — has repeated/oneof fields) */
uint8_t* volvox_grid_load_array_pb(
    const uint8_t* data, int32_t data_len,
    int32_t* out_len
);

/* BindToArray (protobuf input — has repeated/oneof fields) */
uint8_t* volvox_grid_bind_to_array_pb(
    const uint8_t* data, int32_t data_len,
    int32_t* out_len
);

/* SetValue */
uint8_t* volvox_grid_set_value(
    int64_t grid_id,
    const uint8_t* value, int32_t value_len,
    int32_t* out_len
);

/* GetValue */
uint8_t* volvox_grid_get_value(
    int64_t grid_id,
    int32_t* out_len
);

/* SetValueMatrix */
uint8_t* volvox_grid_set_value_matrix(
    int64_t grid_id,
    int32_t row,
    int32_t col,
    const uint8_t* value, int32_t value_len,
    int32_t* out_len
);

/* GetValueMatrix */
uint8_t* volvox_grid_get_value_matrix(
    int64_t grid_id,
    int32_t row,
    int32_t col,
    int32_t* out_len
);

/* SetCells (protobuf input — has repeated/oneof fields) */
uint8_t* volvox_grid_set_cells_pb(
    const uint8_t* data, int32_t data_len,
    int32_t* out_len
);

/* GetCells */
uint8_t* volvox_grid_get_cells(
    int64_t grid_id,
    int32_t row1,
    int32_t col1,
    int32_t row2,
    int32_t col2,
    int32_t* out_len
);

/* SetCell */
uint8_t* volvox_grid_set_cell(
    int64_t grid_id,
    int32_t prop,
    int32_t row1,
    int32_t col1,
    int32_t row2,
    int32_t col2,
    const uint8_t* value, int32_t value_len,
    int32_t* out_len
);

/* GetCell */
uint8_t* volvox_grid_get_cell(
    int64_t grid_id,
    int32_t prop,
    int32_t row,
    int32_t col,
    int32_t* out_len
);

/* SetClip */
uint8_t* volvox_grid_set_clip(
    int64_t grid_id,
    const uint8_t* clip, int32_t clip_len,
    int32_t* out_len
);

/* GetClip */
uint8_t* volvox_grid_get_clip(
    int64_t grid_id,
    int32_t* out_len
);

/* SetClipSeparators */
uint8_t* volvox_grid_set_clip_separators(
    int64_t grid_id,
    const uint8_t* col_separator, int32_t col_separator_len,
    const uint8_t* row_separator, int32_t row_separator_len,
    int32_t* out_len
);

/* SetFillStyle */
uint8_t* volvox_grid_set_fill_style(
    int64_t grid_id,
    int32_t style,
    int32_t* out_len
);

/* AddItem */
uint8_t* volvox_grid_add_item(
    int64_t grid_id,
    const uint8_t* item, int32_t item_len,
    int32_t index,
    int32_t* out_len
);

/* RemoveItem */
uint8_t* volvox_grid_remove_item(
    int64_t grid_id,
    int32_t index,
    int32_t* out_len
);

/* Clear */
uint8_t* volvox_grid_clear(
    int64_t grid_id,
    int32_t scope,
    int32_t region,
    int32_t* out_len
);

/* FindRow */
uint8_t* volvox_grid_find_row(
    int64_t grid_id,
    const uint8_t* text, int32_t text_len,
    int32_t start_row,
    int32_t col,
    int32_t case_sense,
    int32_t full_match,
    int32_t* out_len
);

/* FindRowRegex */
uint8_t* volvox_grid_find_row_regex(
    int64_t grid_id,
    const uint8_t* pattern, int32_t pattern_len,
    int32_t start_row,
    int32_t col,
    int32_t* out_len
);

/* Aggregate */
uint8_t* volvox_grid_aggregate(
    int64_t grid_id,
    int32_t aggregate,
    int32_t row1,
    int32_t col1,
    int32_t row2,
    int32_t col2,
    int32_t* out_len
);

/* SetEditable */
uint8_t* volvox_grid_set_editable(
    int64_t grid_id,
    int32_t mode,
    int32_t* out_len
);

/* EditCell */
uint8_t* volvox_grid_edit_cell(
    int64_t grid_id,
    int32_t row,
    int32_t col,
    int32_t* out_len
);

/* FinishEditing */
uint8_t* volvox_grid_finish_editing(
    int64_t id,
    int32_t* out_len
);

/* SetEditMask */
uint8_t* volvox_grid_set_edit_mask(
    int64_t grid_id,
    const uint8_t* mask, int32_t mask_len,
    int32_t* out_len
);

/* SetColEditMask */
uint8_t* volvox_grid_set_col_edit_mask(
    int64_t grid_id,
    int32_t col,
    const uint8_t* mask, int32_t mask_len,
    int32_t* out_len
);

/* SetColComboList */
uint8_t* volvox_grid_set_col_combo_list(
    int64_t grid_id,
    int32_t col,
    const uint8_t* list, int32_t list_len,
    int32_t* out_len
);

/* SetComboList */
uint8_t* volvox_grid_set_combo_list(
    int64_t grid_id,
    const uint8_t* list, int32_t list_len,
    int32_t* out_len
);

/* SetComboSearch */
uint8_t* volvox_grid_set_combo_search(
    int64_t grid_id,
    int32_t value,
    int32_t* out_len
);

/* SetShowComboButton */
uint8_t* volvox_grid_set_show_combo_button(
    int64_t grid_id,
    int32_t mode,
    int32_t* out_len
);

/* BuildComboList */
uint8_t* volvox_grid_build_combo_list(
    int64_t grid_id,
    const uint8_t* query, int32_t query_len,
    int32_t* out_len
);

/* SetTabBehavior */
uint8_t* volvox_grid_set_tab_behavior(
    int64_t grid_id,
    int32_t behavior,
    int32_t* out_len
);

/* CommitEdit */
uint8_t* volvox_grid_commit_edit(
    int64_t grid_id,
    const uint8_t* text, int32_t text_len,
    int32_t cancel,
    int32_t* out_len
);

/* CancelEdit */
uint8_t* volvox_grid_cancel_edit(
    int64_t id,
    int32_t* out_len
);

/* SetEditText */
uint8_t* volvox_grid_set_edit_text(
    int64_t grid_id,
    const uint8_t* value, int32_t value_len,
    int32_t* out_len
);

/* GetEditText */
uint8_t* volvox_grid_get_edit_text(
    int64_t id,
    int32_t* out_len
);

/* SetEditMaxLength */
uint8_t* volvox_grid_set_edit_max_length(
    int64_t grid_id,
    int32_t value,
    int32_t* out_len
);

/* GetEditMaxLength */
uint8_t* volvox_grid_get_edit_max_length(
    int64_t id,
    int32_t* out_len
);

/* SetGridStyle */
uint8_t* volvox_grid_set_grid_style(
    int64_t grid_id,
    const uint8_t* style, int32_t style_len,
    int32_t* out_len
);

/* GetGridStyle */
uint8_t* volvox_grid_get_grid_style(
    int64_t id,
    int32_t* out_len
);

/* SetCellStyle */
uint8_t* volvox_grid_set_cell_style(
    int64_t grid_id,
    const uint8_t* style, int32_t style_len,
    int32_t* out_len
);

/* GetCellStyle */
uint8_t* volvox_grid_get_cell_style(
    int64_t grid_id,
    int32_t row,
    int32_t col,
    int32_t* out_len
);

/* SetCellStyleRange */
uint8_t* volvox_grid_set_cell_style_range(
    int64_t grid_id,
    int32_t row1,
    int32_t col1,
    int32_t row2,
    int32_t col2,
    const uint8_t* style, int32_t style_len,
    int32_t* out_len
);

/* SetColAlignment */
uint8_t* volvox_grid_set_col_alignment(
    int64_t grid_id,
    int32_t col,
    int32_t alignment,
    int32_t* out_len
);

/* SetColFormat */
uint8_t* volvox_grid_set_col_format(
    int64_t grid_id,
    int32_t col,
    const uint8_t* format, int32_t format_len,
    int32_t* out_len
);

/* SetColDataType */
uint8_t* volvox_grid_set_col_data_type(
    int64_t grid_id,
    int32_t col,
    int32_t data_type,
    int32_t* out_len
);

/* SetColIndent */
uint8_t* volvox_grid_set_col_indent(
    int64_t grid_id,
    int32_t col,
    int32_t indent,
    int32_t* out_len
);

/* SetColKey */
uint8_t* volvox_grid_set_col_key(
    int64_t grid_id,
    int32_t col,
    const uint8_t* key, int32_t key_len,
    int32_t* out_len
);

/* SetColSort */
uint8_t* volvox_grid_set_col_sort(
    int64_t grid_id,
    int32_t col,
    int32_t order,
    int32_t* out_len
);

/* SetFixedAlignment */
uint8_t* volvox_grid_set_fixed_alignment(
    int64_t grid_id,
    int32_t col,
    int32_t alignment,
    int32_t* out_len
);

/* GetColIndex */
uint8_t* volvox_grid_get_col_index(
    int64_t grid_id,
    const uint8_t* key, int32_t key_len,
    int32_t* out_len
);

/* SetCellPicture */
uint8_t* volvox_grid_set_cell_picture(
    int64_t grid_id,
    int32_t row,
    int32_t col,
    const uint8_t* image, int32_t image_len,
    int32_t* out_len
);

/* GetCellPicture */
uint8_t* volvox_grid_get_cell_picture(
    int64_t grid_id,
    int32_t row,
    int32_t col,
    int32_t* out_len
);

/* SetCellPictureAlignment */
uint8_t* volvox_grid_set_cell_picture_alignment(
    int64_t grid_id,
    int32_t row,
    int32_t col,
    int32_t alignment,
    int32_t* out_len
);

/* SetColImageList (protobuf input — has repeated/oneof fields) */
uint8_t* volvox_grid_set_col_image_list_pb(
    const uint8_t* data, int32_t data_len,
    int32_t* out_len
);

/* SetCellFlood */
uint8_t* volvox_grid_set_cell_flood(
    int64_t grid_id,
    int32_t row,
    int32_t col,
    uint32_t color,
    float percent,
    int32_t* out_len
);

/* SetCellChecked */
uint8_t* volvox_grid_set_cell_checked(
    int64_t grid_id,
    int32_t row,
    int32_t col,
    int32_t state,
    int32_t* out_len
);

/* GetCellChecked */
uint8_t* volvox_grid_get_cell_checked(
    int64_t grid_id,
    int32_t row,
    int32_t col,
    int32_t* out_len
);

/* SetOwnerDraw */
uint8_t* volvox_grid_set_owner_draw(
    int64_t grid_id,
    int32_t mode,
    int32_t* out_len
);

/* CellBorder */
uint8_t* volvox_grid_cell_border(
    int64_t grid_id,
    uint32_t color,
    int32_t style,
    int32_t* out_len
);

/* CellBorderRange */
uint8_t* volvox_grid_cell_border_range(
    int64_t grid_id,
    int32_t row1,
    int32_t col1,
    int32_t row2,
    int32_t col2,
    uint32_t color,
    int32_t style,
    int32_t* out_len
);

/* SetWordWrap */
uint8_t* volvox_grid_set_word_wrap(
    int64_t grid_id,
    int32_t value,
    int32_t* out_len
);

/* SetEllipsis */
uint8_t* volvox_grid_set_ellipsis(
    int64_t grid_id,
    int32_t value,
    int32_t* out_len
);

/* Sort (protobuf input — has repeated/oneof fields) */
uint8_t* volvox_grid_sort_pb(
    const uint8_t* data, int32_t data_len,
    int32_t* out_len
);

/* SetExplorerBar */
uint8_t* volvox_grid_set_explorer_bar(
    int64_t grid_id,
    int32_t mode,
    int32_t* out_len
);

/* SetGroupCompare */
uint8_t* volvox_grid_set_group_compare(
    int64_t grid_id,
    int32_t value,
    int32_t* out_len
);

/* GetGroupCompare */
uint8_t* volvox_grid_get_group_compare(
    int64_t id,
    int32_t* out_len
);

/* SetSortAscendingPicture */
uint8_t* volvox_grid_set_sort_ascending_picture(
    int64_t grid_id,
    const uint8_t* image_data, int32_t image_data_len,
    int32_t* out_len
);

/* GetSortAscendingPicture */
uint8_t* volvox_grid_get_sort_ascending_picture(
    int64_t id,
    int32_t* out_len
);

/* SetSortDescendingPicture */
uint8_t* volvox_grid_set_sort_descending_picture(
    int64_t grid_id,
    const uint8_t* image_data, int32_t image_data_len,
    int32_t* out_len
);

/* GetSortDescendingPicture */
uint8_t* volvox_grid_get_sort_descending_picture(
    int64_t id,
    int32_t* out_len
);

/* SetMergeCells */
uint8_t* volvox_grid_set_merge_cells(
    int64_t grid_id,
    int32_t mode,
    int32_t* out_len
);

/* SetMergeCellsFixed */
uint8_t* volvox_grid_set_merge_cells_fixed(
    int64_t grid_id,
    int32_t mode,
    int32_t* out_len
);

/* SetMergeRow */
uint8_t* volvox_grid_set_merge_row(
    int64_t grid_id,
    int32_t row,
    int32_t merge,
    int32_t* out_len
);

/* SetMergeCol */
uint8_t* volvox_grid_set_merge_col(
    int64_t grid_id,
    int32_t col,
    int32_t merge,
    int32_t* out_len
);

/* SetMergeCompare */
uint8_t* volvox_grid_set_merge_compare(
    int64_t grid_id,
    int32_t value,
    int32_t* out_len
);

/* GetMergedRange */
uint8_t* volvox_grid_get_merged_range(
    int64_t grid_id,
    int32_t row,
    int32_t col,
    int32_t* out_len
);

/* SetOutlineBar */
uint8_t* volvox_grid_set_outline_bar(
    int64_t grid_id,
    int32_t style,
    int32_t* out_len
);

/* SetOutlineCol */
uint8_t* volvox_grid_set_outline_col(
    int64_t grid_id,
    int32_t col,
    int32_t* out_len
);

/* SetTreeColor */
uint8_t* volvox_grid_set_tree_color(
    int64_t grid_id,
    uint32_t color,
    int32_t* out_len
);

/* SetIsSubtotal */
uint8_t* volvox_grid_set_is_subtotal(
    int64_t grid_id,
    int32_t row,
    int32_t is_subtotal,
    int32_t* out_len
);

/* GetIsSubtotal */
uint8_t* volvox_grid_get_is_subtotal(
    int64_t grid_id,
    int32_t index,
    int32_t* out_len
);

/* SetRowOutlineLevel */
uint8_t* volvox_grid_set_row_outline_level(
    int64_t grid_id,
    int32_t row,
    int32_t level,
    int32_t* out_len
);

/* GetRowOutlineLevel */
uint8_t* volvox_grid_get_row_outline_level(
    int64_t grid_id,
    int32_t index,
    int32_t* out_len
);

/* SetIsCollapsed */
uint8_t* volvox_grid_set_is_collapsed(
    int64_t grid_id,
    int32_t row,
    int32_t collapsed,
    int32_t* out_len
);

/* GetIsCollapsed */
uint8_t* volvox_grid_get_is_collapsed(
    int64_t grid_id,
    int32_t index,
    int32_t* out_len
);

/* Subtotal */
uint8_t* volvox_grid_subtotal(
    int64_t grid_id,
    int32_t aggregate,
    int32_t group_on_col,
    int32_t aggregate_col,
    const uint8_t* caption, int32_t caption_len,
    uint32_t back_color,
    uint32_t fore_color,
    int32_t add_outline,
    const uint8_t* font, int32_t font_len,
    int32_t* out_len
);

/* SetSubtotalPosition */
uint8_t* volvox_grid_set_subtotal_position(
    int64_t grid_id,
    int32_t position,
    int32_t* out_len
);

/* SetMultiTotals */
uint8_t* volvox_grid_set_multi_totals(
    int64_t grid_id,
    int32_t value,
    int32_t* out_len
);

/* Outline */
uint8_t* volvox_grid_outline(
    int64_t grid_id,
    int32_t level,
    int32_t* out_len
);

/* GetNodeRow */
uint8_t* volvox_grid_get_node_row(
    int64_t grid_id,
    int32_t row,
    int32_t relation,
    int32_t* out_len
);

/* GetNode */
uint8_t* volvox_grid_get_node(
    int64_t grid_id,
    int32_t row,
    int32_t* out_len
);

/* SetNodeOpenPicture */
uint8_t* volvox_grid_set_node_open_picture(
    int64_t grid_id,
    const uint8_t* image_data, int32_t image_data_len,
    int32_t* out_len
);

/* SetNodeClosedPicture */
uint8_t* volvox_grid_set_node_closed_picture(
    int64_t grid_id,
    const uint8_t* image_data, int32_t image_data_len,
    int32_t* out_len
);

/* SaveGrid */
uint8_t* volvox_grid_save_grid(
    int64_t grid_id,
    int32_t format,
    int32_t scope,
    int32_t* out_len
);

/* LoadGrid */
uint8_t* volvox_grid_load_grid(
    int64_t grid_id,
    const uint8_t* data, int32_t data_len,
    int32_t format,
    int32_t scope,
    int32_t* out_len
);

/* PrintGrid */
uint8_t* volvox_grid_print_grid(
    int64_t grid_id,
    int32_t orientation,
    int32_t margin_left,
    int32_t margin_top,
    int32_t margin_right,
    int32_t margin_bottom,
    const uint8_t* header, int32_t header_len,
    const uint8_t* footer, int32_t footer_len,
    int32_t show_page_numbers,
    int32_t* out_len
);

/* Archive */
uint8_t* volvox_grid_archive(
    int64_t grid_id,
    const uint8_t* name, int32_t name_len,
    int32_t action,
    const uint8_t* data, int32_t data_len,
    int32_t* out_len
);

/* GetArchiveInfo */
uint8_t* volvox_grid_get_archive_info(
    int64_t grid_id,
    const uint8_t* data, int32_t data_len,
    int32_t* out_len
);

/* Copy */
uint8_t* volvox_grid_copy(
    int64_t id,
    int32_t* out_len
);

/* Cut */
uint8_t* volvox_grid_cut(
    int64_t id,
    int32_t* out_len
);

/* Paste */
uint8_t* volvox_grid_paste(
    int64_t grid_id,
    const uint8_t* data, int32_t data_len,
    int32_t* out_len
);

/* Delete */
uint8_t* volvox_grid_delete(
    int64_t id,
    int32_t* out_len
);

/* SetDragMode */
uint8_t* volvox_grid_set_drag_mode(
    int64_t grid_id,
    int32_t mode,
    int32_t* out_len
);

/* SetDropMode */
uint8_t* volvox_grid_set_drop_mode(
    int64_t grid_id,
    int32_t mode,
    int32_t* out_len
);

/* DragRow */
uint8_t* volvox_grid_drag_row(
    int64_t grid_id,
    int32_t row,
    int32_t position,
    int32_t* out_len
);

/* SetResizePolicy */
uint8_t* volvox_grid_set_resize_policy(
    int64_t grid_id,
    const uint8_t* policy, int32_t policy_len,
    int32_t* out_len
);

/* SetFreezePolicy */
uint8_t* volvox_grid_set_freeze_policy(
    int64_t grid_id,
    const uint8_t* policy, int32_t policy_len,
    int32_t* out_len
);

/* SetAutoSearch */
uint8_t* volvox_grid_set_auto_search(
    int64_t grid_id,
    int32_t mode,
    int32_t* out_len
);

/* SetAutoSearchDelay */
uint8_t* volvox_grid_set_auto_search_delay(
    int64_t grid_id,
    int32_t value,
    int32_t* out_len
);

/* SetAutoSizeMouse */
uint8_t* volvox_grid_set_auto_size_mouse(
    int64_t grid_id,
    int32_t value,
    int32_t* out_len
);

/* SetScrollTips */
uint8_t* volvox_grid_set_scroll_tips(
    int64_t grid_id,
    int32_t value,
    int32_t* out_len
);

/* SetInteractionConfig */
uint8_t* volvox_grid_set_interaction_config(
    int64_t grid_id,
    const uint8_t* config, int32_t config_len,
    int32_t* out_len
);

/* GetInteractionConfig */
uint8_t* volvox_grid_get_interaction_config(
    int64_t id,
    int32_t* out_len
);

/* SetRendererMode */
uint8_t* volvox_grid_set_renderer_mode(
    int64_t grid_id,
    int32_t mode,
    int32_t* out_len
);

/* GetRendererMode */
uint8_t* volvox_grid_get_renderer_mode(
    int64_t id,
    int32_t* out_len
);

/* SetDebugOverlay */
uint8_t* volvox_grid_set_debug_overlay(
    int64_t grid_id,
    int32_t value,
    int32_t* out_len
);

/* GetDebugOverlay */
uint8_t* volvox_grid_get_debug_overlay(
    int64_t id,
    int32_t* out_len
);

/* SetAnimationEnabled */
uint8_t* volvox_grid_set_animation_enabled(
    int64_t grid_id,
    int32_t enabled,
    int32_t duration_ms,
    int32_t* out_len
);

/* GetAnimationEnabled */
uint8_t* volvox_grid_get_animation_enabled(
    int64_t id,
    int32_t* out_len
);

/* SetRedraw */
uint8_t* volvox_grid_set_redraw(
    int64_t grid_id,
    int32_t value,
    int32_t* out_len
);

/* Refresh */
uint8_t* volvox_grid_refresh(
    int64_t id,
    int32_t* out_len
);

/* SetAutoResize */
uint8_t* volvox_grid_set_auto_resize(
    int64_t grid_id,
    int32_t value,
    int32_t* out_len
);

/* GetAutoResize */
uint8_t* volvox_grid_get_auto_resize(
    int64_t id,
    int32_t* out_len
);

/* SetScrollTipText */
uint8_t* volvox_grid_set_scroll_tip_text(
    int64_t grid_id,
    const uint8_t* value, int32_t value_len,
    int32_t* out_len
);

/* GetScrollTipText */
uint8_t* volvox_grid_get_scroll_tip_text(
    int64_t id,
    int32_t* out_len
);

/* SetFlags */
uint8_t* volvox_grid_set_flags(
    int64_t grid_id,
    int32_t value,
    int32_t* out_len
);

/* GetFlags */
uint8_t* volvox_grid_get_flags(
    int64_t id,
    int32_t* out_len
);

/* GetVersion */
uint8_t* volvox_grid_get_version(
    int64_t id,
    int32_t* out_len
);

/* GetClientWidth */
uint8_t* volvox_grid_get_client_width(
    int64_t id,
    int32_t* out_len
);

/* GetClientHeight */
uint8_t* volvox_grid_get_client_height(
    int64_t id,
    int32_t* out_len
);

/* GetIsSearching */
uint8_t* volvox_grid_get_is_searching(
    int64_t id,
    int32_t* out_len
);

/* GetPicture */
uint8_t* volvox_grid_get_picture(
    int64_t id,
    int32_t* out_len
);

/* SetPictureType */
uint8_t* volvox_grid_set_picture_type(
    int64_t grid_id,
    int32_t value,
    int32_t* out_len
);

/* GetPictureType */
uint8_t* volvox_grid_get_picture_type(
    int64_t id,
    int32_t* out_len
);

/* SetDataMode */
uint8_t* volvox_grid_set_data_mode(
    int64_t grid_id,
    int32_t value,
    int32_t* out_len
);

/* GetDataMode */
uint8_t* volvox_grid_get_data_mode(
    int64_t id,
    int32_t* out_len
);

/* SetVirtualData */
uint8_t* volvox_grid_set_virtual_data(
    int64_t grid_id,
    int32_t value,
    int32_t* out_len
);

/* GetVirtualData */
uint8_t* volvox_grid_get_virtual_data(
    int64_t id,
    int32_t* out_len
);

/* SetColData */
uint8_t* volvox_grid_set_col_data(
    int64_t grid_id,
    int32_t col,
    const uint8_t* data, int32_t data_len,
    int32_t* out_len
);

/* GetColData */
uint8_t* volvox_grid_get_col_data(
    int64_t grid_id,
    int32_t col,
    int32_t* out_len
);

/* SetRowData */
uint8_t* volvox_grid_set_row_data(
    int64_t grid_id,
    int32_t col,
    const uint8_t* data, int32_t data_len,
    int32_t* out_len
);

/* GetRowData */
uint8_t* volvox_grid_get_row_data(
    int64_t grid_id,
    int32_t col,
    int32_t* out_len
);

/* SetRowStatus */
uint8_t* volvox_grid_set_row_status(
    int64_t grid_id,
    int32_t col,
    int32_t value,
    int32_t* out_len
);

/* GetRowStatus */
uint8_t* volvox_grid_get_row_status(
    int64_t grid_id,
    int32_t index,
    int32_t* out_len
);

/* SetCellButtonPicture */
uint8_t* volvox_grid_set_cell_button_picture(
    int64_t grid_id,
    int32_t row,
    int32_t col,
    const uint8_t* image, int32_t image_len,
    int32_t* out_len
);

/* GetCellButtonPicture */
uint8_t* volvox_grid_get_cell_button_picture(
    int64_t grid_id,
    int32_t row,
    int32_t col,
    int32_t* out_len
);

/* GetEditSelStart */
uint8_t* volvox_grid_get_edit_sel_start(
    int64_t id,
    int32_t* out_len
);

/* SetEditSelStart */
uint8_t* volvox_grid_set_edit_sel_start(
    int64_t grid_id,
    int32_t value,
    int32_t* out_len
);

/* GetEditSelLength */
uint8_t* volvox_grid_get_edit_sel_length(
    int64_t id,
    int32_t* out_len
);

/* SetEditSelLength */
uint8_t* volvox_grid_set_edit_sel_length(
    int64_t grid_id,
    int32_t value,
    int32_t* out_len
);

/* GetEditSelText */
uint8_t* volvox_grid_get_edit_sel_text(
    int64_t id,
    int32_t* out_len
);

/* GetComboCount */
uint8_t* volvox_grid_get_combo_count(
    int64_t id,
    int32_t* out_len
);

/* GetComboIndex */
uint8_t* volvox_grid_get_combo_index(
    int64_t id,
    int32_t* out_len
);

/* SetComboIndex */
uint8_t* volvox_grid_set_combo_index(
    int64_t grid_id,
    int32_t value,
    int32_t* out_len
);

/* GetComboItem */
uint8_t* volvox_grid_get_combo_item(
    int64_t grid_id,
    int32_t index,
    int32_t* out_len
);

/* GetComboData */
uint8_t* volvox_grid_get_combo_data(
    int64_t grid_id,
    int32_t index,
    int32_t* out_len
);

/* DataRefresh */
uint8_t* volvox_grid_data_refresh(
    int64_t id,
    int32_t* out_len
);

/* LoadGridUrl */
uint8_t* volvox_grid_load_grid_url(
    int64_t grid_id,
    const uint8_t* url, int32_t url_len,
    const uint8_t* data, int32_t data_len,
    int32_t format,
    int32_t scope,
    int32_t* out_len
);

/* AutoSearch */
uint8_t* volvox_grid_auto_search(
    int64_t grid_id,
    int32_t mode,
    int32_t* out_len
);

/* LoadDemo */
uint8_t* volvox_grid_load_demo(
    int64_t grid_id,
    const uint8_t* demo, int32_t demo_len,
    int32_t* out_len
);


/* ═══════════════════════════════════════════════════════════ */
/* Memory Management & Error Retrieval                        */
/* ═══════════════════════════════════════════════════════════ */

/* Free memory returned by native API functions.              */
/* The allocation size is recovered from the prepended header. */
void volvox_grid_free(uint8_t* ptr);

/* Returns a pointer to the last error message (UTF-8, not    */
/* null-terminated). Valid until the next FFI call into this   */
/* module. Returns NULL if no error. Writes byte length to    */
/* out_len.                                                   */
const uint8_t* volvox_grid_last_error(int32_t* out_len);


#ifdef __cplusplus
}
#endif

