// Minimum VolvoxGrid C++ host: opens a GTK4 window and renders the embedded
// "sales" demo as a real data grid via the FFI runtime + generated lite client.
//
// Architecture:
//   volvoxgrid::Runtime                       — dlopen + raw FFI (volvoxgrid.hpp)
//   volvoxgrid::lite_transport::RuntimeTransport
//                                              — reusable adapter exposing
//                                                Runtime as a synurang::lite::Transport
//                                                (volvoxgrid_lite_transport.hpp)
//   volvoxgrid::v1::*                         — generated message structs + lite client
//                                                (cpp/include/generated/volvoxgrid_lite.hpp)
//
// No libprotobuf, no gRPC. Wire format and message types are generated by
// protoc-gen-synurang-ffi (mode=lite); this file is pure host glue.
//
// Build:
//   cmake -S . -B build && cmake --build build
//   VOLVOXGRID_LIBRARY=/path/to/libvolvoxgrid.so ./build/vg_gtk

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <memory>
#include <string>
#include <vector>

#include <gtk/gtk.h>

#include "volvoxgrid.hpp"
#include "volvoxgrid_lite_transport.hpp"
#include "generated/volvoxgrid_lite.hpp"

namespace {

namespace vg = volvoxgrid::v1;
using volvoxgrid::lite_transport::RuntimeTransport;

// ─── app state ────────────────────────────────────────────────────────
struct App {
    volvoxgrid::Runtime* rt = nullptr;
    std::unique_ptr<RuntimeTransport> transport;
    std::unique_ptr<vg::VolvoxGridServiceLite> client;
    std::unique_ptr<vg::SynurangLiteBidiStream<vg::RenderInput, vg::RenderOutput>> session;
    int64_t grid_id = 0;
    std::vector<uint8_t> rgba;        // engine writes here (RGBA byte order)
    std::vector<uint8_t> bgra;        // Cairo reads here (premultiplied ARGB on LE = BGRA)
    int buffer_w = 0, buffer_h = 0;
    cairo_surface_t* surface = nullptr;
    GtkWidget* drawing = nullptr;
    GtkWidget* status_label = nullptr;
    std::string error;
};

void clear_surface(App& app) {
    if (app.surface) {
        cairo_surface_destroy(app.surface);
        app.surface = nullptr;
    }
}

void rgba_to_bgra(const uint8_t* src, uint8_t* dst, size_t pixel_count) {
    for (size_t i = 0; i < pixel_count; ++i) {
        dst[0] = src[2];
        dst[1] = src[1];
        dst[2] = src[0];
        dst[3] = src[3];
        src += 4; dst += 4;
    }
}

vg::RenderInput viewport_input(int64_t grid_id, int32_t w, int32_t h) {
    vg::RenderInput in;
    in.grid_id = grid_id;
    in.viewport = std::make_shared<vg::ViewportState>();
    in.viewport->width = w;
    in.viewport->height = h;
    in.input_case = vg::RenderInput::InputCase::kViewport;
    return in;
}

vg::RenderInput buffer_input(int64_t grid_id, int64_t handle, int32_t stride,
                             int32_t w, int32_t h, int32_t capacity) {
    vg::RenderInput in;
    in.grid_id = grid_id;
    in.buffer = std::make_shared<vg::BufferReady>();
    in.buffer->handle = handle;
    in.buffer->stride = stride;
    in.buffer->width = w;
    in.buffer->height = h;
    in.buffer->capacity = capacity;
    in.input_case = vg::RenderInput::InputCase::kBuffer;
    return in;
}

vg::RenderInput scroll_input(int64_t grid_id, float dx, float dy) {
    vg::RenderInput in;
    in.grid_id = grid_id;
    in.scroll = std::make_shared<vg::ScrollEvent>();
    in.scroll->delta_x = dx;
    in.scroll->delta_y = dy;
    in.input_case = vg::RenderInput::InputCase::kScroll;
    return in;
}

// Pump RenderSession until we observe a FrameDone (engine guarantees one).
// Other oneof events — selection / cursor / editor — are skipped.
bool present_frame(App& app) {
    if (!app.session || app.grid_id == 0) return false;
    if (app.buffer_w <= 0 || app.buffer_h <= 0) return false;

    const int32_t stride = app.buffer_w * 4;
    const size_t bytes = static_cast<size_t>(stride) * static_cast<size_t>(app.buffer_h);
    try {
        const int64_t handle = static_cast<int64_t>(reinterpret_cast<uintptr_t>(app.rgba.data()));
        app.session->send(buffer_input(app.grid_id, handle, stride,
                                       app.buffer_w, app.buffer_h,
                                       static_cast<int32_t>(bytes)));
    } catch (const std::exception& e) {
        app.error = std::string("send failed: ") + e.what();
        return false;
    }

    for (int spin = 0; spin < 64; ++spin) {
        vg::RenderOutput out;
        try {
            if (!app.session->recv(out)) {
                app.error = "stream ended before FrameDone";
                return false;
            }
        } catch (const std::exception& e) {
            app.error = std::string("recv failed: ") + e.what();
            return false;
        }
        if (out.event_case == vg::RenderOutput::EventCase::kFrameDone) {
            if (out.rendered) {
                rgba_to_bgra(app.rgba.data(), app.bgra.data(),
                             static_cast<size_t>(app.buffer_w) * static_cast<size_t>(app.buffer_h));
            }
            clear_surface(app);
            app.surface = cairo_image_surface_create_for_data(
                app.bgra.data(), CAIRO_FORMAT_ARGB32, app.buffer_w, app.buffer_h, stride);
            return true;
        }
    }
    app.error = "no FrameDone after 64 events";
    return false;
}

bool ensure_buffer(App& app, int w, int h) {
    if (w <= 0 || h <= 0) return false;
    if (app.buffer_w == w && app.buffer_h == h) return true;
    const size_t bytes = static_cast<size_t>(w) * static_cast<size_t>(h) * 4u;
    app.rgba.assign(bytes, 0);
    app.bgra.assign(bytes, 0);
    app.buffer_w = w; app.buffer_h = h;
    clear_surface(app);
    return true;
}

bool render_resize(App& app, int w, int h) {
    if (!ensure_buffer(app, w, h)) return false;
    try {
        app.session->send(viewport_input(app.grid_id, w, h));
    } catch (const std::exception& e) {
        app.error = std::string("send viewport failed: ") + e.what();
        return false;
    }
    return present_frame(app);
}

bool render_scroll(App& app, float dx, float dy) {
    if (app.buffer_w <= 0 || app.buffer_h <= 0) return false;
    try {
        app.session->send(scroll_input(app.grid_id, dx, dy));
    } catch (const std::exception& e) {
        app.error = std::string("send scroll failed: ") + e.what();
        return false;
    }
    return present_frame(app);
}

// ─── GTK plumbing ─────────────────────────────────────────────────────
void on_draw(GtkDrawingArea*, cairo_t* cr, int, int, gpointer user_data) {
    auto* app = static_cast<App*>(user_data);
    if (app->surface) {
        cairo_set_source_surface(cr, app->surface, 0, 0);
        cairo_paint(cr);
    } else {
        cairo_set_source_rgb(cr, 0.95, 0.95, 0.95);
        cairo_paint(cr);
    }
}

// Mouse-wheel notches arrive as dy=±1.0; scale up so each notch moves a
// useful number of pixels in the engine's scroll model.
constexpr float kWheelScrollGain = 3.0f;

void on_resize(GtkDrawingArea* area, int w, int h, gpointer user_data) {
    auto* app = static_cast<App*>(user_data);
    if (render_resize(*app, w, h)) {
        gtk_widget_queue_draw(GTK_WIDGET(area));
        if (app->status_label) {
            char msg[160];
            std::snprintf(msg, sizeof(msg),
                          "Sales grid rendered at %d×%d (text=%s, gpu=%s)",
                          w, h,
                          app->rt->has_builtin_text_engine() ? "yes" : "no",
                          app->rt->has_gpu_renderer() ? "yes" : "no");
            gtk_label_set_text(GTK_LABEL(app->status_label), msg);
        }
    } else if (app->status_label) {
        gtk_label_set_text(GTK_LABEL(app->status_label), app->error.c_str());
    }
}

gboolean on_scroll(GtkEventControllerScroll*, double dx, double dy, gpointer user_data) {
    auto* app = static_cast<App*>(user_data);
    if (!render_scroll(*app, static_cast<float>(dx) * kWheelScrollGain,
                       static_cast<float>(dy) * kWheelScrollGain)) {
        if (app->status_label) gtk_label_set_text(GTK_LABEL(app->status_label), app->error.c_str());
        return FALSE;
    }
    if (app->drawing) gtk_widget_queue_draw(app->drawing);
    return TRUE;
}

const char* default_library() {
#if defined(_WIN32)
    return "volvoxgrid.dll";
#elif defined(__APPLE__)
    return "libvolvoxgrid.dylib";
#else
    return "libvolvoxgrid.so";
#endif
}

bool boot_engine(App& app) {
    try {
        app.rt->init();
        app.transport = std::make_unique<RuntimeTransport>(app.rt);
        app.client = std::make_unique<vg::VolvoxGridServiceLite>(app.transport.get());

        vg::CreateRequest req;
        req.viewport_width = 800;
        req.viewport_height = 500;
        req.scale = 1.0f;
        req.config = std::make_shared<vg::GridConfig>();
        req.config->scrolling = std::make_shared<vg::ScrollConfig>();
        req.config->scrolling->scrollbars = vg::ScrollBarsMode::SCROLLBAR_BOTH;
        auto create_resp = app.client->Create(req);
        app.grid_id = create_resp.grid_id;
        if (app.grid_id == 0) { app.error = "Create returned no grid_id"; return false; }

        vg::GetDemoDataRequest demo_req;
        demo_req.demo = "sales";
        auto demo_resp = app.client->GetDemoData(demo_req);
        if (demo_resp.data.empty()) { app.error = "GetDemoData(\"sales\") returned no data"; return false; }

        vg::LoadDataRequest load_req;
        load_req.grid_id = app.grid_id;
        load_req.data = std::move(demo_resp.data);
        load_req.options = std::make_shared<vg::LoadDataOptions>();
        load_req.options->auto_create_columns = true;
        app.client->LoadData(load_req);

        app.session = std::make_unique<vg::SynurangLiteBidiStream<vg::RenderInput, vg::RenderOutput>>(
            app.client->RenderSession());
        return true;
    } catch (const std::exception& e) {
        app.error = e.what();
        return false;
    }
}

void on_activate(GtkApplication* gtk_app, gpointer user_data) {
    auto* app = static_cast<App*>(user_data);

    GtkWidget* window = gtk_application_window_new(gtk_app);
    gtk_window_set_title(GTK_WINDOW(window), "VolvoxGrid C++ — sales");
    gtk_window_set_default_size(GTK_WINDOW(window), 800, 500);

    GtkWidget* vbox = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0);

    GtkWidget* drawing = gtk_drawing_area_new();
    gtk_widget_set_hexpand(drawing, TRUE);
    gtk_widget_set_vexpand(drawing, TRUE);
    gtk_drawing_area_set_draw_func(GTK_DRAWING_AREA(drawing), on_draw, app, nullptr);
    g_signal_connect(drawing, "resize", G_CALLBACK(on_resize), app);

    GtkEventController* scroll_ctrl = gtk_event_controller_scroll_new(
        GTK_EVENT_CONTROLLER_SCROLL_BOTH_AXES);
    g_signal_connect(scroll_ctrl, "scroll", G_CALLBACK(on_scroll), app);
    gtk_widget_add_controller(drawing, scroll_ctrl);

    app->drawing = drawing;
    gtk_box_append(GTK_BOX(vbox), drawing);

    app->status_label = gtk_label_new(app->error.empty()
        ? "Resize the window to render the sales demo."
        : app->error.c_str());
    gtk_label_set_xalign(GTK_LABEL(app->status_label), 0.0f);
    gtk_widget_set_margin_start(app->status_label, 8);
    gtk_widget_set_margin_end(app->status_label, 8);
    gtk_widget_set_margin_top(app->status_label, 4);
    gtk_widget_set_margin_bottom(app->status_label, 4);
    gtk_box_append(GTK_BOX(vbox), app->status_label);

    gtk_window_set_child(GTK_WINDOW(window), vbox);
    gtk_window_present(GTK_WINDOW(window));
}

} // namespace

int main(int argc, char** argv) {
    const char* lib = std::getenv("VOLVOXGRID_LIBRARY");
    if (!lib || !*lib) lib = (argc > 1) ? argv[1] : default_library();

    // Order matters: rt must outlive app, because App::session (a Stream) calls
    // back through the Runtime on destruction. Locals are destroyed in reverse
    // declaration order, so declare rt first → destroyed last.
    std::unique_ptr<volvoxgrid::Runtime> rt;
    try {
        rt = std::make_unique<volvoxgrid::Runtime>(lib);
    } catch (const volvoxgrid::Error& e) {
        std::fprintf(stderr, "VolvoxGrid load failed: %s\n", e.what());
        return 1;
    }
    App app;
    app.rt = rt.get();
    if (!boot_engine(app)) {
        std::fprintf(stderr, "VolvoxGrid boot failed: %s\n", app.error.c_str());
    }

    GtkApplication* gtk_app = gtk_application_new("io.github.ivere27.volvoxgrid.CppGtk",
                                                  G_APPLICATION_FLAGS_NONE);
    g_signal_connect(gtk_app, "activate", G_CALLBACK(on_activate), &app);
    int rc = g_application_run(G_APPLICATION(gtk_app), 1, argv);
    g_object_unref(gtk_app);

    if (app.surface) cairo_surface_destroy(app.surface);
    return rc;
}
