const gridOptions = {
  defaultColDef: {
    sortable: true,
    flex: 1,
    minWidth: 90,
  },
  columnDefs: [
    { field: 'rank', headerName: '#', width: 60, flex: undefined },
    { field: 'name', headerName: 'Name' },
    { field: 'score', headerName: 'Score', sort: 'desc' },
    { field: 'team', headerName: 'Team' },
  ],
  rowData: [
    { rank: 1, name: 'Alice', score: 98, team: 'Alpha' },
    { rank: 2, name: 'Bob', score: 95, team: 'Beta' },
    { rank: 3, name: 'Carla', score: 93, team: 'Alpha' },
    { rank: 4, name: 'David', score: 91, team: 'Gamma' },
    { rank: 5, name: 'Eva', score: 89, team: 'Beta' },
    { rank: 6, name: 'Frank', score: 87, team: 'Alpha' },
    { rank: 7, name: 'Grace', score: 85, team: 'Gamma' },
    { rank: 8, name: 'Hana', score: 83, team: 'Beta' },
    { rank: 9, name: 'Ivan', score: 81, team: 'Alpha' },
    { rank: 10, name: 'Joon', score: 79, team: 'Gamma' },
    { rank: 11, name: 'Kate', score: 77, team: 'Beta' },
    { rank: 12, name: 'Luca', score: 75, team: 'Alpha' },
    { rank: 13, name: 'Mina', score: 73, team: 'Gamma' },
    { rank: 14, name: 'Noah', score: 71, team: 'Beta' },
    { rank: 15, name: 'Olivia', score: 69, team: 'Alpha' },
    { rank: 16, name: 'Paul', score: 67, team: 'Gamma' },
    { rank: 17, name: 'Quinn', score: 65, team: 'Beta' },
    { rank: 18, name: 'Rosa', score: 63, team: 'Alpha' },
    { rank: 19, name: 'Sam', score: 61, team: 'Gamma' },
    { rank: 20, name: 'Tara', score: 59, team: 'Beta' },
  ],
};
