// dllmain.cpp -- COM DLL entry point with ATL module
//
// Provides the four standard COM exports and hosts the ATL module.

#include <atlbase.h>
#include <atlcom.h>
#include <atlctl.h>

#include "resource.h"

// Generated by MIDL from VolvoxGrid.idl
#include "VolvoxGrid_i.h"
#include "VolvoxGrid_i.c"

#include "VolvoxGridCtrl.h"

// ═══════════════════════════════════════════════════════════════════
// ATL Module
// ═══════════════════════════════════════════════════════════════════

class CVolvoxGridModule : public ATL::CAtlDllModuleT<CVolvoxGridModule>
{
public:
    DECLARE_LIBID(LIBID_VolvoxGridLib)
    DECLARE_REGISTRY_APPID_RESOURCEID(IDR_FLEXGRID, "{C9A5D6E3-AF40-4B7C-BE8D-3F5A7B9C0D1E}")
};

CVolvoxGridModule _AtlModule;

// ═══════════════════════════════════════════════════════════════════
// Object Map (registers CVolvoxGridCtrl)
// ═══════════════════════════════════════════════════════════════════

OBJECT_ENTRY_AUTO(CLSID_VolvoxGrid, CVolvoxGridCtrl)

// ═══════════════════════════════════════════════════════════════════
// DLL Entry Point
// ═══════════════════════════════════════════════════════════════════

extern "C" BOOL WINAPI DllMain(HINSTANCE hInstance, DWORD dwReason, LPVOID lpReserved)
{
    return _AtlModule.DllMain(dwReason, lpReserved);
}

// ═══════════════════════════════════════════════════════════════════
// COM Standard Exports
// ═══════════════════════════════════════════════════════════════════

STDAPI DllCanUnloadNow()
{
    return _AtlModule.DllCanUnloadNow();
}

STDAPI DllGetClassObject(REFCLSID rclsid, REFIID riid, LPVOID* ppv)
{
    return _AtlModule.DllGetClassObject(rclsid, riid, ppv);
}

STDAPI DllRegisterServer()
{
    return _AtlModule.DllRegisterServer();
}

STDAPI DllUnregisterServer()
{
    return _AtlModule.DllUnregisterServer();
}
