// VolvoxGrid Protocol Contract
//
// This file is the single source of truth for VolvoxGrid's public API.
// Every host — Flutter, Android, Java, .NET, Go, Web — communicates with
// the Rust grid engine through the messages and service defined here.
//
// ─── Design principles ───
//
// 1. One retained grid model.
//    The engine (engine/src/grid.rs) owns a single VolvoxGrid state object
//    per grid: rows, columns, cells, layout, selection, scrolling, editing,
//    sorting, spans, outline, animations, and pending events. Hosts never
//    own grid logic — they forward input and present rendered output.
//
// 2. Partial-update semantics.
//    All configuration messages use `optional` fields. Only fields that are
//    explicitly set are applied; unset fields leave the current value
//    unchanged. This is implemented in engine/src/config.rs via
//    `if let Some(v) = field { apply(v) }` for every optional field.
//    This lets hosts send sparse updates without knowing or restating
//    the full current configuration.
//
// 3. Two streaming interfaces.
//    - RenderSession: bidirectional stream for the real-time render loop.
//      The host sends input (viewport, pointer, key, buffer) and receives
//      immediate render-coupled outputs (FrameDone, EditRequest, CursorChange).
//    - EventStream: server-streaming for semantic grid events (selection
//      changed, before/after edit, sort, scroll, etc.).
//    The split ensures that frame-rate-sensitive rendering is never blocked
//    by application-level event handling.
//
// 4. Cancelable events via EventDecision.
//    Events with a non-zero `event_id` in GridEvent are cancelable.
//    The host sends an EventDecision on the RenderSession with `cancel=true`
//    to veto the action. The engine waits up to 250 ms for a decision;
//    if none arrives, the event proceeds (cancel=false).
//    Events with `event_id=0` are informational and cannot be canceled.
//
// 5. Language-agnostic transport.
//    Native hosts use Synurang FFI to load `libvolvoxgrid_plugin` and
//    exchange these protobuf messages. Web hosts use wasm-bindgen.
//    Any language that can load a shared library and speak protobuf can
//    become a VolvoxGrid host without engine changes.
//
// ─── Color format ───
//
// All `uint32` color fields use ARGB format:
//   bits 24–31 = alpha, 16–23 = red, 8–15 = green, 0–7 = blue.
// Example: 0xFFFF0000 = opaque red, 0x80000000 = 50% transparent black.
// The CPU render buffer uses RGBA byte order in memory (R at offset+0,
// G at offset+1, B at offset+2, A at offset+3). The engine converts
// ARGB→RGBA during rendering (see engine/src/canvas_cpu.rs fill_rect).
//
// ─── Modifier bitmask ───
//
// The `modifier` field on PointerEvent, KeyEvent, and mouse/keyboard
// GridEvent messages uses a bitmask:
//   0x01 = Shift, 0x02 = Ctrl, 0x04 = Alt, 0x08 = Meta.
// Verified in flutter/lib/volvoxgrid.dart and adapters/sheet/src/volvox-sheet.ts.
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.12.4
// source: volvoxgrid.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VolvoxGridService_Create_FullMethodName           = "/volvoxgrid.v1.VolvoxGridService/Create"
	VolvoxGridService_Destroy_FullMethodName          = "/volvoxgrid.v1.VolvoxGridService/Destroy"
	VolvoxGridService_Configure_FullMethodName        = "/volvoxgrid.v1.VolvoxGridService/Configure"
	VolvoxGridService_GetConfig_FullMethodName        = "/volvoxgrid.v1.VolvoxGridService/GetConfig"
	VolvoxGridService_LoadFontData_FullMethodName     = "/volvoxgrid.v1.VolvoxGridService/LoadFontData"
	VolvoxGridService_DefineColumns_FullMethodName    = "/volvoxgrid.v1.VolvoxGridService/DefineColumns"
	VolvoxGridService_GetSchema_FullMethodName        = "/volvoxgrid.v1.VolvoxGridService/GetSchema"
	VolvoxGridService_DefineRows_FullMethodName       = "/volvoxgrid.v1.VolvoxGridService/DefineRows"
	VolvoxGridService_InsertRows_FullMethodName       = "/volvoxgrid.v1.VolvoxGridService/InsertRows"
	VolvoxGridService_RemoveRows_FullMethodName       = "/volvoxgrid.v1.VolvoxGridService/RemoveRows"
	VolvoxGridService_MoveColumn_FullMethodName       = "/volvoxgrid.v1.VolvoxGridService/MoveColumn"
	VolvoxGridService_MoveRow_FullMethodName          = "/volvoxgrid.v1.VolvoxGridService/MoveRow"
	VolvoxGridService_UpdateCells_FullMethodName      = "/volvoxgrid.v1.VolvoxGridService/UpdateCells"
	VolvoxGridService_GetCells_FullMethodName         = "/volvoxgrid.v1.VolvoxGridService/GetCells"
	VolvoxGridService_LoadTable_FullMethodName        = "/volvoxgrid.v1.VolvoxGridService/LoadTable"
	VolvoxGridService_LoadData_FullMethodName         = "/volvoxgrid.v1.VolvoxGridService/LoadData"
	VolvoxGridService_Clear_FullMethodName            = "/volvoxgrid.v1.VolvoxGridService/Clear"
	VolvoxGridService_Select_FullMethodName           = "/volvoxgrid.v1.VolvoxGridService/Select"
	VolvoxGridService_GetSelection_FullMethodName     = "/volvoxgrid.v1.VolvoxGridService/GetSelection"
	VolvoxGridService_ShowCell_FullMethodName         = "/volvoxgrid.v1.VolvoxGridService/ShowCell"
	VolvoxGridService_SetTopRow_FullMethodName        = "/volvoxgrid.v1.VolvoxGridService/SetTopRow"
	VolvoxGridService_SetLeftCol_FullMethodName       = "/volvoxgrid.v1.VolvoxGridService/SetLeftCol"
	VolvoxGridService_Edit_FullMethodName             = "/volvoxgrid.v1.VolvoxGridService/Edit"
	VolvoxGridService_Sort_FullMethodName             = "/volvoxgrid.v1.VolvoxGridService/Sort"
	VolvoxGridService_Subtotal_FullMethodName         = "/volvoxgrid.v1.VolvoxGridService/Subtotal"
	VolvoxGridService_AutoSize_FullMethodName         = "/volvoxgrid.v1.VolvoxGridService/AutoSize"
	VolvoxGridService_Outline_FullMethodName          = "/volvoxgrid.v1.VolvoxGridService/Outline"
	VolvoxGridService_GetNode_FullMethodName          = "/volvoxgrid.v1.VolvoxGridService/GetNode"
	VolvoxGridService_Find_FullMethodName             = "/volvoxgrid.v1.VolvoxGridService/Find"
	VolvoxGridService_Aggregate_FullMethodName        = "/volvoxgrid.v1.VolvoxGridService/Aggregate"
	VolvoxGridService_GetMergedRange_FullMethodName   = "/volvoxgrid.v1.VolvoxGridService/GetMergedRange"
	VolvoxGridService_MergeCells_FullMethodName       = "/volvoxgrid.v1.VolvoxGridService/MergeCells"
	VolvoxGridService_UnmergeCells_FullMethodName     = "/volvoxgrid.v1.VolvoxGridService/UnmergeCells"
	VolvoxGridService_GetMergedRegions_FullMethodName = "/volvoxgrid.v1.VolvoxGridService/GetMergedRegions"
	VolvoxGridService_GetMemoryUsage_FullMethodName   = "/volvoxgrid.v1.VolvoxGridService/GetMemoryUsage"
	VolvoxGridService_Clipboard_FullMethodName        = "/volvoxgrid.v1.VolvoxGridService/Clipboard"
	VolvoxGridService_Export_FullMethodName           = "/volvoxgrid.v1.VolvoxGridService/Export"
	VolvoxGridService_Print_FullMethodName            = "/volvoxgrid.v1.VolvoxGridService/Print"
	VolvoxGridService_Archive_FullMethodName          = "/volvoxgrid.v1.VolvoxGridService/Archive"
	VolvoxGridService_ResizeViewport_FullMethodName   = "/volvoxgrid.v1.VolvoxGridService/ResizeViewport"
	VolvoxGridService_SetRedraw_FullMethodName        = "/volvoxgrid.v1.VolvoxGridService/SetRedraw"
	VolvoxGridService_Refresh_FullMethodName          = "/volvoxgrid.v1.VolvoxGridService/Refresh"
	VolvoxGridService_LoadDemo_FullMethodName         = "/volvoxgrid.v1.VolvoxGridService/LoadDemo"
	VolvoxGridService_GetDemoData_FullMethodName      = "/volvoxgrid.v1.VolvoxGridService/GetDemoData"
	VolvoxGridService_RenderSession_FullMethodName    = "/volvoxgrid.v1.VolvoxGridService/RenderSession"
	VolvoxGridService_EventStream_FullMethodName      = "/volvoxgrid.v1.VolvoxGridService/EventStream"
)

// VolvoxGridServiceClient is the client API for VolvoxGridService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VolvoxGridServiceClient interface {
	// ── Lifecycle ──
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Destroy(ctx context.Context, in *DestroyRequest, opts ...grpc.CallOption) (*DestroyResponse, error)
	// ── Configuration ──
	Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error)
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GridConfig, error)
	LoadFontData(ctx context.Context, in *LoadFontDataRequest, opts ...grpc.CallOption) (*LoadFontDataResponse, error)
	// ── Structure ──
	DefineColumns(ctx context.Context, in *DefineColumnsRequest, opts ...grpc.CallOption) (*DefineColumnsResponse, error)
	GetSchema(ctx context.Context, in *GetSchemaRequest, opts ...grpc.CallOption) (*DefineColumnsRequest, error)
	DefineRows(ctx context.Context, in *DefineRowsRequest, opts ...grpc.CallOption) (*DefineRowsResponse, error)
	InsertRows(ctx context.Context, in *InsertRowsRequest, opts ...grpc.CallOption) (*InsertRowsResponse, error)
	RemoveRows(ctx context.Context, in *RemoveRowsRequest, opts ...grpc.CallOption) (*RemoveRowsResponse, error)
	MoveColumn(ctx context.Context, in *MoveColumnRequest, opts ...grpc.CallOption) (*MoveColumnResponse, error)
	MoveRow(ctx context.Context, in *MoveRowRequest, opts ...grpc.CallOption) (*MoveRowResponse, error)
	// ── Data ──
	UpdateCells(ctx context.Context, in *UpdateCellsRequest, opts ...grpc.CallOption) (*WriteResult, error)
	GetCells(ctx context.Context, in *GetCellsRequest, opts ...grpc.CallOption) (*CellsResponse, error)
	LoadTable(ctx context.Context, in *LoadTableRequest, opts ...grpc.CallOption) (*WriteResult, error)
	LoadData(ctx context.Context, in *LoadDataRequest, opts ...grpc.CallOption) (*LoadDataResult, error)
	Clear(ctx context.Context, in *ClearRequest, opts ...grpc.CallOption) (*ClearResponse, error)
	// ── Selection ──
	Select(ctx context.Context, in *SelectRequest, opts ...grpc.CallOption) (*SelectResponse, error)
	GetSelection(ctx context.Context, in *GetSelectionRequest, opts ...grpc.CallOption) (*SelectionState, error)
	ShowCell(ctx context.Context, in *ShowCellRequest, opts ...grpc.CallOption) (*ShowCellResponse, error)
	SetTopRow(ctx context.Context, in *SetRowRequest, opts ...grpc.CallOption) (*SetTopRowResponse, error)
	SetLeftCol(ctx context.Context, in *SetColRequest, opts ...grpc.CallOption) (*SetLeftColResponse, error)
	// ── Editing ──
	Edit(ctx context.Context, in *EditCommand, opts ...grpc.CallOption) (*EditState, error)
	// ── Actions ──
	Sort(ctx context.Context, in *SortRequest, opts ...grpc.CallOption) (*SortResponse, error)
	Subtotal(ctx context.Context, in *SubtotalRequest, opts ...grpc.CallOption) (*SubtotalResult, error)
	AutoSize(ctx context.Context, in *AutoSizeRequest, opts ...grpc.CallOption) (*AutoSizeResponse, error)
	Outline(ctx context.Context, in *OutlineRequest, opts ...grpc.CallOption) (*OutlineResponse, error)
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*NodeInfo, error)
	Find(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error)
	Aggregate(ctx context.Context, in *AggregateRequest, opts ...grpc.CallOption) (*AggregateResponse, error)
	GetMergedRange(ctx context.Context, in *GetMergedRangeRequest, opts ...grpc.CallOption) (*CellRange, error)
	MergeCells(ctx context.Context, in *MergeCellsRequest, opts ...grpc.CallOption) (*MergeCellsResponse, error)
	UnmergeCells(ctx context.Context, in *UnmergeCellsRequest, opts ...grpc.CallOption) (*UnmergeCellsResponse, error)
	GetMergedRegions(ctx context.Context, in *GetMergedRegionsRequest, opts ...grpc.CallOption) (*MergedRegionsResponse, error)
	GetMemoryUsage(ctx context.Context, in *GetMemoryUsageRequest, opts ...grpc.CallOption) (*MemoryUsageResponse, error)
	// ── Clipboard ──
	Clipboard(ctx context.Context, in *ClipboardCommand, opts ...grpc.CallOption) (*ClipboardResponse, error)
	// ── Export / Print / Archive ──
	Export(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (*ExportResponse, error)
	Print(ctx context.Context, in *PrintRequest, opts ...grpc.CallOption) (*PrintResponse, error)
	Archive(ctx context.Context, in *ArchiveRequest, opts ...grpc.CallOption) (*ArchiveResponse, error)
	// ── Render Control ──
	ResizeViewport(ctx context.Context, in *ResizeViewportRequest, opts ...grpc.CallOption) (*ResizeViewportResponse, error)
	SetRedraw(ctx context.Context, in *SetRedrawRequest, opts ...grpc.CallOption) (*SetRedrawResponse, error)
	Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*RefreshResponse, error)
	// ── Demo ──
	LoadDemo(ctx context.Context, in *LoadDemoRequest, opts ...grpc.CallOption) (*LoadDemoResponse, error)
	GetDemoData(ctx context.Context, in *GetDemoDataRequest, opts ...grpc.CallOption) (*GetDemoDataResponse, error)
	// ── Streaming ──
	// Bidirectional: host sends input (pointer, key, buffer, event decisions),
	// engine returns render-coupled output (frames, edit/dropdown requests).
	RenderSession(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RenderInput, RenderOutput], error)
	// Server-streaming: engine pushes semantic grid events.
	// The plugin polls the engine's EventQueue with a 50 ms interval.
	EventStream(ctx context.Context, in *EventStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GridEvent], error)
}

type volvoxGridServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVolvoxGridServiceClient(cc grpc.ClientConnInterface) VolvoxGridServiceClient {
	return &volvoxGridServiceClient{cc}
}

func (c *volvoxGridServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, VolvoxGridService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volvoxGridServiceClient) Destroy(ctx context.Context, in *DestroyRequest, opts ...grpc.CallOption) (*DestroyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DestroyResponse)
	err := c.cc.Invoke(ctx, VolvoxGridService_Destroy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volvoxGridServiceClient) Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureResponse)
	err := c.cc.Invoke(ctx, VolvoxGridService_Configure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volvoxGridServiceClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GridConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GridConfig)
	err := c.cc.Invoke(ctx, VolvoxGridService_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volvoxGridServiceClient) LoadFontData(ctx context.Context, in *LoadFontDataRequest, opts ...grpc.CallOption) (*LoadFontDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadFontDataResponse)
	err := c.cc.Invoke(ctx, VolvoxGridService_LoadFontData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volvoxGridServiceClient) DefineColumns(ctx context.Context, in *DefineColumnsRequest, opts ...grpc.CallOption) (*DefineColumnsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DefineColumnsResponse)
	err := c.cc.Invoke(ctx, VolvoxGridService_DefineColumns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volvoxGridServiceClient) GetSchema(ctx context.Context, in *GetSchemaRequest, opts ...grpc.CallOption) (*DefineColumnsRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DefineColumnsRequest)
	err := c.cc.Invoke(ctx, VolvoxGridService_GetSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volvoxGridServiceClient) DefineRows(ctx context.Context, in *DefineRowsRequest, opts ...grpc.CallOption) (*DefineRowsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DefineRowsResponse)
	err := c.cc.Invoke(ctx, VolvoxGridService_DefineRows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volvoxGridServiceClient) InsertRows(ctx context.Context, in *InsertRowsRequest, opts ...grpc.CallOption) (*InsertRowsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertRowsResponse)
	err := c.cc.Invoke(ctx, VolvoxGridService_InsertRows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volvoxGridServiceClient) RemoveRows(ctx context.Context, in *RemoveRowsRequest, opts ...grpc.CallOption) (*RemoveRowsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveRowsResponse)
	err := c.cc.Invoke(ctx, VolvoxGridService_RemoveRows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volvoxGridServiceClient) MoveColumn(ctx context.Context, in *MoveColumnRequest, opts ...grpc.CallOption) (*MoveColumnResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MoveColumnResponse)
	err := c.cc.Invoke(ctx, VolvoxGridService_MoveColumn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volvoxGridServiceClient) MoveRow(ctx context.Context, in *MoveRowRequest, opts ...grpc.CallOption) (*MoveRowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MoveRowResponse)
	err := c.cc.Invoke(ctx, VolvoxGridService_MoveRow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volvoxGridServiceClient) UpdateCells(ctx context.Context, in *UpdateCellsRequest, opts ...grpc.CallOption) (*WriteResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteResult)
	err := c.cc.Invoke(ctx, VolvoxGridService_UpdateCells_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volvoxGridServiceClient) GetCells(ctx context.Context, in *GetCellsRequest, opts ...grpc.CallOption) (*CellsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CellsResponse)
	err := c.cc.Invoke(ctx, VolvoxGridService_GetCells_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volvoxGridServiceClient) LoadTable(ctx context.Context, in *LoadTableRequest, opts ...grpc.CallOption) (*WriteResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteResult)
	err := c.cc.Invoke(ctx, VolvoxGridService_LoadTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volvoxGridServiceClient) LoadData(ctx context.Context, in *LoadDataRequest, opts ...grpc.CallOption) (*LoadDataResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadDataResult)
	err := c.cc.Invoke(ctx, VolvoxGridService_LoadData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volvoxGridServiceClient) Clear(ctx context.Context, in *ClearRequest, opts ...grpc.CallOption) (*ClearResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearResponse)
	err := c.cc.Invoke(ctx, VolvoxGridService_Clear_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volvoxGridServiceClient) Select(ctx context.Context, in *SelectRequest, opts ...grpc.CallOption) (*SelectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelectResponse)
	err := c.cc.Invoke(ctx, VolvoxGridService_Select_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volvoxGridServiceClient) GetSelection(ctx context.Context, in *GetSelectionRequest, opts ...grpc.CallOption) (*SelectionState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelectionState)
	err := c.cc.Invoke(ctx, VolvoxGridService_GetSelection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volvoxGridServiceClient) ShowCell(ctx context.Context, in *ShowCellRequest, opts ...grpc.CallOption) (*ShowCellResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShowCellResponse)
	err := c.cc.Invoke(ctx, VolvoxGridService_ShowCell_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volvoxGridServiceClient) SetTopRow(ctx context.Context, in *SetRowRequest, opts ...grpc.CallOption) (*SetTopRowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetTopRowResponse)
	err := c.cc.Invoke(ctx, VolvoxGridService_SetTopRow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volvoxGridServiceClient) SetLeftCol(ctx context.Context, in *SetColRequest, opts ...grpc.CallOption) (*SetLeftColResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetLeftColResponse)
	err := c.cc.Invoke(ctx, VolvoxGridService_SetLeftCol_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volvoxGridServiceClient) Edit(ctx context.Context, in *EditCommand, opts ...grpc.CallOption) (*EditState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EditState)
	err := c.cc.Invoke(ctx, VolvoxGridService_Edit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volvoxGridServiceClient) Sort(ctx context.Context, in *SortRequest, opts ...grpc.CallOption) (*SortResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SortResponse)
	err := c.cc.Invoke(ctx, VolvoxGridService_Sort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volvoxGridServiceClient) Subtotal(ctx context.Context, in *SubtotalRequest, opts ...grpc.CallOption) (*SubtotalResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubtotalResult)
	err := c.cc.Invoke(ctx, VolvoxGridService_Subtotal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volvoxGridServiceClient) AutoSize(ctx context.Context, in *AutoSizeRequest, opts ...grpc.CallOption) (*AutoSizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AutoSizeResponse)
	err := c.cc.Invoke(ctx, VolvoxGridService_AutoSize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volvoxGridServiceClient) Outline(ctx context.Context, in *OutlineRequest, opts ...grpc.CallOption) (*OutlineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OutlineResponse)
	err := c.cc.Invoke(ctx, VolvoxGridService_Outline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volvoxGridServiceClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*NodeInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeInfo)
	err := c.cc.Invoke(ctx, VolvoxGridService_GetNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volvoxGridServiceClient) Find(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindResponse)
	err := c.cc.Invoke(ctx, VolvoxGridService_Find_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volvoxGridServiceClient) Aggregate(ctx context.Context, in *AggregateRequest, opts ...grpc.CallOption) (*AggregateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AggregateResponse)
	err := c.cc.Invoke(ctx, VolvoxGridService_Aggregate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volvoxGridServiceClient) GetMergedRange(ctx context.Context, in *GetMergedRangeRequest, opts ...grpc.CallOption) (*CellRange, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CellRange)
	err := c.cc.Invoke(ctx, VolvoxGridService_GetMergedRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volvoxGridServiceClient) MergeCells(ctx context.Context, in *MergeCellsRequest, opts ...grpc.CallOption) (*MergeCellsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MergeCellsResponse)
	err := c.cc.Invoke(ctx, VolvoxGridService_MergeCells_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volvoxGridServiceClient) UnmergeCells(ctx context.Context, in *UnmergeCellsRequest, opts ...grpc.CallOption) (*UnmergeCellsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnmergeCellsResponse)
	err := c.cc.Invoke(ctx, VolvoxGridService_UnmergeCells_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volvoxGridServiceClient) GetMergedRegions(ctx context.Context, in *GetMergedRegionsRequest, opts ...grpc.CallOption) (*MergedRegionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MergedRegionsResponse)
	err := c.cc.Invoke(ctx, VolvoxGridService_GetMergedRegions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volvoxGridServiceClient) GetMemoryUsage(ctx context.Context, in *GetMemoryUsageRequest, opts ...grpc.CallOption) (*MemoryUsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemoryUsageResponse)
	err := c.cc.Invoke(ctx, VolvoxGridService_GetMemoryUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volvoxGridServiceClient) Clipboard(ctx context.Context, in *ClipboardCommand, opts ...grpc.CallOption) (*ClipboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClipboardResponse)
	err := c.cc.Invoke(ctx, VolvoxGridService_Clipboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volvoxGridServiceClient) Export(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (*ExportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportResponse)
	err := c.cc.Invoke(ctx, VolvoxGridService_Export_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volvoxGridServiceClient) Print(ctx context.Context, in *PrintRequest, opts ...grpc.CallOption) (*PrintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrintResponse)
	err := c.cc.Invoke(ctx, VolvoxGridService_Print_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volvoxGridServiceClient) Archive(ctx context.Context, in *ArchiveRequest, opts ...grpc.CallOption) (*ArchiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArchiveResponse)
	err := c.cc.Invoke(ctx, VolvoxGridService_Archive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volvoxGridServiceClient) ResizeViewport(ctx context.Context, in *ResizeViewportRequest, opts ...grpc.CallOption) (*ResizeViewportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResizeViewportResponse)
	err := c.cc.Invoke(ctx, VolvoxGridService_ResizeViewport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volvoxGridServiceClient) SetRedraw(ctx context.Context, in *SetRedrawRequest, opts ...grpc.CallOption) (*SetRedrawResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetRedrawResponse)
	err := c.cc.Invoke(ctx, VolvoxGridService_SetRedraw_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volvoxGridServiceClient) Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*RefreshResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshResponse)
	err := c.cc.Invoke(ctx, VolvoxGridService_Refresh_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volvoxGridServiceClient) LoadDemo(ctx context.Context, in *LoadDemoRequest, opts ...grpc.CallOption) (*LoadDemoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadDemoResponse)
	err := c.cc.Invoke(ctx, VolvoxGridService_LoadDemo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volvoxGridServiceClient) GetDemoData(ctx context.Context, in *GetDemoDataRequest, opts ...grpc.CallOption) (*GetDemoDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDemoDataResponse)
	err := c.cc.Invoke(ctx, VolvoxGridService_GetDemoData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volvoxGridServiceClient) RenderSession(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RenderInput, RenderOutput], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VolvoxGridService_ServiceDesc.Streams[0], VolvoxGridService_RenderSession_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RenderInput, RenderOutput]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VolvoxGridService_RenderSessionClient = grpc.BidiStreamingClient[RenderInput, RenderOutput]

func (c *volvoxGridServiceClient) EventStream(ctx context.Context, in *EventStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GridEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VolvoxGridService_ServiceDesc.Streams[1], VolvoxGridService_EventStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EventStreamRequest, GridEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VolvoxGridService_EventStreamClient = grpc.ServerStreamingClient[GridEvent]

// VolvoxGridServiceServer is the server API for VolvoxGridService service.
// All implementations must embed UnimplementedVolvoxGridServiceServer
// for forward compatibility.
type VolvoxGridServiceServer interface {
	// ── Lifecycle ──
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Destroy(context.Context, *DestroyRequest) (*DestroyResponse, error)
	// ── Configuration ──
	Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error)
	GetConfig(context.Context, *GetConfigRequest) (*GridConfig, error)
	LoadFontData(context.Context, *LoadFontDataRequest) (*LoadFontDataResponse, error)
	// ── Structure ──
	DefineColumns(context.Context, *DefineColumnsRequest) (*DefineColumnsResponse, error)
	GetSchema(context.Context, *GetSchemaRequest) (*DefineColumnsRequest, error)
	DefineRows(context.Context, *DefineRowsRequest) (*DefineRowsResponse, error)
	InsertRows(context.Context, *InsertRowsRequest) (*InsertRowsResponse, error)
	RemoveRows(context.Context, *RemoveRowsRequest) (*RemoveRowsResponse, error)
	MoveColumn(context.Context, *MoveColumnRequest) (*MoveColumnResponse, error)
	MoveRow(context.Context, *MoveRowRequest) (*MoveRowResponse, error)
	// ── Data ──
	UpdateCells(context.Context, *UpdateCellsRequest) (*WriteResult, error)
	GetCells(context.Context, *GetCellsRequest) (*CellsResponse, error)
	LoadTable(context.Context, *LoadTableRequest) (*WriteResult, error)
	LoadData(context.Context, *LoadDataRequest) (*LoadDataResult, error)
	Clear(context.Context, *ClearRequest) (*ClearResponse, error)
	// ── Selection ──
	Select(context.Context, *SelectRequest) (*SelectResponse, error)
	GetSelection(context.Context, *GetSelectionRequest) (*SelectionState, error)
	ShowCell(context.Context, *ShowCellRequest) (*ShowCellResponse, error)
	SetTopRow(context.Context, *SetRowRequest) (*SetTopRowResponse, error)
	SetLeftCol(context.Context, *SetColRequest) (*SetLeftColResponse, error)
	// ── Editing ──
	Edit(context.Context, *EditCommand) (*EditState, error)
	// ── Actions ──
	Sort(context.Context, *SortRequest) (*SortResponse, error)
	Subtotal(context.Context, *SubtotalRequest) (*SubtotalResult, error)
	AutoSize(context.Context, *AutoSizeRequest) (*AutoSizeResponse, error)
	Outline(context.Context, *OutlineRequest) (*OutlineResponse, error)
	GetNode(context.Context, *GetNodeRequest) (*NodeInfo, error)
	Find(context.Context, *FindRequest) (*FindResponse, error)
	Aggregate(context.Context, *AggregateRequest) (*AggregateResponse, error)
	GetMergedRange(context.Context, *GetMergedRangeRequest) (*CellRange, error)
	MergeCells(context.Context, *MergeCellsRequest) (*MergeCellsResponse, error)
	UnmergeCells(context.Context, *UnmergeCellsRequest) (*UnmergeCellsResponse, error)
	GetMergedRegions(context.Context, *GetMergedRegionsRequest) (*MergedRegionsResponse, error)
	GetMemoryUsage(context.Context, *GetMemoryUsageRequest) (*MemoryUsageResponse, error)
	// ── Clipboard ──
	Clipboard(context.Context, *ClipboardCommand) (*ClipboardResponse, error)
	// ── Export / Print / Archive ──
	Export(context.Context, *ExportRequest) (*ExportResponse, error)
	Print(context.Context, *PrintRequest) (*PrintResponse, error)
	Archive(context.Context, *ArchiveRequest) (*ArchiveResponse, error)
	// ── Render Control ──
	ResizeViewport(context.Context, *ResizeViewportRequest) (*ResizeViewportResponse, error)
	SetRedraw(context.Context, *SetRedrawRequest) (*SetRedrawResponse, error)
	Refresh(context.Context, *RefreshRequest) (*RefreshResponse, error)
	// ── Demo ──
	LoadDemo(context.Context, *LoadDemoRequest) (*LoadDemoResponse, error)
	GetDemoData(context.Context, *GetDemoDataRequest) (*GetDemoDataResponse, error)
	// ── Streaming ──
	// Bidirectional: host sends input (pointer, key, buffer, event decisions),
	// engine returns render-coupled output (frames, edit/dropdown requests).
	RenderSession(grpc.BidiStreamingServer[RenderInput, RenderOutput]) error
	// Server-streaming: engine pushes semantic grid events.
	// The plugin polls the engine's EventQueue with a 50 ms interval.
	EventStream(*EventStreamRequest, grpc.ServerStreamingServer[GridEvent]) error
	mustEmbedUnimplementedVolvoxGridServiceServer()
}

// UnimplementedVolvoxGridServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVolvoxGridServiceServer struct{}

func (UnimplementedVolvoxGridServiceServer) Create(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedVolvoxGridServiceServer) Destroy(context.Context, *DestroyRequest) (*DestroyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Destroy not implemented")
}
func (UnimplementedVolvoxGridServiceServer) Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedVolvoxGridServiceServer) GetConfig(context.Context, *GetConfigRequest) (*GridConfig, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedVolvoxGridServiceServer) LoadFontData(context.Context, *LoadFontDataRequest) (*LoadFontDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadFontData not implemented")
}
func (UnimplementedVolvoxGridServiceServer) DefineColumns(context.Context, *DefineColumnsRequest) (*DefineColumnsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DefineColumns not implemented")
}
func (UnimplementedVolvoxGridServiceServer) GetSchema(context.Context, *GetSchemaRequest) (*DefineColumnsRequest, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSchema not implemented")
}
func (UnimplementedVolvoxGridServiceServer) DefineRows(context.Context, *DefineRowsRequest) (*DefineRowsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DefineRows not implemented")
}
func (UnimplementedVolvoxGridServiceServer) InsertRows(context.Context, *InsertRowsRequest) (*InsertRowsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InsertRows not implemented")
}
func (UnimplementedVolvoxGridServiceServer) RemoveRows(context.Context, *RemoveRowsRequest) (*RemoveRowsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveRows not implemented")
}
func (UnimplementedVolvoxGridServiceServer) MoveColumn(context.Context, *MoveColumnRequest) (*MoveColumnResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MoveColumn not implemented")
}
func (UnimplementedVolvoxGridServiceServer) MoveRow(context.Context, *MoveRowRequest) (*MoveRowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MoveRow not implemented")
}
func (UnimplementedVolvoxGridServiceServer) UpdateCells(context.Context, *UpdateCellsRequest) (*WriteResult, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCells not implemented")
}
func (UnimplementedVolvoxGridServiceServer) GetCells(context.Context, *GetCellsRequest) (*CellsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCells not implemented")
}
func (UnimplementedVolvoxGridServiceServer) LoadTable(context.Context, *LoadTableRequest) (*WriteResult, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadTable not implemented")
}
func (UnimplementedVolvoxGridServiceServer) LoadData(context.Context, *LoadDataRequest) (*LoadDataResult, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadData not implemented")
}
func (UnimplementedVolvoxGridServiceServer) Clear(context.Context, *ClearRequest) (*ClearResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Clear not implemented")
}
func (UnimplementedVolvoxGridServiceServer) Select(context.Context, *SelectRequest) (*SelectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Select not implemented")
}
func (UnimplementedVolvoxGridServiceServer) GetSelection(context.Context, *GetSelectionRequest) (*SelectionState, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSelection not implemented")
}
func (UnimplementedVolvoxGridServiceServer) ShowCell(context.Context, *ShowCellRequest) (*ShowCellResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ShowCell not implemented")
}
func (UnimplementedVolvoxGridServiceServer) SetTopRow(context.Context, *SetRowRequest) (*SetTopRowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetTopRow not implemented")
}
func (UnimplementedVolvoxGridServiceServer) SetLeftCol(context.Context, *SetColRequest) (*SetLeftColResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetLeftCol not implemented")
}
func (UnimplementedVolvoxGridServiceServer) Edit(context.Context, *EditCommand) (*EditState, error) {
	return nil, status.Error(codes.Unimplemented, "method Edit not implemented")
}
func (UnimplementedVolvoxGridServiceServer) Sort(context.Context, *SortRequest) (*SortResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Sort not implemented")
}
func (UnimplementedVolvoxGridServiceServer) Subtotal(context.Context, *SubtotalRequest) (*SubtotalResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Subtotal not implemented")
}
func (UnimplementedVolvoxGridServiceServer) AutoSize(context.Context, *AutoSizeRequest) (*AutoSizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AutoSize not implemented")
}
func (UnimplementedVolvoxGridServiceServer) Outline(context.Context, *OutlineRequest) (*OutlineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Outline not implemented")
}
func (UnimplementedVolvoxGridServiceServer) GetNode(context.Context, *GetNodeRequest) (*NodeInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedVolvoxGridServiceServer) Find(context.Context, *FindRequest) (*FindResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Find not implemented")
}
func (UnimplementedVolvoxGridServiceServer) Aggregate(context.Context, *AggregateRequest) (*AggregateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Aggregate not implemented")
}
func (UnimplementedVolvoxGridServiceServer) GetMergedRange(context.Context, *GetMergedRangeRequest) (*CellRange, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMergedRange not implemented")
}
func (UnimplementedVolvoxGridServiceServer) MergeCells(context.Context, *MergeCellsRequest) (*MergeCellsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MergeCells not implemented")
}
func (UnimplementedVolvoxGridServiceServer) UnmergeCells(context.Context, *UnmergeCellsRequest) (*UnmergeCellsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnmergeCells not implemented")
}
func (UnimplementedVolvoxGridServiceServer) GetMergedRegions(context.Context, *GetMergedRegionsRequest) (*MergedRegionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMergedRegions not implemented")
}
func (UnimplementedVolvoxGridServiceServer) GetMemoryUsage(context.Context, *GetMemoryUsageRequest) (*MemoryUsageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMemoryUsage not implemented")
}
func (UnimplementedVolvoxGridServiceServer) Clipboard(context.Context, *ClipboardCommand) (*ClipboardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Clipboard not implemented")
}
func (UnimplementedVolvoxGridServiceServer) Export(context.Context, *ExportRequest) (*ExportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Export not implemented")
}
func (UnimplementedVolvoxGridServiceServer) Print(context.Context, *PrintRequest) (*PrintResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Print not implemented")
}
func (UnimplementedVolvoxGridServiceServer) Archive(context.Context, *ArchiveRequest) (*ArchiveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Archive not implemented")
}
func (UnimplementedVolvoxGridServiceServer) ResizeViewport(context.Context, *ResizeViewportRequest) (*ResizeViewportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResizeViewport not implemented")
}
func (UnimplementedVolvoxGridServiceServer) SetRedraw(context.Context, *SetRedrawRequest) (*SetRedrawResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetRedraw not implemented")
}
func (UnimplementedVolvoxGridServiceServer) Refresh(context.Context, *RefreshRequest) (*RefreshResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Refresh not implemented")
}
func (UnimplementedVolvoxGridServiceServer) LoadDemo(context.Context, *LoadDemoRequest) (*LoadDemoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadDemo not implemented")
}
func (UnimplementedVolvoxGridServiceServer) GetDemoData(context.Context, *GetDemoDataRequest) (*GetDemoDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDemoData not implemented")
}
func (UnimplementedVolvoxGridServiceServer) RenderSession(grpc.BidiStreamingServer[RenderInput, RenderOutput]) error {
	return status.Error(codes.Unimplemented, "method RenderSession not implemented")
}
func (UnimplementedVolvoxGridServiceServer) EventStream(*EventStreamRequest, grpc.ServerStreamingServer[GridEvent]) error {
	return status.Error(codes.Unimplemented, "method EventStream not implemented")
}
func (UnimplementedVolvoxGridServiceServer) mustEmbedUnimplementedVolvoxGridServiceServer() {}
func (UnimplementedVolvoxGridServiceServer) testEmbeddedByValue()                           {}

// UnsafeVolvoxGridServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VolvoxGridServiceServer will
// result in compilation errors.
type UnsafeVolvoxGridServiceServer interface {
	mustEmbedUnimplementedVolvoxGridServiceServer()
}

func RegisterVolvoxGridServiceServer(s grpc.ServiceRegistrar, srv VolvoxGridServiceServer) {
	// If the following call panics, it indicates UnimplementedVolvoxGridServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VolvoxGridService_ServiceDesc, srv)
}

func _VolvoxGridService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolvoxGridServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolvoxGridService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolvoxGridServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolvoxGridService_Destroy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolvoxGridServiceServer).Destroy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolvoxGridService_Destroy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolvoxGridServiceServer).Destroy(ctx, req.(*DestroyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolvoxGridService_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolvoxGridServiceServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolvoxGridService_Configure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolvoxGridServiceServer).Configure(ctx, req.(*ConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolvoxGridService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolvoxGridServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolvoxGridService_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolvoxGridServiceServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolvoxGridService_LoadFontData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadFontDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolvoxGridServiceServer).LoadFontData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolvoxGridService_LoadFontData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolvoxGridServiceServer).LoadFontData(ctx, req.(*LoadFontDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolvoxGridService_DefineColumns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DefineColumnsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolvoxGridServiceServer).DefineColumns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolvoxGridService_DefineColumns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolvoxGridServiceServer).DefineColumns(ctx, req.(*DefineColumnsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolvoxGridService_GetSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolvoxGridServiceServer).GetSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolvoxGridService_GetSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolvoxGridServiceServer).GetSchema(ctx, req.(*GetSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolvoxGridService_DefineRows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DefineRowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolvoxGridServiceServer).DefineRows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolvoxGridService_DefineRows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolvoxGridServiceServer).DefineRows(ctx, req.(*DefineRowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolvoxGridService_InsertRows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertRowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolvoxGridServiceServer).InsertRows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolvoxGridService_InsertRows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolvoxGridServiceServer).InsertRows(ctx, req.(*InsertRowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolvoxGridService_RemoveRows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolvoxGridServiceServer).RemoveRows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolvoxGridService_RemoveRows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolvoxGridServiceServer).RemoveRows(ctx, req.(*RemoveRowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolvoxGridService_MoveColumn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveColumnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolvoxGridServiceServer).MoveColumn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolvoxGridService_MoveColumn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolvoxGridServiceServer).MoveColumn(ctx, req.(*MoveColumnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolvoxGridService_MoveRow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveRowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolvoxGridServiceServer).MoveRow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolvoxGridService_MoveRow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolvoxGridServiceServer).MoveRow(ctx, req.(*MoveRowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolvoxGridService_UpdateCells_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCellsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolvoxGridServiceServer).UpdateCells(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolvoxGridService_UpdateCells_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolvoxGridServiceServer).UpdateCells(ctx, req.(*UpdateCellsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolvoxGridService_GetCells_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCellsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolvoxGridServiceServer).GetCells(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolvoxGridService_GetCells_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolvoxGridServiceServer).GetCells(ctx, req.(*GetCellsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolvoxGridService_LoadTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolvoxGridServiceServer).LoadTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolvoxGridService_LoadTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolvoxGridServiceServer).LoadTable(ctx, req.(*LoadTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolvoxGridService_LoadData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolvoxGridServiceServer).LoadData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolvoxGridService_LoadData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolvoxGridServiceServer).LoadData(ctx, req.(*LoadDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolvoxGridService_Clear_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolvoxGridServiceServer).Clear(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolvoxGridService_Clear_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolvoxGridServiceServer).Clear(ctx, req.(*ClearRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolvoxGridService_Select_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolvoxGridServiceServer).Select(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolvoxGridService_Select_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolvoxGridServiceServer).Select(ctx, req.(*SelectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolvoxGridService_GetSelection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSelectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolvoxGridServiceServer).GetSelection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolvoxGridService_GetSelection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolvoxGridServiceServer).GetSelection(ctx, req.(*GetSelectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolvoxGridService_ShowCell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowCellRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolvoxGridServiceServer).ShowCell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolvoxGridService_ShowCell_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolvoxGridServiceServer).ShowCell(ctx, req.(*ShowCellRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolvoxGridService_SetTopRow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolvoxGridServiceServer).SetTopRow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolvoxGridService_SetTopRow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolvoxGridServiceServer).SetTopRow(ctx, req.(*SetRowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolvoxGridService_SetLeftCol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetColRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolvoxGridServiceServer).SetLeftCol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolvoxGridService_SetLeftCol_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolvoxGridServiceServer).SetLeftCol(ctx, req.(*SetColRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolvoxGridService_Edit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolvoxGridServiceServer).Edit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolvoxGridService_Edit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolvoxGridServiceServer).Edit(ctx, req.(*EditCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolvoxGridService_Sort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolvoxGridServiceServer).Sort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolvoxGridService_Sort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolvoxGridServiceServer).Sort(ctx, req.(*SortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolvoxGridService_Subtotal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubtotalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolvoxGridServiceServer).Subtotal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolvoxGridService_Subtotal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolvoxGridServiceServer).Subtotal(ctx, req.(*SubtotalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolvoxGridService_AutoSize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AutoSizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolvoxGridServiceServer).AutoSize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolvoxGridService_AutoSize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolvoxGridServiceServer).AutoSize(ctx, req.(*AutoSizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolvoxGridService_Outline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OutlineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolvoxGridServiceServer).Outline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolvoxGridService_Outline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolvoxGridServiceServer).Outline(ctx, req.(*OutlineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolvoxGridService_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolvoxGridServiceServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolvoxGridService_GetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolvoxGridServiceServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolvoxGridService_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolvoxGridServiceServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolvoxGridService_Find_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolvoxGridServiceServer).Find(ctx, req.(*FindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolvoxGridService_Aggregate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AggregateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolvoxGridServiceServer).Aggregate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolvoxGridService_Aggregate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolvoxGridServiceServer).Aggregate(ctx, req.(*AggregateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolvoxGridService_GetMergedRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMergedRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolvoxGridServiceServer).GetMergedRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolvoxGridService_GetMergedRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolvoxGridServiceServer).GetMergedRange(ctx, req.(*GetMergedRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolvoxGridService_MergeCells_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MergeCellsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolvoxGridServiceServer).MergeCells(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolvoxGridService_MergeCells_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolvoxGridServiceServer).MergeCells(ctx, req.(*MergeCellsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolvoxGridService_UnmergeCells_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnmergeCellsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolvoxGridServiceServer).UnmergeCells(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolvoxGridService_UnmergeCells_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolvoxGridServiceServer).UnmergeCells(ctx, req.(*UnmergeCellsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolvoxGridService_GetMergedRegions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMergedRegionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolvoxGridServiceServer).GetMergedRegions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolvoxGridService_GetMergedRegions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolvoxGridServiceServer).GetMergedRegions(ctx, req.(*GetMergedRegionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolvoxGridService_GetMemoryUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemoryUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolvoxGridServiceServer).GetMemoryUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolvoxGridService_GetMemoryUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolvoxGridServiceServer).GetMemoryUsage(ctx, req.(*GetMemoryUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolvoxGridService_Clipboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClipboardCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolvoxGridServiceServer).Clipboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolvoxGridService_Clipboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolvoxGridServiceServer).Clipboard(ctx, req.(*ClipboardCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolvoxGridService_Export_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolvoxGridServiceServer).Export(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolvoxGridService_Export_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolvoxGridServiceServer).Export(ctx, req.(*ExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolvoxGridService_Print_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolvoxGridServiceServer).Print(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolvoxGridService_Print_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolvoxGridServiceServer).Print(ctx, req.(*PrintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolvoxGridService_Archive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolvoxGridServiceServer).Archive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolvoxGridService_Archive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolvoxGridServiceServer).Archive(ctx, req.(*ArchiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolvoxGridService_ResizeViewport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResizeViewportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolvoxGridServiceServer).ResizeViewport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolvoxGridService_ResizeViewport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolvoxGridServiceServer).ResizeViewport(ctx, req.(*ResizeViewportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolvoxGridService_SetRedraw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRedrawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolvoxGridServiceServer).SetRedraw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolvoxGridService_SetRedraw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolvoxGridServiceServer).SetRedraw(ctx, req.(*SetRedrawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolvoxGridService_Refresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolvoxGridServiceServer).Refresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolvoxGridService_Refresh_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolvoxGridServiceServer).Refresh(ctx, req.(*RefreshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolvoxGridService_LoadDemo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadDemoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolvoxGridServiceServer).LoadDemo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolvoxGridService_LoadDemo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolvoxGridServiceServer).LoadDemo(ctx, req.(*LoadDemoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolvoxGridService_GetDemoData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDemoDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolvoxGridServiceServer).GetDemoData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolvoxGridService_GetDemoData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolvoxGridServiceServer).GetDemoData(ctx, req.(*GetDemoDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolvoxGridService_RenderSession_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VolvoxGridServiceServer).RenderSession(&grpc.GenericServerStream[RenderInput, RenderOutput]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VolvoxGridService_RenderSessionServer = grpc.BidiStreamingServer[RenderInput, RenderOutput]

func _VolvoxGridService_EventStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EventStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VolvoxGridServiceServer).EventStream(m, &grpc.GenericServerStream[EventStreamRequest, GridEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VolvoxGridService_EventStreamServer = grpc.ServerStreamingServer[GridEvent]

// VolvoxGridService_ServiceDesc is the grpc.ServiceDesc for VolvoxGridService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VolvoxGridService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "volvoxgrid.v1.VolvoxGridService",
	HandlerType: (*VolvoxGridServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _VolvoxGridService_Create_Handler,
		},
		{
			MethodName: "Destroy",
			Handler:    _VolvoxGridService_Destroy_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _VolvoxGridService_Configure_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _VolvoxGridService_GetConfig_Handler,
		},
		{
			MethodName: "LoadFontData",
			Handler:    _VolvoxGridService_LoadFontData_Handler,
		},
		{
			MethodName: "DefineColumns",
			Handler:    _VolvoxGridService_DefineColumns_Handler,
		},
		{
			MethodName: "GetSchema",
			Handler:    _VolvoxGridService_GetSchema_Handler,
		},
		{
			MethodName: "DefineRows",
			Handler:    _VolvoxGridService_DefineRows_Handler,
		},
		{
			MethodName: "InsertRows",
			Handler:    _VolvoxGridService_InsertRows_Handler,
		},
		{
			MethodName: "RemoveRows",
			Handler:    _VolvoxGridService_RemoveRows_Handler,
		},
		{
			MethodName: "MoveColumn",
			Handler:    _VolvoxGridService_MoveColumn_Handler,
		},
		{
			MethodName: "MoveRow",
			Handler:    _VolvoxGridService_MoveRow_Handler,
		},
		{
			MethodName: "UpdateCells",
			Handler:    _VolvoxGridService_UpdateCells_Handler,
		},
		{
			MethodName: "GetCells",
			Handler:    _VolvoxGridService_GetCells_Handler,
		},
		{
			MethodName: "LoadTable",
			Handler:    _VolvoxGridService_LoadTable_Handler,
		},
		{
			MethodName: "LoadData",
			Handler:    _VolvoxGridService_LoadData_Handler,
		},
		{
			MethodName: "Clear",
			Handler:    _VolvoxGridService_Clear_Handler,
		},
		{
			MethodName: "Select",
			Handler:    _VolvoxGridService_Select_Handler,
		},
		{
			MethodName: "GetSelection",
			Handler:    _VolvoxGridService_GetSelection_Handler,
		},
		{
			MethodName: "ShowCell",
			Handler:    _VolvoxGridService_ShowCell_Handler,
		},
		{
			MethodName: "SetTopRow",
			Handler:    _VolvoxGridService_SetTopRow_Handler,
		},
		{
			MethodName: "SetLeftCol",
			Handler:    _VolvoxGridService_SetLeftCol_Handler,
		},
		{
			MethodName: "Edit",
			Handler:    _VolvoxGridService_Edit_Handler,
		},
		{
			MethodName: "Sort",
			Handler:    _VolvoxGridService_Sort_Handler,
		},
		{
			MethodName: "Subtotal",
			Handler:    _VolvoxGridService_Subtotal_Handler,
		},
		{
			MethodName: "AutoSize",
			Handler:    _VolvoxGridService_AutoSize_Handler,
		},
		{
			MethodName: "Outline",
			Handler:    _VolvoxGridService_Outline_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _VolvoxGridService_GetNode_Handler,
		},
		{
			MethodName: "Find",
			Handler:    _VolvoxGridService_Find_Handler,
		},
		{
			MethodName: "Aggregate",
			Handler:    _VolvoxGridService_Aggregate_Handler,
		},
		{
			MethodName: "GetMergedRange",
			Handler:    _VolvoxGridService_GetMergedRange_Handler,
		},
		{
			MethodName: "MergeCells",
			Handler:    _VolvoxGridService_MergeCells_Handler,
		},
		{
			MethodName: "UnmergeCells",
			Handler:    _VolvoxGridService_UnmergeCells_Handler,
		},
		{
			MethodName: "GetMergedRegions",
			Handler:    _VolvoxGridService_GetMergedRegions_Handler,
		},
		{
			MethodName: "GetMemoryUsage",
			Handler:    _VolvoxGridService_GetMemoryUsage_Handler,
		},
		{
			MethodName: "Clipboard",
			Handler:    _VolvoxGridService_Clipboard_Handler,
		},
		{
			MethodName: "Export",
			Handler:    _VolvoxGridService_Export_Handler,
		},
		{
			MethodName: "Print",
			Handler:    _VolvoxGridService_Print_Handler,
		},
		{
			MethodName: "Archive",
			Handler:    _VolvoxGridService_Archive_Handler,
		},
		{
			MethodName: "ResizeViewport",
			Handler:    _VolvoxGridService_ResizeViewport_Handler,
		},
		{
			MethodName: "SetRedraw",
			Handler:    _VolvoxGridService_SetRedraw_Handler,
		},
		{
			MethodName: "Refresh",
			Handler:    _VolvoxGridService_Refresh_Handler,
		},
		{
			MethodName: "LoadDemo",
			Handler:    _VolvoxGridService_LoadDemo_Handler,
		},
		{
			MethodName: "GetDemoData",
			Handler:    _VolvoxGridService_GetDemoData_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RenderSession",
			Handler:       _VolvoxGridService_RenderSession_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "EventStream",
			Handler:       _VolvoxGridService_EventStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "volvoxgrid.proto",
}
