import "wtypes.idl";

[
    uuid(00000000-0000-0000-C000-000000000046),
    object,
    pointer_default(unique)
]
interface IUnknown {
    HRESULT QueryInterface([in] REFIID riid, [out, iid_is(riid)] void **ppvObject);
    ULONG AddRef();
    ULONG Release();
};
