// Code generated by protoc-gen-synurang-ffi. DO NOT EDIT.
// Rust Plugin Server Implementation for Synurang FFI

#![allow(unused_imports)]
#![allow(dead_code)]
use super::*;

use prost::Message;
use std::collections::HashMap;
use std::ffi::{c_char, c_int, c_void, CStr};
use std::ptr;
use std::sync::{Arc, Mutex, RwLock};
use std::sync::atomic::{AtomicU64, Ordering};

// =============================================================================
// Stream Infrastructure
// =============================================================================

struct StreamContext {
    send_queue: Mutex<Vec<Vec<u8>>>,  // host -> plugin
    recv_queue: Mutex<Vec<Vec<u8>>>,  // plugin -> host
    send_cv: std::sync::Condvar,
    recv_cv: std::sync::Condvar,
    closed: std::sync::atomic::AtomicBool,
    send_closed: std::sync::atomic::AtomicBool,
}

impl StreamContext {
    fn new() -> Self {
        Self {
            send_queue: Mutex::new(Vec::new()),
            recv_queue: Mutex::new(Vec::new()),
            send_cv: std::sync::Condvar::new(),
            recv_cv: std::sync::Condvar::new(),
            closed: std::sync::atomic::AtomicBool::new(false),
            send_closed: std::sync::atomic::AtomicBool::new(false),
        }
    }
    
    fn send_to_plugin(&self, data: Vec<u8>) {
        if let Ok(mut queue) = self.send_queue.lock() {
            queue.push(data);
            self.send_cv.notify_one();
        }
    }
    
    fn recv_from_plugin(&self) -> Option<Vec<u8>> {
        let mut queue = self.recv_queue.lock().ok()?;
        loop {
            if !queue.is_empty() {
                return Some(queue.remove(0));
            }
            if self.closed.load(Ordering::SeqCst) {
                return None;
            }
            queue = self.recv_cv.wait(queue).ok()?;
        }
    }
    
    fn close(&self) {
        // Hold send_queue lock to prevent lost wakeup on send_cv
        {
            let _guard = self.send_queue.lock();
            self.closed.store(true, Ordering::SeqCst);
        }
        self.send_cv.notify_all();
        // Hold recv_queue lock to prevent lost wakeup on recv_cv
        {
            let _guard = self.recv_queue.lock();
        }
        self.recv_cv.notify_all();
    }
    
    fn is_closed(&self) -> bool {
        self.closed.load(Ordering::SeqCst)
    }
}

lazy_static::lazy_static! {
    static ref STREAMS: RwLock<HashMap<u64, Arc<StreamContext>>> = RwLock::new(HashMap::new());
    static ref NEXT_HANDLE: AtomicU64 = AtomicU64::new(1);
}

fn get_stream(handle: u64) -> Option<Arc<StreamContext>> {
    STREAMS.read().ok()?.get(&handle).cloned()
}

// =============================================================================
// Plugin Trait
// =============================================================================


pub trait VolvoxGridServicePlugin: Send + Sync + 'static {
    fn create(&self, request: CreateRequest) -> Result<GridHandle, String>;
    fn destroy(&self, request: GridHandle) -> Result<Empty, String>;
    fn configure(&self, request: ConfigureRequest) -> Result<Empty, String>;
    fn get_config(&self, request: GridHandle) -> Result<GridConfig, String>;
    fn load_font_data(&self, request: LoadFontDataRequest) -> Result<Empty, String>;
    fn define_columns(&self, request: DefineColumnsRequest) -> Result<Empty, String>;
    fn get_schema(&self, request: GridHandle) -> Result<DefineColumnsRequest, String>;
    fn define_rows(&self, request: DefineRowsRequest) -> Result<Empty, String>;
    fn insert_rows(&self, request: InsertRowsRequest) -> Result<Empty, String>;
    fn remove_rows(&self, request: RemoveRowsRequest) -> Result<Empty, String>;
    fn move_column(&self, request: MoveColumnRequest) -> Result<Empty, String>;
    fn move_row(&self, request: MoveRowRequest) -> Result<Empty, String>;
    fn update_cells(&self, request: UpdateCellsRequest) -> Result<WriteResult, String>;
    fn get_cells(&self, request: GetCellsRequest) -> Result<CellsResponse, String>;
    fn load_table(&self, request: LoadTableRequest) -> Result<WriteResult, String>;
    fn clear(&self, request: ClearRequest) -> Result<Empty, String>;
    fn select(&self, request: SelectRequest) -> Result<Empty, String>;
    fn get_selection(&self, request: GridHandle) -> Result<SelectionState, String>;
    fn edit(&self, request: EditCommand) -> Result<EditState, String>;
    fn sort(&self, request: SortRequest) -> Result<Empty, String>;
    fn subtotal(&self, request: SubtotalRequest) -> Result<Empty, String>;
    fn auto_size(&self, request: AutoSizeRequest) -> Result<Empty, String>;
    fn outline(&self, request: OutlineRequest) -> Result<Empty, String>;
    fn get_node(&self, request: GetNodeRequest) -> Result<NodeInfo, String>;
    fn find(&self, request: FindRequest) -> Result<FindResponse, String>;
    fn aggregate(&self, request: AggregateRequest) -> Result<AggregateResponse, String>;
    fn get_merged_range(&self, request: GetMergedRangeRequest) -> Result<CellRange, String>;
    fn merge_cells(&self, request: MergeCellsRequest) -> Result<Empty, String>;
    fn unmerge_cells(&self, request: UnmergeCellsRequest) -> Result<Empty, String>;
    fn get_merged_regions(&self, request: GridHandle) -> Result<MergedRegionsResponse, String>;
    fn get_memory_usage(&self, request: GridHandle) -> Result<MemoryUsageResponse, String>;
    fn clipboard(&self, request: ClipboardCommand) -> Result<ClipboardResponse, String>;
    fn export(&self, request: ExportRequest) -> Result<ExportResponse, String>;
    fn import(&self, request: ImportRequest) -> Result<Empty, String>;
    fn print(&self, request: PrintRequest) -> Result<PrintResponse, String>;
    fn archive(&self, request: ArchiveRequest) -> Result<ArchiveResponse, String>;
    fn resize_viewport(&self, request: ResizeViewportRequest) -> Result<Empty, String>;
    fn set_redraw(&self, request: SetRedrawRequest) -> Result<Empty, String>;
    fn refresh(&self, request: GridHandle) -> Result<Empty, String>;
    fn load_demo(&self, request: LoadDemoRequest) -> Result<Empty, String>;
    fn render_session(&self, stream: &dyn PluginStreamBidi<RenderInput, RenderOutput>) -> Result<(), String>;
    fn event_stream(&self, request: GridHandle, stream: &dyn PluginStreamSender<GridEvent>) -> Result<(), String>;
}

static PLUGIN_VOLVOX_GRID_SERVICE: std::sync::OnceLock<Box<dyn VolvoxGridServicePlugin>> = std::sync::OnceLock::new();

pub fn register_volvox_grid_service_plugin(plugin: impl VolvoxGridServicePlugin) {
    let _ = PLUGIN_VOLVOX_GRID_SERVICE.set(Box::new(plugin));
}

fn get_volvox_grid_service_plugin() -> Option<&'static dyn VolvoxGridServicePlugin> {
    Some(PLUGIN_VOLVOX_GRID_SERVICE.get_or_init(super::create_plugin).as_ref())
}


// =============================================================================
// Stream Interfaces
// =============================================================================

pub trait PluginStreamSender<T> {
    fn send(&self, msg: T) -> bool;
    fn is_cancelled(&self) -> bool;
}

pub trait PluginStreamReceiver<T> {
    fn recv(&self) -> Option<T>;
    fn is_cancelled(&self) -> bool;
}

pub trait PluginStreamBidi<Req, Resp>: PluginStreamSender<Resp> + PluginStreamReceiver<Req> {}

struct StreamSender<T> {
    ctx: Arc<StreamContext>,
    _marker: std::marker::PhantomData<T>,
}

impl<T: Message + Default> PluginStreamSender<T> for StreamSender<T> {
    fn send(&self, msg: T) -> bool {
        if self.ctx.is_closed() {
            return false;
        }
        let mut buf = Vec::new();
        if msg.encode(&mut buf).is_err() {
            return false;
        }
        // Format: [status:1][payload]
        let mut result = vec![0u8]; // success
        result.extend(buf);
        if let Ok(mut queue) = self.ctx.recv_queue.lock() {
            queue.push(result);
            self.ctx.recv_cv.notify_one();
        }
        true
    }
    
    fn is_cancelled(&self) -> bool {
        self.ctx.is_closed()
    }
}

struct StreamReceiver<T> {
    ctx: Arc<StreamContext>,
    _marker: std::marker::PhantomData<T>,
}

impl<T: Message + Default> PluginStreamReceiver<T> for StreamReceiver<T> {
    fn recv(&self) -> Option<T> {
        let mut queue = self.ctx.send_queue.lock().ok()?;
        loop {
            if self.ctx.is_closed() {
                return None;
            }
            if !queue.is_empty() {
                let data = queue.remove(0);  // FIFO order
                return T::decode(data.as_slice()).ok();
            }
            if self.ctx.send_closed.load(Ordering::SeqCst) && queue.is_empty() {
                return None;
            }
            queue = self.ctx.send_cv.wait(queue).ok()?;
        }
    }
    
    fn is_cancelled(&self) -> bool {
        self.ctx.is_closed()
    }
}

struct StreamBidi<Req, Resp> {
    sender: StreamSender<Resp>,
    receiver: StreamReceiver<Req>,
}

impl<Req: Message + Default, Resp: Message + Default> PluginStreamSender<Resp> for StreamBidi<Req, Resp> {
    fn send(&self, msg: Resp) -> bool {
        self.sender.send(msg)
    }
    fn is_cancelled(&self) -> bool {
        self.sender.is_cancelled()
    }
}

impl<Req: Message + Default, Resp: Message + Default> PluginStreamReceiver<Req> for StreamBidi<Req, Resp> {
    fn recv(&self) -> Option<Req> {
        self.receiver.recv()
    }
    fn is_cancelled(&self) -> bool {
        self.receiver.is_cancelled()
    }
}

impl<Req: Message + Default, Resp: Message + Default> PluginStreamBidi<Req, Resp> for StreamBidi<Req, Resp> {}

// =============================================================================
// C ABI Exports
// =============================================================================

#[no_mangle]
pub extern "C" fn Synurang_Free(ptr: *mut c_void) {
    if !ptr.is_null() {
        unsafe {
            let _ = Box::from_raw(ptr as *mut u8);
        }
    }
}


#[no_mangle]
pub extern "C" fn Synurang_Invoke_VolvoxGridService(
    method: *const c_char,
    data: *const c_char,
    data_len: c_int,
    resp_len: *mut c_int,
) -> *mut c_char {
    let method_str = unsafe {
        if method.is_null() {
            return error_response(resp_len, "null method");
        }
        match CStr::from_ptr(method).to_str() {
            Ok(s) => s,
            Err(_) => return error_response(resp_len, "invalid method utf8"),
        }
    };
    
    let input = if data.is_null() || data_len <= 0 {
        Vec::new()
    } else {
        unsafe { std::slice::from_raw_parts(data as *const u8, data_len as usize).to_vec() }
    };
    
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => return error_response(resp_len, "plugin not registered"),
    };
    
    match method_str {
        "/volvoxgrid.v1.VolvoxGridService/Create" => {
            match CreateRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.create(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/Destroy" => {
            match GridHandle::decode(input.as_slice()) {
                Ok(req) => match plugin.destroy(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/Configure" => {
            match ConfigureRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.configure(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/GetConfig" => {
            match GridHandle::decode(input.as_slice()) {
                Ok(req) => match plugin.get_config(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/LoadFontData" => {
            match LoadFontDataRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.load_font_data(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/DefineColumns" => {
            match DefineColumnsRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.define_columns(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/GetSchema" => {
            match GridHandle::decode(input.as_slice()) {
                Ok(req) => match plugin.get_schema(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/DefineRows" => {
            match DefineRowsRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.define_rows(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/InsertRows" => {
            match InsertRowsRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.insert_rows(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/RemoveRows" => {
            match RemoveRowsRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.remove_rows(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/MoveColumn" => {
            match MoveColumnRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.move_column(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/MoveRow" => {
            match MoveRowRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.move_row(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/UpdateCells" => {
            match UpdateCellsRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.update_cells(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/GetCells" => {
            match GetCellsRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.get_cells(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/LoadTable" => {
            match LoadTableRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.load_table(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/Clear" => {
            match ClearRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.clear(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/Select" => {
            match SelectRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.select(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/GetSelection" => {
            match GridHandle::decode(input.as_slice()) {
                Ok(req) => match plugin.get_selection(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/Edit" => {
            match EditCommand::decode(input.as_slice()) {
                Ok(req) => match plugin.edit(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/Sort" => {
            match SortRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.sort(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/Subtotal" => {
            match SubtotalRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.subtotal(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/AutoSize" => {
            match AutoSizeRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.auto_size(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/Outline" => {
            match OutlineRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.outline(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/GetNode" => {
            match GetNodeRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.get_node(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/Find" => {
            match FindRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.find(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/Aggregate" => {
            match AggregateRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.aggregate(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/GetMergedRange" => {
            match GetMergedRangeRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.get_merged_range(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/MergeCells" => {
            match MergeCellsRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.merge_cells(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/UnmergeCells" => {
            match UnmergeCellsRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.unmerge_cells(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/GetMergedRegions" => {
            match GridHandle::decode(input.as_slice()) {
                Ok(req) => match plugin.get_merged_regions(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/GetMemoryUsage" => {
            match GridHandle::decode(input.as_slice()) {
                Ok(req) => match plugin.get_memory_usage(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/Clipboard" => {
            match ClipboardCommand::decode(input.as_slice()) {
                Ok(req) => match plugin.clipboard(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/Export" => {
            match ExportRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.export(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/Import" => {
            match ImportRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.import(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/Print" => {
            match PrintRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.print(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/Archive" => {
            match ArchiveRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.archive(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/ResizeViewport" => {
            match ResizeViewportRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.resize_viewport(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/SetRedraw" => {
            match SetRedrawRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.set_redraw(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/Refresh" => {
            match GridHandle::decode(input.as_slice()) {
                Ok(req) => match plugin.refresh(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/LoadDemo" => {
            match LoadDemoRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.load_demo(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        _ => error_response(resp_len, "unknown method"),
    }
}


#[no_mangle]
pub extern "C" fn Synurang_Stream_VolvoxGridService_Open(method: *const c_char) -> u64 {
    let method_str = unsafe {
        if method.is_null() {
            return 0;
        }
        match CStr::from_ptr(method).to_str() {
            Ok(s) => s.to_string(),
            Err(_) => return 0,
        }
    };
    
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => return 0,
    };
    
    let ctx = Arc::new(StreamContext::new());
    let handle = NEXT_HANDLE.fetch_add(1, Ordering::SeqCst);
    
    {
        let mut streams = STREAMS.write().unwrap();
        streams.insert(handle, ctx.clone());
    }
    
    // Start handler thread
    let ctx_clone = ctx.clone();
    let _ = std::thread::spawn(move || {
        match method_str.as_str() {
            "/volvoxgrid.v1.VolvoxGridService/RenderSession" => {
                let bidi = StreamBidi::<RenderInput, RenderOutput> {
                    sender: StreamSender {
                        ctx: ctx_clone.clone(),
                        _marker: std::marker::PhantomData,
                    },
                    receiver: StreamReceiver {
                        ctx: ctx_clone.clone(),
                        _marker: std::marker::PhantomData,
                    },
                };
                let _ = plugin.render_session(&bidi);
                ctx_clone.close();
            }
            "/volvoxgrid.v1.VolvoxGridService/EventStream" => {
                // Wait for initial request using Condvar
                let data = {
                    let mut queue = match ctx_clone.send_queue.lock() {
                        Ok(q) => q,
                        Err(_) => return,
                    };
                    loop {
                        if ctx_clone.is_closed() { return; }
                        if !queue.is_empty() {
                            break queue.remove(0);  // FIFO order
                        }
                        queue = match ctx_clone.send_cv.wait(queue) {
                            Ok(q) => q,
                            Err(_) => return,
                        };
                    }
                };
                if let Ok(req) = GridHandle::decode(data.as_slice()) {
                    let sender = StreamSender::<GridEvent> {
                        ctx: ctx_clone.clone(),
                        _marker: std::marker::PhantomData,
                    };
                    let _ = plugin.event_stream(req, &sender);
                }
                ctx_clone.close();
            }
            _ => {}
        }
    });
    
    handle
}




#[no_mangle]
pub extern "C" fn Synurang_Stream_Send(handle: u64, data: *const c_char, data_len: c_int) -> c_int {
    let ctx = match get_stream(handle) {
        Some(c) => c,
        None => return -1,
    };
    
    if ctx.is_closed() {
        return -1;
    }
    
    let bytes = if data.is_null() || data_len <= 0 {
        Vec::new()
    } else {
        unsafe { std::slice::from_raw_parts(data as *const u8, data_len as usize).to_vec() }
    };
    
    ctx.send_to_plugin(bytes);
    0
}

#[no_mangle]
pub extern "C" fn Synurang_Stream_Recv(
    handle: u64,
    resp_len: *mut c_int,
    status: *mut c_int,
) -> *mut c_char {
    let ctx = match get_stream(handle) {
        Some(c) => c,
        None => {
            unsafe { *status = 2; *resp_len = 0; }
            return ptr::null_mut();
        }
    };
    
    // Block for data using Condvar (no busy-wait polling)
    match ctx.recv_from_plugin() {
        Some(data) => {
            let ptr = Box::into_raw(data.clone().into_boxed_slice()) as *mut c_char;
            unsafe {
                *resp_len = data.len() as c_int;
                *status = 0;
            }
            ptr
        }
        None => {
            unsafe {
                *status = 1; // EOF
                *resp_len = 0;
            }
            ptr::null_mut()
        }
    }
}

#[no_mangle]
pub extern "C" fn Synurang_Stream_CloseSend(handle: u64) {
    if let Some(ctx) = get_stream(handle) {
        {
            let _guard = ctx.send_queue.lock();
            ctx.send_closed.store(true, Ordering::SeqCst);
        }
        ctx.send_cv.notify_all();
    }
}

#[no_mangle]
pub extern "C" fn Synurang_Stream_Close(handle: u64) {
    if let Some(ctx) = get_stream(handle) {
        ctx.close();  // This now notifies all waiters
    }
    if let Ok(mut streams) = STREAMS.write() {
        streams.remove(&handle);
    }
}


// =============================================================================
// Helper Functions
// =============================================================================

fn error_response(resp_len: *mut c_int, msg: &str) -> *mut c_char {
    let mut result = vec![1u8]; // error status
    result.extend(msg.as_bytes());
    unsafe { *resp_len = result.len() as c_int; }
    Box::into_raw(result.into_boxed_slice()) as *mut c_char
}

fn success_response(resp_len: *mut c_int, data: &[u8]) -> *mut c_char {
    let mut result = vec![0u8]; // success status
    result.extend(data);
    unsafe { *resp_len = result.len() as c_int; }
    Box::into_raw(result.into_boxed_slice()) as *mut c_char
}

// Module: volvoxgrid_v1

