// Code generated by protoc-gen-synurang-ffi. DO NOT EDIT.
// Rust Plugin Server Implementation for Synurang FFI

#![allow(unused_imports)]
#![allow(dead_code)]
use super::*;

use prost::Message;
use std::collections::HashMap;
use std::ffi::{c_char, c_int, c_void, CStr};
use std::ptr;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::{Arc, Mutex, OnceLock, RwLock};

unsafe extern "C" {
    fn malloc(size: usize) -> *mut c_void;
    fn free(ptr: *mut c_void);
}

#[derive(Clone, PartialEq, Message)]
struct CoreFfiError {
    #[prost(int32, tag = "1")]
    code: i32,
    #[prost(string, tag = "2")]
    message: String,
    #[prost(int32, tag = "3")]
    grpc_code: i32,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FfiError {
    pub message: String,
    pub code: i32,
    pub grpc_code: i32,
}

impl FfiError {
    pub fn new(message: impl Into<String>, code: i32, grpc_code: i32) -> Self {
        Self {
            message: message.into(),
            code,
            grpc_code,
        }
    }
}

impl std::fmt::Display for FfiError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.message.fmt(f)
    }
}

impl std::error::Error for FfiError {}

impl From<String> for FfiError {
    fn from(message: String) -> Self {
        Self::new(message, 0, 2)
    }
}

impl From<&str> for FfiError {
    fn from(message: &str) -> Self {
        Self::new(message, 0, 2)
    }
}

impl From<&String> for FfiError {
    fn from(message: &String) -> Self {
        Self::from(message.as_str())
    }
}

impl From<&FfiError> for FfiError {
    fn from(error: &FfiError) -> Self {
        error.clone()
    }
}

// =============================================================================
// Stream Infrastructure
// =============================================================================

struct StreamContext {
    send_queue: Mutex<Vec<Vec<u8>>>,      // host -> plugin
    recv_queue: Mutex<Vec<StreamResult>>, // plugin -> host
    worker: Mutex<Option<std::thread::JoinHandle<()>>>,
    send_cv: std::sync::Condvar,
    recv_cv: std::sync::Condvar,
    closed: std::sync::atomic::AtomicBool,
    send_closed: std::sync::atomic::AtomicBool,
}

struct StreamResult {
    status: i32,
    payload: Vec<u8>,
}

impl StreamContext {
    fn new() -> Self {
        Self {
            send_queue: Mutex::new(Vec::new()),
            recv_queue: Mutex::new(Vec::new()),
            worker: Mutex::new(None),
            send_cv: std::sync::Condvar::new(),
            recv_cv: std::sync::Condvar::new(),
            closed: std::sync::atomic::AtomicBool::new(false),
            send_closed: std::sync::atomic::AtomicBool::new(false),
        }
    }

    fn send_to_plugin(&self, data: Vec<u8>) {
        if let Ok(mut queue) = self.send_queue.lock() {
            queue.push(data);
            self.send_cv.notify_one();
        }
    }

    fn push_recv_result(&self, status: i32, payload: Vec<u8>) {
        if let Ok(mut queue) = self.recv_queue.lock() {
            queue.push(StreamResult { status, payload });
            self.recv_cv.notify_one();
        }
    }

    fn recv_from_plugin(&self) -> Option<StreamResult> {
        let mut queue = self.recv_queue.lock().ok()?;
        loop {
            if !queue.is_empty() {
                return Some(queue.remove(0));
            }
            if self.closed.load(Ordering::SeqCst) {
                return None;
            }
            queue = self.recv_cv.wait(queue).ok()?;
        }
    }

    fn close(&self) {
        // Hold send_queue lock to prevent lost wakeup on send_cv
        {
            let _guard = self.send_queue.lock();
            self.closed.store(true, Ordering::SeqCst);
        }
        self.send_cv.notify_all();
        // Hold recv_queue lock to prevent lost wakeup on recv_cv
        {
            let _guard = self.recv_queue.lock();
        }
        self.recv_cv.notify_all();
    }

    fn is_closed(&self) -> bool {
        self.closed.load(Ordering::SeqCst)
    }

    fn set_worker(&self, worker: std::thread::JoinHandle<()>) {
        if let Ok(mut slot) = self.worker.lock() {
            *slot = Some(worker);
        }
    }

    fn take_worker(&self) -> Option<std::thread::JoinHandle<()>> {
        self.worker.lock().ok()?.take()
    }
}

static STREAMS: OnceLock<RwLock<HashMap<u64, Arc<StreamContext>>>> = OnceLock::new();
static NEXT_HANDLE: OnceLock<AtomicU64> = OnceLock::new();

fn streams() -> &'static RwLock<HashMap<u64, Arc<StreamContext>>> {
    STREAMS.get_or_init(|| RwLock::new(HashMap::new()))
}

fn next_handle() -> &'static AtomicU64 {
    NEXT_HANDLE.get_or_init(|| AtomicU64::new(1))
}

fn get_stream(handle: u64) -> Option<Arc<StreamContext>> {
    streams().read().ok()?.get(&handle).cloned()
}

// =============================================================================
// Plugin Trait
// =============================================================================

pub trait VolvoxGridServicePlugin: Send + Sync + 'static {
    fn create(&self, request: CreateRequest) -> Result<CreateResponse, FfiError>;
    fn destroy(&self, request: GridHandle) -> Result<Empty, FfiError>;
    fn configure(&self, request: ConfigureRequest) -> Result<Empty, FfiError>;
    fn get_config(&self, request: GridHandle) -> Result<GridConfig, FfiError>;
    fn load_font_data(&self, request: LoadFontDataRequest) -> Result<Empty, FfiError>;
    fn define_columns(&self, request: DefineColumnsRequest) -> Result<Empty, FfiError>;
    fn get_schema(&self, request: GridHandle) -> Result<DefineColumnsRequest, FfiError>;
    fn define_rows(&self, request: DefineRowsRequest) -> Result<Empty, FfiError>;
    fn insert_rows(&self, request: InsertRowsRequest) -> Result<Empty, FfiError>;
    fn remove_rows(&self, request: RemoveRowsRequest) -> Result<Empty, FfiError>;
    fn move_column(&self, request: MoveColumnRequest) -> Result<Empty, FfiError>;
    fn move_row(&self, request: MoveRowRequest) -> Result<Empty, FfiError>;
    fn update_cells(&self, request: UpdateCellsRequest) -> Result<WriteResult, FfiError>;
    fn get_cells(&self, request: GetCellsRequest) -> Result<CellsResponse, FfiError>;
    fn load_table(&self, request: LoadTableRequest) -> Result<WriteResult, FfiError>;
    fn load_data(&self, request: LoadDataRequest) -> Result<LoadDataResult, FfiError>;
    fn clear(&self, request: ClearRequest) -> Result<Empty, FfiError>;
    fn select(&self, request: SelectRequest) -> Result<Empty, FfiError>;
    fn get_selection(&self, request: GridHandle) -> Result<SelectionState, FfiError>;
    fn show_cell(&self, request: ShowCellRequest) -> Result<Empty, FfiError>;
    fn set_top_row(&self, request: SetRowRequest) -> Result<Empty, FfiError>;
    fn set_left_col(&self, request: SetColRequest) -> Result<Empty, FfiError>;
    fn edit(&self, request: EditCommand) -> Result<EditState, FfiError>;
    fn sort(&self, request: SortRequest) -> Result<Empty, FfiError>;
    fn subtotal(&self, request: SubtotalRequest) -> Result<Empty, FfiError>;
    fn auto_size(&self, request: AutoSizeRequest) -> Result<Empty, FfiError>;
    fn outline(&self, request: OutlineRequest) -> Result<Empty, FfiError>;
    fn get_node(&self, request: GetNodeRequest) -> Result<NodeInfo, FfiError>;
    fn find(&self, request: FindRequest) -> Result<FindResponse, FfiError>;
    fn aggregate(&self, request: AggregateRequest) -> Result<AggregateResponse, FfiError>;
    fn get_merged_range(&self, request: GetMergedRangeRequest) -> Result<CellRange, FfiError>;
    fn merge_cells(&self, request: MergeCellsRequest) -> Result<Empty, FfiError>;
    fn unmerge_cells(&self, request: UnmergeCellsRequest) -> Result<Empty, FfiError>;
    fn get_merged_regions(&self, request: GridHandle) -> Result<MergedRegionsResponse, FfiError>;
    fn get_memory_usage(&self, request: GridHandle) -> Result<MemoryUsageResponse, FfiError>;
    fn clipboard(&self, request: ClipboardCommand) -> Result<ClipboardResponse, FfiError>;
    fn export(&self, request: ExportRequest) -> Result<ExportResponse, FfiError>;
    fn print(&self, request: PrintRequest) -> Result<PrintResponse, FfiError>;
    fn archive(&self, request: ArchiveRequest) -> Result<ArchiveResponse, FfiError>;
    fn resize_viewport(&self, request: ResizeViewportRequest) -> Result<Empty, FfiError>;
    fn set_redraw(&self, request: SetRedrawRequest) -> Result<Empty, FfiError>;
    fn refresh(&self, request: GridHandle) -> Result<Empty, FfiError>;
    fn load_demo(&self, request: LoadDemoRequest) -> Result<Empty, FfiError>;
    fn get_demo_data(&self, request: GetDemoDataRequest) -> Result<GetDemoDataResponse, FfiError>;
    fn render_session(
        &self,
        stream: &dyn PluginStreamBidi<RenderInput, RenderOutput>,
    ) -> Result<(), FfiError>;
    fn event_stream(
        &self,
        request: GridHandle,
        stream: &dyn PluginStreamSender<GridEvent>,
    ) -> Result<(), FfiError>;
}

static PLUGIN_VOLVOX_GRID_SERVICE: std::sync::OnceLock<Box<dyn VolvoxGridServicePlugin>> =
    std::sync::OnceLock::new();

pub fn register_volvox_grid_service_plugin(plugin: impl VolvoxGridServicePlugin) {
    let _ = PLUGIN_VOLVOX_GRID_SERVICE.set(Box::new(plugin));
}

fn get_volvox_grid_service_plugin() -> Option<&'static dyn VolvoxGridServicePlugin> {
    Some(
        PLUGIN_VOLVOX_GRID_SERVICE
            .get_or_init(super::create_plugin)
            .as_ref(),
    )
}

// =============================================================================
// Stream Interfaces
// =============================================================================

pub trait PluginStreamSender<T> {
    fn send(&self, msg: T) -> bool;
    fn is_cancelled(&self) -> bool;
}

pub trait PluginStreamReceiver<T> {
    fn recv(&self) -> Option<T>;
    fn is_cancelled(&self) -> bool;
}

pub trait PluginStreamBidi<Req, Resp>:
    PluginStreamSender<Resp> + PluginStreamReceiver<Req>
{
}

struct StreamSender<T> {
    ctx: Arc<StreamContext>,
    _marker: std::marker::PhantomData<T>,
}

impl<T: Message + Default> PluginStreamSender<T> for StreamSender<T> {
    fn send(&self, msg: T) -> bool {
        if self.ctx.is_closed() {
            return false;
        }
        let mut buf = Vec::new();
        if msg.encode(&mut buf).is_err() {
            return false;
        }
        self.ctx.push_recv_result(0, buf);
        true
    }

    fn is_cancelled(&self) -> bool {
        self.ctx.is_closed()
    }
}

struct StreamReceiver<T> {
    ctx: Arc<StreamContext>,
    _marker: std::marker::PhantomData<T>,
}

impl<T: Message + Default> PluginStreamReceiver<T> for StreamReceiver<T> {
    fn recv(&self) -> Option<T> {
        let mut queue = self.ctx.send_queue.lock().ok()?;
        loop {
            if self.ctx.is_closed() {
                return None;
            }
            if !queue.is_empty() {
                let data = queue.remove(0); // FIFO order
                return T::decode(data.as_slice()).ok();
            }
            if self.ctx.send_closed.load(Ordering::SeqCst) && queue.is_empty() {
                return None;
            }
            queue = self.ctx.send_cv.wait(queue).ok()?;
        }
    }

    fn is_cancelled(&self) -> bool {
        self.ctx.is_closed()
    }
}

struct StreamBidi<Req, Resp> {
    sender: StreamSender<Resp>,
    receiver: StreamReceiver<Req>,
}

impl<Req: Message + Default, Resp: Message + Default> PluginStreamSender<Resp>
    for StreamBidi<Req, Resp>
{
    fn send(&self, msg: Resp) -> bool {
        self.sender.send(msg)
    }
    fn is_cancelled(&self) -> bool {
        self.sender.is_cancelled()
    }
}

impl<Req: Message + Default, Resp: Message + Default> PluginStreamReceiver<Req>
    for StreamBidi<Req, Resp>
{
    fn recv(&self) -> Option<Req> {
        self.receiver.recv()
    }
    fn is_cancelled(&self) -> bool {
        self.receiver.is_cancelled()
    }
}

impl<Req: Message + Default, Resp: Message + Default> PluginStreamBidi<Req, Resp>
    for StreamBidi<Req, Resp>
{
}

// =============================================================================
// C ABI Exports
// =============================================================================

#[no_mangle]
pub extern "C" fn Synurang_Free(ptr: *mut c_void) {
    if !ptr.is_null() {
        unsafe { free(ptr) };
    }
}

#[no_mangle]
pub extern "C" fn Synurang_Invoke_VolvoxGridService(
    method: *const c_char,
    data: *const c_char,
    data_len: c_int,
    resp_len: *mut c_int,
) -> *mut c_char {
    let method_str = unsafe {
        if method.is_null() {
            return error_response(resp_len, "null method");
        }
        match CStr::from_ptr(method).to_str() {
            Ok(s) => s,
            Err(_) => return error_response(resp_len, "invalid method utf8"),
        }
    };

    let input = if data.is_null() || data_len <= 0 {
        Vec::new()
    } else {
        unsafe { std::slice::from_raw_parts(data as *const u8, data_len as usize).to_vec() }
    };

    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => return error_response(resp_len, "plugin not registered"),
    };

    match method_str {
        "/volvoxgrid.v1.VolvoxGridService/Create" => {
            match CreateRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.create(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/Destroy" => match GridHandle::decode(input.as_slice()) {
            Ok(req) => match plugin.destroy(req) {
                Ok(resp) => {
                    let mut buf = Vec::new();
                    if resp.encode(&mut buf).is_ok() {
                        success_response(resp_len, &buf)
                    } else {
                        error_response(resp_len, "encode failed")
                    }
                }
                Err(e) => error_response(resp_len, &e),
            },
            Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
        },
        "/volvoxgrid.v1.VolvoxGridService/Configure" => {
            match ConfigureRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.configure(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/GetConfig" => {
            match GridHandle::decode(input.as_slice()) {
                Ok(req) => match plugin.get_config(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/LoadFontData" => {
            match LoadFontDataRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.load_font_data(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/DefineColumns" => {
            match DefineColumnsRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.define_columns(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/GetSchema" => {
            match GridHandle::decode(input.as_slice()) {
                Ok(req) => match plugin.get_schema(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/DefineRows" => {
            match DefineRowsRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.define_rows(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/InsertRows" => {
            match InsertRowsRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.insert_rows(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/RemoveRows" => {
            match RemoveRowsRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.remove_rows(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/MoveColumn" => {
            match MoveColumnRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.move_column(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/MoveRow" => {
            match MoveRowRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.move_row(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/UpdateCells" => {
            match UpdateCellsRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.update_cells(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/GetCells" => {
            match GetCellsRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.get_cells(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/LoadTable" => {
            match LoadTableRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.load_table(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/LoadData" => {
            match LoadDataRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.load_data(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/Clear" => match ClearRequest::decode(input.as_slice()) {
            Ok(req) => match plugin.clear(req) {
                Ok(resp) => {
                    let mut buf = Vec::new();
                    if resp.encode(&mut buf).is_ok() {
                        success_response(resp_len, &buf)
                    } else {
                        error_response(resp_len, "encode failed")
                    }
                }
                Err(e) => error_response(resp_len, &e),
            },
            Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
        },
        "/volvoxgrid.v1.VolvoxGridService/Select" => {
            match SelectRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.select(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/GetSelection" => {
            match GridHandle::decode(input.as_slice()) {
                Ok(req) => match plugin.get_selection(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/ShowCell" => {
            match ShowCellRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.show_cell(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/SetTopRow" => {
            match SetRowRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.set_top_row(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/SetLeftCol" => {
            match SetColRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.set_left_col(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/Edit" => match EditCommand::decode(input.as_slice()) {
            Ok(req) => match plugin.edit(req) {
                Ok(resp) => {
                    let mut buf = Vec::new();
                    if resp.encode(&mut buf).is_ok() {
                        success_response(resp_len, &buf)
                    } else {
                        error_response(resp_len, "encode failed")
                    }
                }
                Err(e) => error_response(resp_len, &e),
            },
            Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
        },
        "/volvoxgrid.v1.VolvoxGridService/Sort" => match SortRequest::decode(input.as_slice()) {
            Ok(req) => match plugin.sort(req) {
                Ok(resp) => {
                    let mut buf = Vec::new();
                    if resp.encode(&mut buf).is_ok() {
                        success_response(resp_len, &buf)
                    } else {
                        error_response(resp_len, "encode failed")
                    }
                }
                Err(e) => error_response(resp_len, &e),
            },
            Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
        },
        "/volvoxgrid.v1.VolvoxGridService/Subtotal" => {
            match SubtotalRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.subtotal(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/AutoSize" => {
            match AutoSizeRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.auto_size(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/Outline" => {
            match OutlineRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.outline(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/GetNode" => {
            match GetNodeRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.get_node(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/Find" => match FindRequest::decode(input.as_slice()) {
            Ok(req) => match plugin.find(req) {
                Ok(resp) => {
                    let mut buf = Vec::new();
                    if resp.encode(&mut buf).is_ok() {
                        success_response(resp_len, &buf)
                    } else {
                        error_response(resp_len, "encode failed")
                    }
                }
                Err(e) => error_response(resp_len, &e),
            },
            Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
        },
        "/volvoxgrid.v1.VolvoxGridService/Aggregate" => {
            match AggregateRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.aggregate(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/GetMergedRange" => {
            match GetMergedRangeRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.get_merged_range(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/MergeCells" => {
            match MergeCellsRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.merge_cells(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/UnmergeCells" => {
            match UnmergeCellsRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.unmerge_cells(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/GetMergedRegions" => {
            match GridHandle::decode(input.as_slice()) {
                Ok(req) => match plugin.get_merged_regions(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/GetMemoryUsage" => {
            match GridHandle::decode(input.as_slice()) {
                Ok(req) => match plugin.get_memory_usage(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/Clipboard" => {
            match ClipboardCommand::decode(input.as_slice()) {
                Ok(req) => match plugin.clipboard(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/Export" => {
            match ExportRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.export(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/Print" => match PrintRequest::decode(input.as_slice()) {
            Ok(req) => match plugin.print(req) {
                Ok(resp) => {
                    let mut buf = Vec::new();
                    if resp.encode(&mut buf).is_ok() {
                        success_response(resp_len, &buf)
                    } else {
                        error_response(resp_len, "encode failed")
                    }
                }
                Err(e) => error_response(resp_len, &e),
            },
            Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
        },
        "/volvoxgrid.v1.VolvoxGridService/Archive" => {
            match ArchiveRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.archive(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/ResizeViewport" => {
            match ResizeViewportRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.resize_viewport(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/SetRedraw" => {
            match SetRedrawRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.set_redraw(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/Refresh" => match GridHandle::decode(input.as_slice()) {
            Ok(req) => match plugin.refresh(req) {
                Ok(resp) => {
                    let mut buf = Vec::new();
                    if resp.encode(&mut buf).is_ok() {
                        success_response(resp_len, &buf)
                    } else {
                        error_response(resp_len, "encode failed")
                    }
                }
                Err(e) => error_response(resp_len, &e),
            },
            Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
        },
        "/volvoxgrid.v1.VolvoxGridService/LoadDemo" => {
            match LoadDemoRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.load_demo(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        "/volvoxgrid.v1.VolvoxGridService/GetDemoData" => {
            match GetDemoDataRequest::decode(input.as_slice()) {
                Ok(req) => match plugin.get_demo_data(req) {
                    Ok(resp) => {
                        let mut buf = Vec::new();
                        if resp.encode(&mut buf).is_ok() {
                            success_response(resp_len, &buf)
                        } else {
                            error_response(resp_len, "encode failed")
                        }
                    }
                    Err(e) => error_response(resp_len, &e),
                },
                Err(e) => error_response(resp_len, &format!("decode failed: {}", e)),
            }
        }
        _ => error_response(resp_len, "unknown method"),
    }
}

#[no_mangle]
pub extern "C" fn Synurang_Stream_VolvoxGridService_Open(method: *const c_char) -> u64 {
    let method_str = unsafe {
        if method.is_null() {
            return 0;
        }
        match CStr::from_ptr(method).to_str() {
            Ok(s) => s.to_string(),
            Err(_) => return 0,
        }
    };

    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => return 0,
    };

    let ctx = Arc::new(StreamContext::new());
    let handle = next_handle().fetch_add(1, Ordering::SeqCst);

    {
        let mut streams = streams().write().unwrap();
        streams.insert(handle, ctx.clone());
    }

    // Start handler thread
    let ctx_clone = ctx.clone();
    let worker = std::thread::spawn(move || {
        match method_str.as_str() {
            "/volvoxgrid.v1.VolvoxGridService/RenderSession" => {
                let bidi = StreamBidi::<RenderInput, RenderOutput> {
                    sender: StreamSender {
                        ctx: ctx_clone.clone(),
                        _marker: std::marker::PhantomData,
                    },
                    receiver: StreamReceiver {
                        ctx: ctx_clone.clone(),
                        _marker: std::marker::PhantomData,
                    },
                };
                if let Err(e) = plugin.render_session(&bidi) {
                    push_stream_error(&ctx_clone, &e);
                }
                ctx_clone.close();
            }
            "/volvoxgrid.v1.VolvoxGridService/EventStream" => {
                // Wait for initial request using Condvar
                let data = {
                    let mut queue = match ctx_clone.send_queue.lock() {
                        Ok(q) => q,
                        Err(_) => return,
                    };
                    loop {
                        if ctx_clone.is_closed() {
                            return;
                        }
                        if !queue.is_empty() {
                            break queue.remove(0); // FIFO order
                        }
                        queue = match ctx_clone.send_cv.wait(queue) {
                            Ok(q) => q,
                            Err(_) => return,
                        };
                    }
                };
                if let Ok(req) = GridHandle::decode(data.as_slice()) {
                    let sender = StreamSender::<GridEvent> {
                        ctx: ctx_clone.clone(),
                        _marker: std::marker::PhantomData,
                    };
                    if let Err(e) = plugin.event_stream(req, &sender) {
                        push_stream_error(&ctx_clone, &e);
                    }
                } else {
                    push_stream_error(&ctx_clone, "failed to parse stream request");
                }
                ctx_clone.close();
            }
            _ => {
                push_stream_error(&ctx_clone, format!("unknown method: {}", method_str));
                ctx_clone.close();
            }
        }
    });
    ctx.set_worker(worker);

    handle
}

#[no_mangle]
pub extern "C" fn Synurang_Stream_Send(handle: u64, data: *const c_char, data_len: c_int) -> c_int {
    let ctx = match get_stream(handle) {
        Some(c) => c,
        None => return -1,
    };

    if ctx.is_closed() {
        return -1;
    }

    let bytes = if data.is_null() || data_len <= 0 {
        Vec::new()
    } else {
        unsafe { std::slice::from_raw_parts(data as *const u8, data_len as usize).to_vec() }
    };

    ctx.send_to_plugin(bytes);
    0
}

#[no_mangle]
pub extern "C" fn Synurang_Stream_Recv(
    handle: u64,
    resp_len: *mut c_int,
    status: *mut c_int,
) -> *mut c_char {
    let ctx = match get_stream(handle) {
        Some(c) => c,
        None => {
            let payload = encode_ffi_error_payload(&FfiError::new("stream not found", 0, 2));
            unsafe {
                *status = -1;
                *resp_len = payload.len() as c_int;
            }
            return alloc_payload(&payload);
        }
    };

    // Block for data using Condvar (no busy-wait polling)
    match ctx.recv_from_plugin() {
        Some(result) => {
            unsafe {
                *resp_len = result.payload.len() as c_int;
                *status = result.status;
            }
            alloc_payload(&result.payload)
        }
        None => {
            unsafe {
                *status = 1; // EOF
                *resp_len = 0;
            }
            ptr::null_mut()
        }
    }
}

#[no_mangle]
pub extern "C" fn Synurang_Stream_CloseSend(handle: u64) {
    if let Some(ctx) = get_stream(handle) {
        {
            let _guard = ctx.send_queue.lock();
            ctx.send_closed.store(true, Ordering::SeqCst);
        }
        ctx.send_cv.notify_all();
    }
}

#[no_mangle]
pub extern "C" fn Synurang_Stream_Close(handle: u64) {
    let worker = if let Some(ctx) = get_stream(handle) {
        ctx.close(); // This now notifies all waiters
        ctx.take_worker()
    } else {
        None
    };
    if let Ok(mut streams) = streams().write() {
        streams.remove(&handle);
    }
    if let Some(worker) = worker {
        if worker.thread().id() != std::thread::current().id() {
            let _ = worker.join();
        }
    }
}

// =============================================================================
// Helper Functions
// =============================================================================

fn encode_ffi_error_payload(error: &FfiError) -> Vec<u8> {
    let pb_err = CoreFfiError {
        code: error.code,
        message: error.message.clone(),
        grpc_code: error.grpc_code,
    };
    let mut payload = Vec::new();
    if pb_err.encode(&mut payload).is_ok() {
        if payload.is_empty() {
            vec![0x12, 0x00]
        } else {
            payload
        }
    } else {
        if error.message.is_empty() {
            vec![0x12, 0x00]
        } else {
            error.message.as_bytes().to_vec()
        }
    }
}

fn alloc_payload(data: &[u8]) -> *mut c_char {
    if data.is_empty() {
        return ptr::null_mut();
    }
    unsafe {
        let raw = malloc(data.len()) as *mut u8;
        if raw.is_null() {
            return ptr::null_mut();
        }
        ptr::copy_nonoverlapping(data.as_ptr(), raw, data.len());
        raw as *mut c_char
    }
}

fn push_stream_error<E: Into<FfiError>>(ctx: &Arc<StreamContext>, error: E) {
    let error = error.into();
    ctx.push_recv_result(-1, encode_ffi_error_payload(&error));
}

fn error_response<E: Into<FfiError>>(resp_len: *mut c_int, error: E) -> *mut c_char {
    let error = error.into();
    let payload = encode_ffi_error_payload(&error);
    unsafe {
        *resp_len = -(payload.len() as c_int);
    }
    alloc_payload(&payload)
}

fn success_response(resp_len: *mut c_int, data: &[u8]) -> *mut c_char {
    unsafe {
        *resp_len = data.len() as c_int;
    }
    alloc_payload(data)
}

// Module: volvoxgrid_v1
