// Code generated by protoc-gen-synurang-ffi. DO NOT EDIT.
// Rust WASM bindings for volvoxgrid.v1
//
// Error sentinel convention (aligned with native C API where possible):
//   Empty       -> (no return value)
//   Handle      -> -1_i64
//   Int32Value  -> i32::MIN
//   BoolValue   -> false  (native uses -1_i32, but WASM returns bool)
//   DoubleValue -> f64::NAN
//   StringValue -> String::new()
//   Protobuf    -> Vec::new()

#![allow(unused_imports)]
#![allow(dead_code)]
use super::*;

use prost::Message;
use std::cell::{Cell, RefCell};
use std::collections::{HashMap, VecDeque};
use std::marker::PhantomData;
use std::sync::OnceLock;
use wasm_bindgen::prelude::*;

// =============================================================================
// Last Error (thread-local, dlerror()-style)
// =============================================================================

thread_local! {
    static LAST_ERROR: RefCell<String> = RefCell::new(String::new());
}

fn set_last_error(msg: String) {
    LAST_ERROR.with(|e| *e.borrow_mut() = msg);
}

fn clear_last_error() {
    LAST_ERROR.with(|e| e.borrow_mut().clear());
}

// =============================================================================
// Stream Result Framing
// =============================================================================
// `*_stream_recv()` returns `[status, payload...]`:
//   0 = data
//   1 = eof
//   2 = error (see last_error)
//   3 = pending (non-blocking; no data yet)

const STREAM_STATUS_DATA: u8 = 0;
const STREAM_STATUS_EOF: u8 = 1;
const STREAM_STATUS_ERROR: u8 = 2;
const STREAM_STATUS_PENDING: u8 = 3;

fn stream_pack(status: u8, payload: &[u8]) -> Vec<u8> {
    let mut out = Vec::with_capacity(1 + payload.len());
    out.push(status);
    out.extend_from_slice(payload);
    out
}

fn stream_status(status: u8) -> Vec<u8> {
    vec![status]
}

// =============================================================================
// Stream Interfaces (WASM)
// =============================================================================

pub trait PluginStreamSender<T> {
    fn send(&self, msg: T) -> bool;
    fn is_cancelled(&self) -> bool;
}

pub trait PluginStreamReceiver<T> {
    fn recv(&self) -> Option<T>;
    fn is_cancelled(&self) -> bool;
}

pub trait PluginStreamBidi<Req, Resp>:
    PluginStreamSender<Resp> + PluginStreamReceiver<Req>
{
}

struct LocalStreamSender<T> {
    outputs: RefCell<Vec<Vec<u8>>>,
    cancelled: Cell<bool>,
    encode_error: RefCell<Option<String>>,
    _marker: PhantomData<T>,
}

impl<T> LocalStreamSender<T> {
    fn new() -> Self {
        Self {
            outputs: RefCell::new(Vec::new()),
            cancelled: Cell::new(false),
            encode_error: RefCell::new(None),
            _marker: PhantomData,
        }
    }

    fn take_outputs(&self) -> Vec<Vec<u8>> {
        std::mem::take(&mut *self.outputs.borrow_mut())
    }

    fn take_encode_error(&self) -> Option<String> {
        self.encode_error.borrow_mut().take()
    }
}

impl<T: Message + Default> PluginStreamSender<T> for LocalStreamSender<T> {
    fn send(&self, msg: T) -> bool {
        if self.cancelled.get() {
            return false;
        }
        let mut buf = Vec::new();
        match msg.encode(&mut buf) {
            Ok(_) => {
                self.outputs.borrow_mut().push(buf);
                true
            }
            Err(e) => {
                *self.encode_error.borrow_mut() = Some(format!("encode stream message: {}", e));
                self.cancelled.set(true);
                false
            }
        }
    }

    fn is_cancelled(&self) -> bool {
        self.cancelled.get()
    }
}

struct LocalStreamReceiver<T> {
    inputs: RefCell<VecDeque<Vec<u8>>>,
    cancelled: Cell<bool>,
    decode_error: RefCell<Option<String>>,
    _marker: PhantomData<T>,
}

impl<T> LocalStreamReceiver<T> {
    fn from_queue(inputs: VecDeque<Vec<u8>>) -> Self {
        Self {
            inputs: RefCell::new(inputs),
            cancelled: Cell::new(false),
            decode_error: RefCell::new(None),
            _marker: PhantomData,
        }
    }

    fn take_decode_error(&self) -> Option<String> {
        self.decode_error.borrow_mut().take()
    }
}

impl<T: Message + Default> PluginStreamReceiver<T> for LocalStreamReceiver<T> {
    fn recv(&self) -> Option<T> {
        if self.cancelled.get() {
            return None;
        }
        let data = self.inputs.borrow_mut().pop_front()?;
        match T::decode(data.as_slice()) {
            Ok(msg) => Some(msg),
            Err(e) => {
                *self.decode_error.borrow_mut() = Some(format!("decode stream message: {}", e));
                self.cancelled.set(true);
                None
            }
        }
    }

    fn is_cancelled(&self) -> bool {
        self.cancelled.get()
    }
}

struct LocalStreamBidi<Req, Resp> {
    sender: LocalStreamSender<Resp>,
    receiver: LocalStreamReceiver<Req>,
}

impl<Req, Resp> LocalStreamBidi<Req, Resp> {
    fn from_queue(inputs: VecDeque<Vec<u8>>) -> Self {
        Self {
            sender: LocalStreamSender::new(),
            receiver: LocalStreamReceiver::from_queue(inputs),
        }
    }

    fn take_outputs(&self) -> Vec<Vec<u8>> {
        self.sender.take_outputs()
    }

    fn take_encode_error(&self) -> Option<String> {
        self.sender.take_encode_error()
    }

    fn take_decode_error(&self) -> Option<String> {
        self.receiver.take_decode_error()
    }
}

impl<Req: Message + Default, Resp: Message + Default> PluginStreamSender<Resp>
    for LocalStreamBidi<Req, Resp>
{
    fn send(&self, msg: Resp) -> bool {
        self.sender.send(msg)
    }

    fn is_cancelled(&self) -> bool {
        self.sender.is_cancelled() || self.receiver.is_cancelled()
    }
}

impl<Req: Message + Default, Resp: Message + Default> PluginStreamReceiver<Req>
    for LocalStreamBidi<Req, Resp>
{
    fn recv(&self) -> Option<Req> {
        self.receiver.recv()
    }

    fn is_cancelled(&self) -> bool {
        self.sender.is_cancelled() || self.receiver.is_cancelled()
    }
}

impl<Req: Message + Default, Resp: Message + Default> PluginStreamBidi<Req, Resp>
    for LocalStreamBidi<Req, Resp>
{
}

// =============================================================================
// Plugin Traits
// =============================================================================

pub trait VolvoxGridServicePlugin: Send + Sync + 'static {
    fn create(&self, request: CreateRequest) -> Result<CreateResponse, String>;
    fn destroy(&self, request: GridHandle) -> Result<Empty, String>;
    fn configure(&self, request: ConfigureRequest) -> Result<Empty, String>;
    fn get_config(&self, request: GridHandle) -> Result<GridConfig, String>;
    fn load_font_data(&self, request: LoadFontDataRequest) -> Result<Empty, String>;
    fn define_columns(&self, request: DefineColumnsRequest) -> Result<Empty, String>;
    fn get_schema(&self, request: GridHandle) -> Result<DefineColumnsRequest, String>;
    fn define_rows(&self, request: DefineRowsRequest) -> Result<Empty, String>;
    fn insert_rows(&self, request: InsertRowsRequest) -> Result<Empty, String>;
    fn remove_rows(&self, request: RemoveRowsRequest) -> Result<Empty, String>;
    fn move_column(&self, request: MoveColumnRequest) -> Result<Empty, String>;
    fn move_row(&self, request: MoveRowRequest) -> Result<Empty, String>;
    fn update_cells(&self, request: UpdateCellsRequest) -> Result<WriteResult, String>;
    fn get_cells(&self, request: GetCellsRequest) -> Result<CellsResponse, String>;
    fn load_table(&self, request: LoadTableRequest) -> Result<WriteResult, String>;
    fn clear(&self, request: ClearRequest) -> Result<Empty, String>;
    fn select(&self, request: SelectRequest) -> Result<Empty, String>;
    fn get_selection(&self, request: GridHandle) -> Result<SelectionState, String>;
    fn show_cell(&self, request: ShowCellRequest) -> Result<Empty, String>;
    fn set_top_row(&self, request: SetRowRequest) -> Result<Empty, String>;
    fn set_left_col(&self, request: SetColRequest) -> Result<Empty, String>;
    fn edit(&self, request: EditCommand) -> Result<EditState, String>;
    fn sort(&self, request: SortRequest) -> Result<Empty, String>;
    fn subtotal(&self, request: SubtotalRequest) -> Result<Empty, String>;
    fn auto_size(&self, request: AutoSizeRequest) -> Result<Empty, String>;
    fn outline(&self, request: OutlineRequest) -> Result<Empty, String>;
    fn get_node(&self, request: GetNodeRequest) -> Result<NodeInfo, String>;
    fn find(&self, request: FindRequest) -> Result<FindResponse, String>;
    fn aggregate(&self, request: AggregateRequest) -> Result<AggregateResponse, String>;
    fn get_merged_range(&self, request: GetMergedRangeRequest) -> Result<CellRange, String>;
    fn merge_cells(&self, request: MergeCellsRequest) -> Result<Empty, String>;
    fn unmerge_cells(&self, request: UnmergeCellsRequest) -> Result<Empty, String>;
    fn get_merged_regions(&self, request: GridHandle) -> Result<MergedRegionsResponse, String>;
    fn get_memory_usage(&self, request: GridHandle) -> Result<MemoryUsageResponse, String>;
    fn clipboard(&self, request: ClipboardCommand) -> Result<ClipboardResponse, String>;
    fn export(&self, request: ExportRequest) -> Result<ExportResponse, String>;
    fn import(&self, request: ImportRequest) -> Result<Empty, String>;
    fn print(&self, request: PrintRequest) -> Result<PrintResponse, String>;
    fn archive(&self, request: ArchiveRequest) -> Result<ArchiveResponse, String>;
    fn resize_viewport(&self, request: ResizeViewportRequest) -> Result<Empty, String>;
    fn set_redraw(&self, request: SetRedrawRequest) -> Result<Empty, String>;
    fn refresh(&self, request: GridHandle) -> Result<Empty, String>;
    fn load_demo(&self, request: LoadDemoRequest) -> Result<Empty, String>;
    fn render_session(
        &self,
        stream: &dyn PluginStreamBidi<RenderInput, RenderOutput>,
    ) -> Result<(), String>;
    fn event_stream(
        &self,
        request: GridHandle,
        stream: &dyn PluginStreamSender<GridEvent>,
    ) -> Result<(), String>;
}

static PLUGIN_VOLVOX_GRID_SERVICE: OnceLock<Box<dyn VolvoxGridServicePlugin>> = OnceLock::new();

/// Register a plugin implementation. Returns `true` on success, `false` if
/// a plugin was already registered (the new plugin is dropped).
pub fn register_volvox_grid_service_plugin(plugin: impl VolvoxGridServicePlugin) -> bool {
    PLUGIN_VOLVOX_GRID_SERVICE.set(Box::new(plugin)).is_ok()
}

fn get_volvox_grid_service_plugin() -> Option<&'static dyn VolvoxGridServicePlugin> {
    PLUGIN_VOLVOX_GRID_SERVICE.get().map(|p| p.as_ref())
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum VolvoxGridServiceStreamMode {
    Server,
    Client,
    Bidi,
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum VolvoxGridServiceStreamMethod {
    RenderSession,
    EventStream,
}

struct VolvoxGridServiceStreamContext {
    method: VolvoxGridServiceStreamMethod,
    mode: VolvoxGridServiceStreamMode,
    send_queue: VecDeque<Vec<u8>>,
    recv_queue: VecDeque<Vec<u8>>,
    send_closed: bool,
    closed: bool,
    started: bool,
    finished: bool,
    stream_error: bool,
}

impl VolvoxGridServiceStreamContext {
    fn new(method: VolvoxGridServiceStreamMethod, mode: VolvoxGridServiceStreamMode) -> Self {
        Self {
            method,
            mode,
            send_queue: VecDeque::new(),
            recv_queue: VecDeque::new(),
            send_closed: false,
            closed: false,
            started: false,
            finished: false,
            stream_error: false,
        }
    }
}

thread_local! {
    static STREAMS_VOLVOX_GRID_SERVICE: RefCell<HashMap<i64, VolvoxGridServiceStreamContext>> =
        RefCell::new(HashMap::new());
    static NEXT_STREAM_HANDLE_VOLVOX_GRID_SERVICE: Cell<i64> = Cell::new(1);
}

fn volvox_grid_service_next_stream_handle() -> i64 {
    NEXT_STREAM_HANDLE_VOLVOX_GRID_SERVICE.with(|cell| {
        let current = cell.get();
        let next = if current == i64::MAX { 1 } else { current + 1 };
        cell.set(next);
        current
    })
}

fn volvox_grid_service_run_stream(ctx: &mut VolvoxGridServiceStreamContext) {
    if ctx.closed || ctx.finished {
        return;
    }

    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => {
            set_last_error("plugin not registered".into());
            ctx.stream_error = true;
            ctx.finished = true;
            return;
        }
    };

    match ctx.method {
        VolvoxGridServiceStreamMethod::RenderSession => {
            if ctx.started || !ctx.send_closed {
                return;
            }

            let bidi = LocalStreamBidi::<RenderInput, RenderOutput>::from_queue(std::mem::take(
                &mut ctx.send_queue,
            ));
            match plugin.render_session(&bidi) {
                Ok(_) => {
                    if let Some(e) = bidi.take_decode_error() {
                        set_last_error(e);
                        ctx.stream_error = true;
                    } else if let Some(e) = bidi.take_encode_error() {
                        set_last_error(e);
                        ctx.stream_error = true;
                    } else {
                        for out in bidi.take_outputs() {
                            ctx.recv_queue.push_back(out);
                        }
                        clear_last_error();
                    }
                }
                Err(e) => {
                    set_last_error(e);
                    ctx.stream_error = true;
                }
            }

            ctx.finished = true;
            ctx.started = true;
        }
        VolvoxGridServiceStreamMethod::EventStream => {
            if ctx.started {
                return;
            }

            let data = match ctx.send_queue.pop_front() {
                Some(d) => d,
                None => return,
            };

            if !ctx.send_queue.is_empty() {
                set_last_error("server stream expects one request".into());
                ctx.stream_error = true;
                ctx.finished = true;
                ctx.started = true;
                return;
            }

            let req = match GridHandle::decode(data.as_slice()) {
                Ok(r) => r,
                Err(e) => {
                    set_last_error(format!("decode stream request: {}", e));
                    ctx.stream_error = true;
                    ctx.finished = true;
                    ctx.started = true;
                    return;
                }
            };

            let sender = LocalStreamSender::<GridEvent>::new();
            match plugin.event_stream(req, &sender) {
                Ok(_) => {
                    if let Some(e) = sender.take_encode_error() {
                        set_last_error(e);
                        ctx.stream_error = true;
                    } else {
                        for out in sender.take_outputs() {
                            ctx.recv_queue.push_back(out);
                        }
                        clear_last_error();
                    }
                }
                Err(e) => {
                    set_last_error(e);
                    ctx.stream_error = true;
                }
            }

            ctx.finished = true;
            ctx.started = true;
        }
    }
}

// =============================================================================
// WASM Exports
// =============================================================================

#[wasm_bindgen]
pub fn volvox_grid_create(
    viewport_width: i32,
    viewport_height: i32,
    scale: f32,
    config: &[u8],
) -> Vec<u8> {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => {
            set_last_error("plugin not registered".into());
            return Vec::new();
        }
    };
    let req = CreateRequest {
        viewport_width,
        viewport_height,
        scale,
        config: match GridConfig::decode(config) {
            Ok(m) => Some(m),
            Err(e) => {
                set_last_error(format!("decode 'config': {}", e));
                return Vec::new();
            }
        },
        ..Default::default()
    };
    match plugin.create(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            let _ = r.encode(&mut buf);
            buf
        }
        Err(e) => {
            set_last_error(e);
            return Vec::new();
        }
    }
}

#[wasm_bindgen]
pub fn volvox_grid_destroy(id: i64) -> Vec<u8> {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => {
            set_last_error("plugin not registered".into());
            return Vec::new();
        }
    };
    let req = GridHandle {
        id,
        ..Default::default()
    };
    match plugin.destroy(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            let _ = r.encode(&mut buf);
            buf
        }
        Err(e) => {
            set_last_error(e);
            return Vec::new();
        }
    }
}

#[wasm_bindgen]
pub fn volvox_grid_configure(grid_id: i64, config: &[u8]) -> Vec<u8> {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => {
            set_last_error("plugin not registered".into());
            return Vec::new();
        }
    };
    let req = ConfigureRequest {
        grid_id,
        config: match GridConfig::decode(config) {
            Ok(m) => Some(m),
            Err(e) => {
                set_last_error(format!("decode 'config': {}", e));
                return Vec::new();
            }
        },
        ..Default::default()
    };
    match plugin.configure(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            let _ = r.encode(&mut buf);
            buf
        }
        Err(e) => {
            set_last_error(e);
            return Vec::new();
        }
    }
}

#[wasm_bindgen]
pub fn volvox_grid_get_config(id: i64) -> Vec<u8> {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => {
            set_last_error("plugin not registered".into());
            return Vec::new();
        }
    };
    let req = GridHandle {
        id,
        ..Default::default()
    };
    match plugin.get_config(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            let _ = r.encode(&mut buf);
            buf
        }
        Err(e) => {
            set_last_error(e);
            return Vec::new();
        }
    }
}

#[wasm_bindgen]
pub fn volvox_grid_load_font_data_pb(data: &[u8]) -> Vec<u8> {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => {
            set_last_error("plugin not registered".into());
            return Vec::new();
        }
    };
    let req = match LoadFontDataRequest::decode(data) {
        Ok(r) => r,
        Err(e) => {
            set_last_error(format!("decode: {}", e));
            return Vec::new();
        }
    };
    match plugin.load_font_data(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            let _ = r.encode(&mut buf);
            buf
        }
        Err(e) => {
            set_last_error(e);
            return Vec::new();
        }
    }
}

#[wasm_bindgen]
pub fn volvox_grid_define_columns_pb(data: &[u8]) -> Vec<u8> {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => {
            set_last_error("plugin not registered".into());
            return Vec::new();
        }
    };
    let req = match DefineColumnsRequest::decode(data) {
        Ok(r) => r,
        Err(e) => {
            set_last_error(format!("decode: {}", e));
            return Vec::new();
        }
    };
    match plugin.define_columns(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            let _ = r.encode(&mut buf);
            buf
        }
        Err(e) => {
            set_last_error(e);
            return Vec::new();
        }
    }
}

#[wasm_bindgen]
pub fn volvox_grid_get_schema(id: i64) -> Vec<u8> {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => {
            set_last_error("plugin not registered".into());
            return Vec::new();
        }
    };
    let req = GridHandle {
        id,
        ..Default::default()
    };
    match plugin.get_schema(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            let _ = r.encode(&mut buf);
            buf
        }
        Err(e) => {
            set_last_error(e);
            return Vec::new();
        }
    }
}

#[wasm_bindgen]
pub fn volvox_grid_define_rows_pb(data: &[u8]) -> Vec<u8> {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => {
            set_last_error("plugin not registered".into());
            return Vec::new();
        }
    };
    let req = match DefineRowsRequest::decode(data) {
        Ok(r) => r,
        Err(e) => {
            set_last_error(format!("decode: {}", e));
            return Vec::new();
        }
    };
    match plugin.define_rows(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            let _ = r.encode(&mut buf);
            buf
        }
        Err(e) => {
            set_last_error(e);
            return Vec::new();
        }
    }
}

#[wasm_bindgen]
pub fn volvox_grid_insert_rows_pb(data: &[u8]) -> Vec<u8> {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => {
            set_last_error("plugin not registered".into());
            return Vec::new();
        }
    };
    let req = match InsertRowsRequest::decode(data) {
        Ok(r) => r,
        Err(e) => {
            set_last_error(format!("decode: {}", e));
            return Vec::new();
        }
    };
    match plugin.insert_rows(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            let _ = r.encode(&mut buf);
            buf
        }
        Err(e) => {
            set_last_error(e);
            return Vec::new();
        }
    }
}

#[wasm_bindgen]
pub fn volvox_grid_remove_rows(grid_id: i64, index: i32, count: i32) -> Vec<u8> {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => {
            set_last_error("plugin not registered".into());
            return Vec::new();
        }
    };
    let req = RemoveRowsRequest {
        grid_id,
        index,
        count,
        ..Default::default()
    };
    match plugin.remove_rows(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            let _ = r.encode(&mut buf);
            buf
        }
        Err(e) => {
            set_last_error(e);
            return Vec::new();
        }
    }
}

#[wasm_bindgen]
pub fn volvox_grid_move_column(grid_id: i64, col: i32, position: i32) -> Vec<u8> {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => {
            set_last_error("plugin not registered".into());
            return Vec::new();
        }
    };
    let req = MoveColumnRequest {
        grid_id,
        col,
        position,
        ..Default::default()
    };
    match plugin.move_column(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            let _ = r.encode(&mut buf);
            buf
        }
        Err(e) => {
            set_last_error(e);
            return Vec::new();
        }
    }
}

#[wasm_bindgen]
pub fn volvox_grid_move_row(grid_id: i64, row: i32, position: i32) -> Vec<u8> {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => {
            set_last_error("plugin not registered".into());
            return Vec::new();
        }
    };
    let req = MoveRowRequest {
        grid_id,
        row,
        position,
        ..Default::default()
    };
    match plugin.move_row(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            let _ = r.encode(&mut buf);
            buf
        }
        Err(e) => {
            set_last_error(e);
            return Vec::new();
        }
    }
}

#[wasm_bindgen]
pub fn volvox_grid_update_cells_pb(data: &[u8]) -> Vec<u8> {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => {
            set_last_error("plugin not registered".into());
            return Vec::new();
        }
    };
    let req = match UpdateCellsRequest::decode(data) {
        Ok(r) => r,
        Err(e) => {
            set_last_error(format!("decode: {}", e));
            return Vec::new();
        }
    };
    match plugin.update_cells(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            let _ = r.encode(&mut buf);
            buf
        }
        Err(e) => {
            set_last_error(e);
            return Vec::new();
        }
    }
}

#[wasm_bindgen]
pub fn volvox_grid_get_cells(
    grid_id: i64,
    row1: i32,
    col1: i32,
    row2: i32,
    col2: i32,
    include_style: bool,
    include_checked: bool,
    include_typed: bool,
) -> Vec<u8> {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => {
            set_last_error("plugin not registered".into());
            return Vec::new();
        }
    };
    let req = GetCellsRequest {
        grid_id,
        row1,
        col1,
        row2,
        col2,
        include_style,
        include_checked,
        include_typed,
        ..Default::default()
    };
    match plugin.get_cells(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            let _ = r.encode(&mut buf);
            buf
        }
        Err(e) => {
            set_last_error(e);
            return Vec::new();
        }
    }
}

#[wasm_bindgen]
pub fn volvox_grid_load_table_pb(data: &[u8]) -> Vec<u8> {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => {
            set_last_error("plugin not registered".into());
            return Vec::new();
        }
    };
    let req = match LoadTableRequest::decode(data) {
        Ok(r) => r,
        Err(e) => {
            set_last_error(format!("decode: {}", e));
            return Vec::new();
        }
    };
    match plugin.load_table(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            let _ = r.encode(&mut buf);
            buf
        }
        Err(e) => {
            set_last_error(e);
            return Vec::new();
        }
    }
}

#[wasm_bindgen]
pub fn volvox_grid_clear(grid_id: i64, scope: i32, region: i32) -> Vec<u8> {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => {
            set_last_error("plugin not registered".into());
            return Vec::new();
        }
    };
    let req = ClearRequest {
        grid_id,
        scope,
        region,
        ..Default::default()
    };
    match plugin.clear(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            let _ = r.encode(&mut buf);
            buf
        }
        Err(e) => {
            set_last_error(e);
            return Vec::new();
        }
    }
}

#[wasm_bindgen]
pub fn volvox_grid_select_pb(data: &[u8]) -> Vec<u8> {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => {
            set_last_error("plugin not registered".into());
            return Vec::new();
        }
    };
    let req = match SelectRequest::decode(data) {
        Ok(r) => r,
        Err(e) => {
            set_last_error(format!("decode: {}", e));
            return Vec::new();
        }
    };
    match plugin.select(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            let _ = r.encode(&mut buf);
            buf
        }
        Err(e) => {
            set_last_error(e);
            return Vec::new();
        }
    }
}

#[wasm_bindgen]
pub fn volvox_grid_get_selection(id: i64) -> Vec<u8> {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => {
            set_last_error("plugin not registered".into());
            return Vec::new();
        }
    };
    let req = GridHandle {
        id,
        ..Default::default()
    };
    match plugin.get_selection(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            let _ = r.encode(&mut buf);
            buf
        }
        Err(e) => {
            set_last_error(e);
            return Vec::new();
        }
    }
}

#[wasm_bindgen]
pub fn volvox_grid_show_cell(grid_id: i64, row: i32, col: i32) -> Vec<u8> {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => {
            set_last_error("plugin not registered".into());
            return Vec::new();
        }
    };
    let req = ShowCellRequest {
        grid_id,
        row,
        col,
        ..Default::default()
    };
    match plugin.show_cell(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            let _ = r.encode(&mut buf);
            buf
        }
        Err(e) => {
            set_last_error(e);
            return Vec::new();
        }
    }
}

#[wasm_bindgen]
pub fn volvox_grid_set_top_row(grid_id: i64, row: i32) -> Vec<u8> {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => {
            set_last_error("plugin not registered".into());
            return Vec::new();
        }
    };
    let req = SetRowRequest {
        grid_id,
        row,
        ..Default::default()
    };
    match plugin.set_top_row(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            let _ = r.encode(&mut buf);
            buf
        }
        Err(e) => {
            set_last_error(e);
            return Vec::new();
        }
    }
}

#[wasm_bindgen]
pub fn volvox_grid_set_left_col(grid_id: i64, col: i32) -> Vec<u8> {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => {
            set_last_error("plugin not registered".into());
            return Vec::new();
        }
    };
    let req = SetColRequest {
        grid_id,
        col,
        ..Default::default()
    };
    match plugin.set_left_col(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            let _ = r.encode(&mut buf);
            buf
        }
        Err(e) => {
            set_last_error(e);
            return Vec::new();
        }
    }
}

#[wasm_bindgen]
pub fn volvox_grid_edit_pb(data: &[u8]) -> Vec<u8> {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => {
            set_last_error("plugin not registered".into());
            return Vec::new();
        }
    };
    let req = match EditCommand::decode(data) {
        Ok(r) => r,
        Err(e) => {
            set_last_error(format!("decode: {}", e));
            return Vec::new();
        }
    };
    match plugin.edit(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            let _ = r.encode(&mut buf);
            buf
        }
        Err(e) => {
            set_last_error(e);
            return Vec::new();
        }
    }
}

#[wasm_bindgen]
pub fn volvox_grid_sort_pb(data: &[u8]) -> Vec<u8> {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => {
            set_last_error("plugin not registered".into());
            return Vec::new();
        }
    };
    let req = match SortRequest::decode(data) {
        Ok(r) => r,
        Err(e) => {
            set_last_error(format!("decode: {}", e));
            return Vec::new();
        }
    };
    match plugin.sort(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            let _ = r.encode(&mut buf);
            buf
        }
        Err(e) => {
            set_last_error(e);
            return Vec::new();
        }
    }
}

#[wasm_bindgen]
pub fn volvox_grid_subtotal(
    grid_id: i64,
    aggregate: i32,
    group_on_col: i32,
    aggregate_col: i32,
    caption: &str,
    back_color: u32,
    fore_color: u32,
    add_outline: bool,
) -> Vec<u8> {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => {
            set_last_error("plugin not registered".into());
            return Vec::new();
        }
    };
    let req = SubtotalRequest {
        grid_id,
        aggregate,
        group_on_col,
        aggregate_col,
        caption: caption.to_string(),
        back_color,
        fore_color,
        add_outline,
        ..Default::default()
    };
    match plugin.subtotal(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            let _ = r.encode(&mut buf);
            buf
        }
        Err(e) => {
            set_last_error(e);
            return Vec::new();
        }
    }
}

#[wasm_bindgen]
pub fn volvox_grid_auto_size(
    grid_id: i64,
    col_from: i32,
    col_to: i32,
    equal: bool,
    max_width: i32,
) -> Vec<u8> {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => {
            set_last_error("plugin not registered".into());
            return Vec::new();
        }
    };
    let req = AutoSizeRequest {
        grid_id,
        col_from,
        col_to,
        equal,
        max_width,
        ..Default::default()
    };
    match plugin.auto_size(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            let _ = r.encode(&mut buf);
            buf
        }
        Err(e) => {
            set_last_error(e);
            return Vec::new();
        }
    }
}

#[wasm_bindgen]
pub fn volvox_grid_outline(grid_id: i64, level: i32) -> Vec<u8> {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => {
            set_last_error("plugin not registered".into());
            return Vec::new();
        }
    };
    let req = OutlineRequest {
        grid_id,
        level,
        ..Default::default()
    };
    match plugin.outline(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            let _ = r.encode(&mut buf);
            buf
        }
        Err(e) => {
            set_last_error(e);
            return Vec::new();
        }
    }
}

#[wasm_bindgen]
pub fn volvox_grid_get_node_pb(data: &[u8]) -> Vec<u8> {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => {
            set_last_error("plugin not registered".into());
            return Vec::new();
        }
    };
    let req = match GetNodeRequest::decode(data) {
        Ok(r) => r,
        Err(e) => {
            set_last_error(format!("decode: {}", e));
            return Vec::new();
        }
    };
    match plugin.get_node(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            let _ = r.encode(&mut buf);
            buf
        }
        Err(e) => {
            set_last_error(e);
            return Vec::new();
        }
    }
}

#[wasm_bindgen]
pub fn volvox_grid_find_pb(data: &[u8]) -> Vec<u8> {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => {
            set_last_error("plugin not registered".into());
            return Vec::new();
        }
    };
    let req = match FindRequest::decode(data) {
        Ok(r) => r,
        Err(e) => {
            set_last_error(format!("decode: {}", e));
            return Vec::new();
        }
    };
    match plugin.find(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            let _ = r.encode(&mut buf);
            buf
        }
        Err(e) => {
            set_last_error(e);
            return Vec::new();
        }
    }
}

#[wasm_bindgen]
pub fn volvox_grid_aggregate(
    grid_id: i64,
    aggregate: i32,
    row1: i32,
    col1: i32,
    row2: i32,
    col2: i32,
) -> Vec<u8> {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => {
            set_last_error("plugin not registered".into());
            return Vec::new();
        }
    };
    let req = AggregateRequest {
        grid_id,
        aggregate,
        row1,
        col1,
        row2,
        col2,
        ..Default::default()
    };
    match plugin.aggregate(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            let _ = r.encode(&mut buf);
            buf
        }
        Err(e) => {
            set_last_error(e);
            return Vec::new();
        }
    }
}

#[wasm_bindgen]
pub fn volvox_grid_get_merged_range(grid_id: i64, row: i32, col: i32) -> Vec<u8> {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => {
            set_last_error("plugin not registered".into());
            return Vec::new();
        }
    };
    let req = GetMergedRangeRequest {
        grid_id,
        row,
        col,
        ..Default::default()
    };
    match plugin.get_merged_range(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            let _ = r.encode(&mut buf);
            buf
        }
        Err(e) => {
            set_last_error(e);
            return Vec::new();
        }
    }
}

#[wasm_bindgen]
pub fn volvox_grid_merge_cells(grid_id: i64, range: &[u8]) -> Vec<u8> {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => {
            set_last_error("plugin not registered".into());
            return Vec::new();
        }
    };
    let req = MergeCellsRequest {
        grid_id,
        range: match CellRange::decode(range) {
            Ok(m) => Some(m),
            Err(e) => {
                set_last_error(format!("decode 'range': {}", e));
                return Vec::new();
            }
        },
        ..Default::default()
    };
    match plugin.merge_cells(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            let _ = r.encode(&mut buf);
            buf
        }
        Err(e) => {
            set_last_error(e);
            return Vec::new();
        }
    }
}

#[wasm_bindgen]
pub fn volvox_grid_unmerge_cells(grid_id: i64, range: &[u8]) -> Vec<u8> {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => {
            set_last_error("plugin not registered".into());
            return Vec::new();
        }
    };
    let req = UnmergeCellsRequest {
        grid_id,
        range: match CellRange::decode(range) {
            Ok(m) => Some(m),
            Err(e) => {
                set_last_error(format!("decode 'range': {}", e));
                return Vec::new();
            }
        },
        ..Default::default()
    };
    match plugin.unmerge_cells(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            let _ = r.encode(&mut buf);
            buf
        }
        Err(e) => {
            set_last_error(e);
            return Vec::new();
        }
    }
}

#[wasm_bindgen]
pub fn volvox_grid_get_merged_regions(id: i64) -> Vec<u8> {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => {
            set_last_error("plugin not registered".into());
            return Vec::new();
        }
    };
    let req = GridHandle {
        id,
        ..Default::default()
    };
    match plugin.get_merged_regions(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            let _ = r.encode(&mut buf);
            buf
        }
        Err(e) => {
            set_last_error(e);
            return Vec::new();
        }
    }
}

#[wasm_bindgen]
pub fn volvox_grid_get_memory_usage(id: i64) -> Vec<u8> {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => {
            set_last_error("plugin not registered".into());
            return Vec::new();
        }
    };
    let req = GridHandle {
        id,
        ..Default::default()
    };
    match plugin.get_memory_usage(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            let _ = r.encode(&mut buf);
            buf
        }
        Err(e) => {
            set_last_error(e);
            return Vec::new();
        }
    }
}

#[wasm_bindgen]
pub fn volvox_grid_clipboard_pb(data: &[u8]) -> Vec<u8> {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => {
            set_last_error("plugin not registered".into());
            return Vec::new();
        }
    };
    let req = match ClipboardCommand::decode(data) {
        Ok(r) => r,
        Err(e) => {
            set_last_error(format!("decode: {}", e));
            return Vec::new();
        }
    };
    match plugin.clipboard(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            let _ = r.encode(&mut buf);
            buf
        }
        Err(e) => {
            set_last_error(e);
            return Vec::new();
        }
    }
}

#[wasm_bindgen]
pub fn volvox_grid_export(grid_id: i64, format: i32, scope: i32) -> Vec<u8> {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => {
            set_last_error("plugin not registered".into());
            return Vec::new();
        }
    };
    let req = ExportRequest {
        grid_id,
        format,
        scope,
        ..Default::default()
    };
    match plugin.export(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            let _ = r.encode(&mut buf);
            buf
        }
        Err(e) => {
            set_last_error(e);
            return Vec::new();
        }
    }
}

#[wasm_bindgen]
pub fn volvox_grid_import_pb(data: &[u8]) -> Vec<u8> {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => {
            set_last_error("plugin not registered".into());
            return Vec::new();
        }
    };
    let req = match ImportRequest::decode(data) {
        Ok(r) => r,
        Err(e) => {
            set_last_error(format!("decode: {}", e));
            return Vec::new();
        }
    };
    match plugin.import(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            let _ = r.encode(&mut buf);
            buf
        }
        Err(e) => {
            set_last_error(e);
            return Vec::new();
        }
    }
}

#[wasm_bindgen]
pub fn volvox_grid_print_pb(data: &[u8]) -> Vec<u8> {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => {
            set_last_error("plugin not registered".into());
            return Vec::new();
        }
    };
    let req = match PrintRequest::decode(data) {
        Ok(r) => r,
        Err(e) => {
            set_last_error(format!("decode: {}", e));
            return Vec::new();
        }
    };
    match plugin.print(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            let _ = r.encode(&mut buf);
            buf
        }
        Err(e) => {
            set_last_error(e);
            return Vec::new();
        }
    }
}

#[wasm_bindgen]
pub fn volvox_grid_archive(grid_id: i64, name: &str, action: i32, data: &[u8]) -> Vec<u8> {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => {
            set_last_error("plugin not registered".into());
            return Vec::new();
        }
    };
    let req = ArchiveRequest {
        grid_id,
        name: name.to_string(),
        action,
        data: data.to_vec(),
        ..Default::default()
    };
    match plugin.archive(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            let _ = r.encode(&mut buf);
            buf
        }
        Err(e) => {
            set_last_error(e);
            return Vec::new();
        }
    }
}

#[wasm_bindgen]
pub fn volvox_grid_resize_viewport(grid_id: i64, width: i32, height: i32) -> Vec<u8> {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => {
            set_last_error("plugin not registered".into());
            return Vec::new();
        }
    };
    let req = ResizeViewportRequest {
        grid_id,
        width,
        height,
        ..Default::default()
    };
    match plugin.resize_viewport(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            let _ = r.encode(&mut buf);
            buf
        }
        Err(e) => {
            set_last_error(e);
            return Vec::new();
        }
    }
}

#[wasm_bindgen]
pub fn volvox_grid_set_redraw(grid_id: i64, enabled: bool) -> Vec<u8> {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => {
            set_last_error("plugin not registered".into());
            return Vec::new();
        }
    };
    let req = SetRedrawRequest {
        grid_id,
        enabled,
        ..Default::default()
    };
    match plugin.set_redraw(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            let _ = r.encode(&mut buf);
            buf
        }
        Err(e) => {
            set_last_error(e);
            return Vec::new();
        }
    }
}

#[wasm_bindgen]
pub fn volvox_grid_refresh(id: i64) -> Vec<u8> {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => {
            set_last_error("plugin not registered".into());
            return Vec::new();
        }
    };
    let req = GridHandle {
        id,
        ..Default::default()
    };
    match plugin.refresh(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            let _ = r.encode(&mut buf);
            buf
        }
        Err(e) => {
            set_last_error(e);
            return Vec::new();
        }
    }
}

#[wasm_bindgen]
pub fn volvox_grid_load_demo(grid_id: i64, demo: &str) -> Vec<u8> {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => {
            set_last_error("plugin not registered".into());
            return Vec::new();
        }
    };
    let req = LoadDemoRequest {
        grid_id,
        demo: demo.to_string(),
        ..Default::default()
    };
    match plugin.load_demo(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            let _ = r.encode(&mut buf);
            buf
        }
        Err(e) => {
            set_last_error(e);
            return Vec::new();
        }
    }
}

// =============================================================================
// WASM Stream Exports
// =============================================================================

#[wasm_bindgen]
pub fn volvox_grid_stream_open(method: &str) -> i64 {
    if get_volvox_grid_service_plugin().is_none() {
        set_last_error("plugin not registered".into());
        return -1;
    }

    let (method_id, mode) = match method {
        "/volvoxgrid.v1.VolvoxGridService/RenderSession" => (
            VolvoxGridServiceStreamMethod::RenderSession,
            VolvoxGridServiceStreamMode::Bidi,
        ),
        "/volvoxgrid.v1.VolvoxGridService/EventStream" => (
            VolvoxGridServiceStreamMethod::EventStream,
            VolvoxGridServiceStreamMode::Server,
        ),
        _ => {
            set_last_error(format!("unknown streaming method: {}", method));
            return -1;
        }
    };

    let handle = volvox_grid_service_next_stream_handle();
    STREAMS_VOLVOX_GRID_SERVICE.with(|streams| {
        streams
            .borrow_mut()
            .insert(handle, VolvoxGridServiceStreamContext::new(method_id, mode));
    });
    clear_last_error();
    handle
}

#[wasm_bindgen]
pub fn volvox_grid_stream_send(handle: i64, data: &[u8]) -> i32 {
    STREAMS_VOLVOX_GRID_SERVICE.with(|streams| {
        let mut streams = streams.borrow_mut();
        let ctx = match streams.get_mut(&handle) {
            Some(c) => c,
            None => {
                set_last_error(format!("invalid stream handle: {}", handle));
                return -1;
            }
        };

        if ctx.closed {
            set_last_error("stream is closed".into());
            return -1;
        }
        if ctx.send_closed {
            set_last_error("send side already closed".into());
            return -1;
        }
        if ctx.stream_error || ctx.finished {
            set_last_error("stream already finished".into());
            return -1;
        }

        if matches!(ctx.mode, VolvoxGridServiceStreamMode::Server)
            && (ctx.started || !ctx.send_queue.is_empty())
        {
            set_last_error("server stream accepts a single request".into());
            return -1;
        }

        ctx.send_queue.push_back(data.to_vec());

        if matches!(ctx.mode, VolvoxGridServiceStreamMode::Server) {
            volvox_grid_service_run_stream(ctx);
        }

        if ctx.stream_error {
            -1
        } else {
            clear_last_error();
            0
        }
    })
}

#[wasm_bindgen]
pub fn volvox_grid_stream_recv(handle: i64) -> Vec<u8> {
    STREAMS_VOLVOX_GRID_SERVICE.with(|streams| {
        let mut streams = streams.borrow_mut();
        let ctx = match streams.get_mut(&handle) {
            Some(c) => c,
            None => {
                set_last_error(format!("invalid stream handle: {}", handle));
                return stream_status(STREAM_STATUS_ERROR);
            }
        };

        if ctx.closed {
            set_last_error("stream is closed".into());
            return stream_status(STREAM_STATUS_ERROR);
        }

        if let Some(payload) = ctx.recv_queue.pop_front() {
            clear_last_error();
            return stream_pack(STREAM_STATUS_DATA, payload.as_slice());
        }

        if ctx.stream_error {
            return stream_status(STREAM_STATUS_ERROR);
        }

        if ctx.finished {
            clear_last_error();
            return stream_status(STREAM_STATUS_EOF);
        }

        clear_last_error();
        stream_status(STREAM_STATUS_PENDING)
    })
}

#[wasm_bindgen]
pub fn volvox_grid_stream_close_send(handle: i64) {
    STREAMS_VOLVOX_GRID_SERVICE.with(|streams| {
        let mut streams = streams.borrow_mut();
        let ctx = match streams.get_mut(&handle) {
            Some(c) => c,
            None => {
                set_last_error(format!("invalid stream handle: {}", handle));
                return;
            }
        };

        if ctx.closed {
            set_last_error("stream is closed".into());
            return;
        }

        if ctx.send_closed {
            clear_last_error();
            return;
        }

        ctx.send_closed = true;

        match ctx.mode {
            VolvoxGridServiceStreamMode::Server => {
                if !ctx.started {
                    if ctx.send_queue.is_empty() {
                        set_last_error("server stream request not sent".into());
                        ctx.stream_error = true;
                        ctx.finished = true;
                        ctx.started = true;
                    } else {
                        volvox_grid_service_run_stream(ctx);
                    }
                }
            }
            VolvoxGridServiceStreamMode::Client | VolvoxGridServiceStreamMode::Bidi => {
                volvox_grid_service_run_stream(ctx);
            }
        }

        if !ctx.stream_error {
            clear_last_error();
        }
    });
}

#[wasm_bindgen]
pub fn volvox_grid_stream_close(handle: i64) {
    STREAMS_VOLVOX_GRID_SERVICE.with(|streams| {
        let mut streams = streams.borrow_mut();
        if let Some(ctx) = streams.get_mut(&handle) {
            ctx.closed = true;
        }
        streams.remove(&handle);
    });
    clear_last_error();
}

// =============================================================================
// Error Retrieval
// =============================================================================

/// Returns the last error message, or an empty string if no error has occurred.
/// The error is cleared after each successful FFI call.
#[wasm_bindgen]
pub fn volvox_grid_last_error() -> String {
    LAST_ERROR.with(|e| e.borrow().clone())
}

// Module: volvoxgrid_v1
