// Code generated by protoc-gen-synurang-ffi. DO NOT EDIT.
// Rust Native C API for volvoxgrid.v1

#![allow(unused_imports)]
#![allow(dead_code)]
#![allow(clippy::missing_safety_doc)]
use super::*;

use prost::Message;
use std::sync::OnceLock;


// =============================================================================
// Last Error (thread-local, dlerror()-style)
// =============================================================================

thread_local! {
    static LAST_ERROR: std::cell::RefCell<String> = std::cell::RefCell::new(String::new());
}

fn set_last_error(msg: String) {
    LAST_ERROR.with(|e| *e.borrow_mut() = msg);
}

fn clear_last_error() {
    LAST_ERROR.with(|e| e.borrow_mut().clear());
}

// =============================================================================
// Plugin Trait (unary methods only)
// =============================================================================

pub trait VolvoxGridServicePlugin: Send + Sync + 'static {
    fn create(&self, request: CreateRequest) -> Result<GridHandle, String>;
    fn destroy(&self, request: GridHandle) -> Result<Empty, String>;
    fn configure(&self, request: ConfigureRequest) -> Result<Empty, String>;
    fn get_config(&self, request: GridHandle) -> Result<GridConfig, String>;
    fn load_font_data(&self, request: LoadFontDataRequest) -> Result<Empty, String>;
    fn define_columns(&self, request: DefineColumnsRequest) -> Result<Empty, String>;
    fn define_rows(&self, request: DefineRowsRequest) -> Result<Empty, String>;
    fn insert_rows(&self, request: InsertRowsRequest) -> Result<Empty, String>;
    fn remove_rows(&self, request: RemoveRowsRequest) -> Result<Empty, String>;
    fn move_column(&self, request: MoveColumnRequest) -> Result<Empty, String>;
    fn move_row(&self, request: MoveRowRequest) -> Result<Empty, String>;
    fn update_cells(&self, request: UpdateCellsRequest) -> Result<Empty, String>;
    fn get_cells(&self, request: GetCellsRequest) -> Result<CellsResponse, String>;
    fn load_array(&self, request: LoadArrayRequest) -> Result<Empty, String>;
    fn clear(&self, request: ClearRequest) -> Result<Empty, String>;
    fn select(&self, request: SelectRequest) -> Result<Empty, String>;
    fn get_selection(&self, request: GridHandle) -> Result<SelectionState, String>;
    fn edit(&self, request: EditCommand) -> Result<EditState, String>;
    fn sort(&self, request: SortRequest) -> Result<Empty, String>;
    fn subtotal(&self, request: SubtotalRequest) -> Result<Empty, String>;
    fn auto_size(&self, request: AutoSizeRequest) -> Result<Empty, String>;
    fn outline(&self, request: OutlineRequest) -> Result<Empty, String>;
    fn get_node(&self, request: GetNodeRequest) -> Result<NodeInfo, String>;
    fn find(&self, request: FindRequest) -> Result<FindResponse, String>;
    fn aggregate(&self, request: AggregateRequest) -> Result<AggregateResponse, String>;
    fn get_merged_range(&self, request: GetMergedRangeRequest) -> Result<CellRange, String>;
    fn merge_cells(&self, request: MergeCellsRequest) -> Result<Empty, String>;
    fn unmerge_cells(&self, request: UnmergeCellsRequest) -> Result<Empty, String>;
    fn get_merged_regions(&self, request: GridHandle) -> Result<MergedRegionsResponse, String>;
    fn get_memory_usage(&self, request: GridHandle) -> Result<MemoryUsageResponse, String>;
    fn clipboard(&self, request: ClipboardCommand) -> Result<ClipboardResponse, String>;
    fn export(&self, request: ExportRequest) -> Result<ExportResponse, String>;
    fn import(&self, request: ImportRequest) -> Result<Empty, String>;
    fn print(&self, request: PrintRequest) -> Result<PrintResponse, String>;
    fn archive(&self, request: ArchiveRequest) -> Result<ArchiveResponse, String>;
    fn resize_viewport(&self, request: ResizeViewportRequest) -> Result<Empty, String>;
    fn set_redraw(&self, request: SetRedrawRequest) -> Result<Empty, String>;
    fn refresh(&self, request: GridHandle) -> Result<Empty, String>;
    fn load_demo(&self, request: LoadDemoRequest) -> Result<Empty, String>;
}

static PLUGIN_VOLVOX_GRID_SERVICE: OnceLock<Box<dyn VolvoxGridServicePlugin>> = OnceLock::new();

/// Register a plugin implementation. Returns `true` on success, `false` if
/// a plugin was already registered (the new plugin is dropped).
pub fn register_volvox_grid_service_plugin(plugin: impl VolvoxGridServicePlugin) -> bool {
    PLUGIN_VOLVOX_GRID_SERVICE.set(Box::new(plugin)).is_ok()
}

fn get_volvox_grid_service_plugin() -> Option<&'static dyn VolvoxGridServicePlugin> {
    PLUGIN_VOLVOX_GRID_SERVICE.get().map(|p| p.as_ref())
}

// =============================================================================
// Native Memory Helpers
// =============================================================================
// Returned pointers include an internal length header located immediately
// before the payload pointer. This makes free safe even if callers pass
// an incorrect length argument.

pub fn alloc_payload_with_header(payload: Vec<u8>) -> *mut u8 {
    let payload_len = payload.len();
    let header_len = std::mem::size_of::<usize>();
    let total_len = header_len + payload_len;

    let mut buf = Vec::<u8>::with_capacity(total_len);
    buf.extend_from_slice(&payload_len.to_ne_bytes());
    buf.extend_from_slice(&payload);

    let raw = Box::into_raw(buf.into_boxed_slice()) as *mut u8;
    // SAFETY: raw points to an allocation with at least header_len bytes.
    unsafe { raw.add(header_len) }
}

pub fn free_payload_with_header(ptr: *mut u8) {
    if ptr.is_null() {
        return;
    }

    let header_len = std::mem::size_of::<usize>();
    // SAFETY: ptr was returned by alloc_payload_with_header.
    let base = unsafe { ptr.sub(header_len) };

    let mut len_bytes = [0u8; std::mem::size_of::<usize>()];
    // SAFETY: base points to header_len initialized bytes.
    unsafe { std::ptr::copy_nonoverlapping(base as *const u8, len_bytes.as_mut_ptr(), header_len) };
    let payload_len = usize::from_ne_bytes(len_bytes);
    let total_len = header_len + payload_len;

    // SAFETY: reconstructs exactly the allocation created by alloc_payload_with_header.
    let _ = unsafe { Box::from_raw(std::slice::from_raw_parts_mut(base, total_len)) };
}

// =============================================================================
// Native C API Functions
// =============================================================================

/// Create
#[no_mangle]
pub unsafe extern "C" fn volvox_grid_create(
    viewport_width: i32,
    viewport_height: i32,
    scale: f32,
    config: *const u8, config_len: i32,
) -> i64 {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => { set_last_error("plugin not registered".into()); return -1; },
    };
    let req = CreateRequest {
        viewport_width,
        viewport_height,
        scale,
        config: if !config.is_null() && config_len > 0 {
            match GridConfig::decode(std::slice::from_raw_parts(config, config_len as usize)) {
                Ok(m) => Some(m),
                Err(e) => { set_last_error(format!("decode 'config': {}", e)); return -1; }
            }
        } else { None },
        ..Default::default()
    };
    match plugin.create(req) {
        Ok(r) => { clear_last_error(); r.id },
        Err(e) => { set_last_error(e); return -1; },
    }
}

/// Destroy
#[no_mangle]
pub unsafe extern "C" fn volvox_grid_destroy(
    id: i64,
    out_len: *mut i32,
) -> *mut u8 {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => { set_last_error("plugin not registered".into()); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    let req = GridHandle {
        id,
        ..Default::default()
    };
    match plugin.destroy(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            if r.encode(&mut buf).is_ok() {
                if !out_len.is_null() { *out_len = buf.len() as i32; }
                alloc_payload_with_header(buf)
            } else {
                if !out_len.is_null() { *out_len = 0; }
                std::ptr::null_mut()
            }
        },
        Err(e) => { set_last_error(e); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    }
}

/// Configure
#[no_mangle]
pub unsafe extern "C" fn volvox_grid_configure(
    grid_id: i64,
    config: *const u8, config_len: i32,
    out_len: *mut i32,
) -> *mut u8 {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => { set_last_error("plugin not registered".into()); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    let req = ConfigureRequest {
        grid_id,
        config: if !config.is_null() && config_len > 0 {
            match GridConfig::decode(std::slice::from_raw_parts(config, config_len as usize)) {
                Ok(m) => Some(m),
                Err(e) => { set_last_error(format!("decode 'config': {}", e)); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); }
            }
        } else { None },
        ..Default::default()
    };
    match plugin.configure(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            if r.encode(&mut buf).is_ok() {
                if !out_len.is_null() { *out_len = buf.len() as i32; }
                alloc_payload_with_header(buf)
            } else {
                if !out_len.is_null() { *out_len = 0; }
                std::ptr::null_mut()
            }
        },
        Err(e) => { set_last_error(e); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    }
}

/// GetConfig
#[no_mangle]
pub unsafe extern "C" fn volvox_grid_get_config(
    id: i64,
    out_len: *mut i32,
) -> *mut u8 {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => { set_last_error("plugin not registered".into()); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    let req = GridHandle {
        id,
        ..Default::default()
    };
    match plugin.get_config(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            if r.encode(&mut buf).is_ok() {
                if !out_len.is_null() { *out_len = buf.len() as i32; }
                alloc_payload_with_header(buf)
            } else {
                if !out_len.is_null() { *out_len = 0; }
                std::ptr::null_mut()
            }
        },
        Err(e) => { set_last_error(e); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    }
}

/// LoadFontData (protobuf input — has repeated/oneof fields)
#[no_mangle]
pub unsafe extern "C" fn volvox_grid_load_font_data_pb(
    data: *const u8, data_len: i32,
    out_len: *mut i32,
) -> *mut u8 {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => { set_last_error("plugin not registered".into()); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    let input = if data.is_null() || data_len <= 0 {
        Vec::new()
    } else {
        std::slice::from_raw_parts(data, data_len as usize).to_vec()
    };
    let req = match LoadFontDataRequest::decode(input.as_slice()) {
        Ok(r) => r,
        Err(e) => { set_last_error(format!("decode: {}", e)); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    match plugin.load_font_data(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            if r.encode(&mut buf).is_ok() {
                if !out_len.is_null() { *out_len = buf.len() as i32; }
                alloc_payload_with_header(buf)
            } else {
                if !out_len.is_null() { *out_len = 0; }
                std::ptr::null_mut()
            }
        },
        Err(e) => { set_last_error(e); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    }
}

/// DefineColumns (protobuf input — has repeated/oneof fields)
#[no_mangle]
pub unsafe extern "C" fn volvox_grid_define_columns_pb(
    data: *const u8, data_len: i32,
    out_len: *mut i32,
) -> *mut u8 {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => { set_last_error("plugin not registered".into()); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    let input = if data.is_null() || data_len <= 0 {
        Vec::new()
    } else {
        std::slice::from_raw_parts(data, data_len as usize).to_vec()
    };
    let req = match DefineColumnsRequest::decode(input.as_slice()) {
        Ok(r) => r,
        Err(e) => { set_last_error(format!("decode: {}", e)); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    match plugin.define_columns(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            if r.encode(&mut buf).is_ok() {
                if !out_len.is_null() { *out_len = buf.len() as i32; }
                alloc_payload_with_header(buf)
            } else {
                if !out_len.is_null() { *out_len = 0; }
                std::ptr::null_mut()
            }
        },
        Err(e) => { set_last_error(e); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    }
}

/// DefineRows (protobuf input — has repeated/oneof fields)
#[no_mangle]
pub unsafe extern "C" fn volvox_grid_define_rows_pb(
    data: *const u8, data_len: i32,
    out_len: *mut i32,
) -> *mut u8 {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => { set_last_error("plugin not registered".into()); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    let input = if data.is_null() || data_len <= 0 {
        Vec::new()
    } else {
        std::slice::from_raw_parts(data, data_len as usize).to_vec()
    };
    let req = match DefineRowsRequest::decode(input.as_slice()) {
        Ok(r) => r,
        Err(e) => { set_last_error(format!("decode: {}", e)); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    match plugin.define_rows(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            if r.encode(&mut buf).is_ok() {
                if !out_len.is_null() { *out_len = buf.len() as i32; }
                alloc_payload_with_header(buf)
            } else {
                if !out_len.is_null() { *out_len = 0; }
                std::ptr::null_mut()
            }
        },
        Err(e) => { set_last_error(e); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    }
}

/// InsertRows (protobuf input — has repeated/oneof fields)
#[no_mangle]
pub unsafe extern "C" fn volvox_grid_insert_rows_pb(
    data: *const u8, data_len: i32,
    out_len: *mut i32,
) -> *mut u8 {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => { set_last_error("plugin not registered".into()); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    let input = if data.is_null() || data_len <= 0 {
        Vec::new()
    } else {
        std::slice::from_raw_parts(data, data_len as usize).to_vec()
    };
    let req = match InsertRowsRequest::decode(input.as_slice()) {
        Ok(r) => r,
        Err(e) => { set_last_error(format!("decode: {}", e)); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    match plugin.insert_rows(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            if r.encode(&mut buf).is_ok() {
                if !out_len.is_null() { *out_len = buf.len() as i32; }
                alloc_payload_with_header(buf)
            } else {
                if !out_len.is_null() { *out_len = 0; }
                std::ptr::null_mut()
            }
        },
        Err(e) => { set_last_error(e); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    }
}

/// RemoveRows
#[no_mangle]
pub unsafe extern "C" fn volvox_grid_remove_rows(
    grid_id: i64,
    index: i32,
    count: i32,
    out_len: *mut i32,
) -> *mut u8 {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => { set_last_error("plugin not registered".into()); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    let req = RemoveRowsRequest {
        grid_id,
        index,
        count,
        ..Default::default()
    };
    match plugin.remove_rows(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            if r.encode(&mut buf).is_ok() {
                if !out_len.is_null() { *out_len = buf.len() as i32; }
                alloc_payload_with_header(buf)
            } else {
                if !out_len.is_null() { *out_len = 0; }
                std::ptr::null_mut()
            }
        },
        Err(e) => { set_last_error(e); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    }
}

/// MoveColumn
#[no_mangle]
pub unsafe extern "C" fn volvox_grid_move_column(
    grid_id: i64,
    col: i32,
    position: i32,
    out_len: *mut i32,
) -> *mut u8 {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => { set_last_error("plugin not registered".into()); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    let req = MoveColumnRequest {
        grid_id,
        col,
        position,
        ..Default::default()
    };
    match plugin.move_column(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            if r.encode(&mut buf).is_ok() {
                if !out_len.is_null() { *out_len = buf.len() as i32; }
                alloc_payload_with_header(buf)
            } else {
                if !out_len.is_null() { *out_len = 0; }
                std::ptr::null_mut()
            }
        },
        Err(e) => { set_last_error(e); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    }
}

/// MoveRow
#[no_mangle]
pub unsafe extern "C" fn volvox_grid_move_row(
    grid_id: i64,
    row: i32,
    position: i32,
    out_len: *mut i32,
) -> *mut u8 {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => { set_last_error("plugin not registered".into()); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    let req = MoveRowRequest {
        grid_id,
        row,
        position,
        ..Default::default()
    };
    match plugin.move_row(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            if r.encode(&mut buf).is_ok() {
                if !out_len.is_null() { *out_len = buf.len() as i32; }
                alloc_payload_with_header(buf)
            } else {
                if !out_len.is_null() { *out_len = 0; }
                std::ptr::null_mut()
            }
        },
        Err(e) => { set_last_error(e); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    }
}

/// UpdateCells (protobuf input — has repeated/oneof fields)
#[no_mangle]
pub unsafe extern "C" fn volvox_grid_update_cells_pb(
    data: *const u8, data_len: i32,
    out_len: *mut i32,
) -> *mut u8 {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => { set_last_error("plugin not registered".into()); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    let input = if data.is_null() || data_len <= 0 {
        Vec::new()
    } else {
        std::slice::from_raw_parts(data, data_len as usize).to_vec()
    };
    let req = match UpdateCellsRequest::decode(input.as_slice()) {
        Ok(r) => r,
        Err(e) => { set_last_error(format!("decode: {}", e)); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    match plugin.update_cells(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            if r.encode(&mut buf).is_ok() {
                if !out_len.is_null() { *out_len = buf.len() as i32; }
                alloc_payload_with_header(buf)
            } else {
                if !out_len.is_null() { *out_len = 0; }
                std::ptr::null_mut()
            }
        },
        Err(e) => { set_last_error(e); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    }
}

/// GetCells
#[no_mangle]
pub unsafe extern "C" fn volvox_grid_get_cells(
    grid_id: i64,
    row1: i32,
    col1: i32,
    row2: i32,
    col2: i32,
    include_style: i32,
    include_checked: i32,
    out_len: *mut i32,
) -> *mut u8 {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => { set_last_error("plugin not registered".into()); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    let req = GetCellsRequest {
        grid_id,
        row1,
        col1,
        row2,
        col2,
        include_style: include_style != 0,
        include_checked: include_checked != 0,
        ..Default::default()
    };
    match plugin.get_cells(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            if r.encode(&mut buf).is_ok() {
                if !out_len.is_null() { *out_len = buf.len() as i32; }
                alloc_payload_with_header(buf)
            } else {
                if !out_len.is_null() { *out_len = 0; }
                std::ptr::null_mut()
            }
        },
        Err(e) => { set_last_error(e); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    }
}

/// LoadArray (protobuf input — has repeated/oneof fields)
#[no_mangle]
pub unsafe extern "C" fn volvox_grid_load_array_pb(
    data: *const u8, data_len: i32,
    out_len: *mut i32,
) -> *mut u8 {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => { set_last_error("plugin not registered".into()); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    let input = if data.is_null() || data_len <= 0 {
        Vec::new()
    } else {
        std::slice::from_raw_parts(data, data_len as usize).to_vec()
    };
    let req = match LoadArrayRequest::decode(input.as_slice()) {
        Ok(r) => r,
        Err(e) => { set_last_error(format!("decode: {}", e)); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    match plugin.load_array(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            if r.encode(&mut buf).is_ok() {
                if !out_len.is_null() { *out_len = buf.len() as i32; }
                alloc_payload_with_header(buf)
            } else {
                if !out_len.is_null() { *out_len = 0; }
                std::ptr::null_mut()
            }
        },
        Err(e) => { set_last_error(e); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    }
}

/// Clear
#[no_mangle]
pub unsafe extern "C" fn volvox_grid_clear(
    grid_id: i64,
    scope: i32,
    region: i32,
    out_len: *mut i32,
) -> *mut u8 {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => { set_last_error("plugin not registered".into()); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    let req = ClearRequest {
        grid_id,
        scope,
        region,
        ..Default::default()
    };
    match plugin.clear(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            if r.encode(&mut buf).is_ok() {
                if !out_len.is_null() { *out_len = buf.len() as i32; }
                alloc_payload_with_header(buf)
            } else {
                if !out_len.is_null() { *out_len = 0; }
                std::ptr::null_mut()
            }
        },
        Err(e) => { set_last_error(e); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    }
}

/// Select (protobuf input — has repeated/oneof fields)
#[no_mangle]
pub unsafe extern "C" fn volvox_grid_select_pb(
    data: *const u8, data_len: i32,
    out_len: *mut i32,
) -> *mut u8 {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => { set_last_error("plugin not registered".into()); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    let input = if data.is_null() || data_len <= 0 {
        Vec::new()
    } else {
        std::slice::from_raw_parts(data, data_len as usize).to_vec()
    };
    let req = match SelectRequest::decode(input.as_slice()) {
        Ok(r) => r,
        Err(e) => { set_last_error(format!("decode: {}", e)); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    match plugin.select(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            if r.encode(&mut buf).is_ok() {
                if !out_len.is_null() { *out_len = buf.len() as i32; }
                alloc_payload_with_header(buf)
            } else {
                if !out_len.is_null() { *out_len = 0; }
                std::ptr::null_mut()
            }
        },
        Err(e) => { set_last_error(e); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    }
}

/// GetSelection
#[no_mangle]
pub unsafe extern "C" fn volvox_grid_get_selection(
    id: i64,
    out_len: *mut i32,
) -> *mut u8 {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => { set_last_error("plugin not registered".into()); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    let req = GridHandle {
        id,
        ..Default::default()
    };
    match plugin.get_selection(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            if r.encode(&mut buf).is_ok() {
                if !out_len.is_null() { *out_len = buf.len() as i32; }
                alloc_payload_with_header(buf)
            } else {
                if !out_len.is_null() { *out_len = 0; }
                std::ptr::null_mut()
            }
        },
        Err(e) => { set_last_error(e); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    }
}

/// Edit (protobuf input — has repeated/oneof fields)
#[no_mangle]
pub unsafe extern "C" fn volvox_grid_edit_pb(
    data: *const u8, data_len: i32,
    out_len: *mut i32,
) -> *mut u8 {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => { set_last_error("plugin not registered".into()); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    let input = if data.is_null() || data_len <= 0 {
        Vec::new()
    } else {
        std::slice::from_raw_parts(data, data_len as usize).to_vec()
    };
    let req = match EditCommand::decode(input.as_slice()) {
        Ok(r) => r,
        Err(e) => { set_last_error(format!("decode: {}", e)); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    match plugin.edit(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            if r.encode(&mut buf).is_ok() {
                if !out_len.is_null() { *out_len = buf.len() as i32; }
                alloc_payload_with_header(buf)
            } else {
                if !out_len.is_null() { *out_len = 0; }
                std::ptr::null_mut()
            }
        },
        Err(e) => { set_last_error(e); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    }
}

/// Sort (protobuf input — has repeated/oneof fields)
#[no_mangle]
pub unsafe extern "C" fn volvox_grid_sort_pb(
    data: *const u8, data_len: i32,
    out_len: *mut i32,
) -> *mut u8 {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => { set_last_error("plugin not registered".into()); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    let input = if data.is_null() || data_len <= 0 {
        Vec::new()
    } else {
        std::slice::from_raw_parts(data, data_len as usize).to_vec()
    };
    let req = match SortRequest::decode(input.as_slice()) {
        Ok(r) => r,
        Err(e) => { set_last_error(format!("decode: {}", e)); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    match plugin.sort(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            if r.encode(&mut buf).is_ok() {
                if !out_len.is_null() { *out_len = buf.len() as i32; }
                alloc_payload_with_header(buf)
            } else {
                if !out_len.is_null() { *out_len = 0; }
                std::ptr::null_mut()
            }
        },
        Err(e) => { set_last_error(e); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    }
}

/// Subtotal
#[no_mangle]
pub unsafe extern "C" fn volvox_grid_subtotal(
    grid_id: i64,
    aggregate: i32,
    group_on_col: i32,
    aggregate_col: i32,
    caption: *const u8, caption_len: i32,
    back_color: u32,
    fore_color: u32,
    add_outline: i32,
    out_len: *mut i32,
) -> *mut u8 {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => { set_last_error("plugin not registered".into()); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    let req = SubtotalRequest {
        grid_id,
        aggregate,
        group_on_col,
        aggregate_col,
        caption: if !caption.is_null() && caption_len > 0 {
            match std::str::from_utf8(std::slice::from_raw_parts(caption, caption_len as usize)) {
                Ok(s) => s.to_string(),
                Err(e) => { set_last_error(format!("invalid utf-8 in 'caption': {}", e)); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); }
            }
        } else { String::new() },
        back_color,
        fore_color,
        add_outline: add_outline != 0,
        ..Default::default()
    };
    match plugin.subtotal(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            if r.encode(&mut buf).is_ok() {
                if !out_len.is_null() { *out_len = buf.len() as i32; }
                alloc_payload_with_header(buf)
            } else {
                if !out_len.is_null() { *out_len = 0; }
                std::ptr::null_mut()
            }
        },
        Err(e) => { set_last_error(e); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    }
}

/// AutoSize
#[no_mangle]
pub unsafe extern "C" fn volvox_grid_auto_size(
    grid_id: i64,
    col_from: i32,
    col_to: i32,
    equal: i32,
    max_width: i32,
    out_len: *mut i32,
) -> *mut u8 {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => { set_last_error("plugin not registered".into()); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    let req = AutoSizeRequest {
        grid_id,
        col_from,
        col_to,
        equal: equal != 0,
        max_width,
        ..Default::default()
    };
    match plugin.auto_size(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            if r.encode(&mut buf).is_ok() {
                if !out_len.is_null() { *out_len = buf.len() as i32; }
                alloc_payload_with_header(buf)
            } else {
                if !out_len.is_null() { *out_len = 0; }
                std::ptr::null_mut()
            }
        },
        Err(e) => { set_last_error(e); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    }
}

/// Outline
#[no_mangle]
pub unsafe extern "C" fn volvox_grid_outline(
    grid_id: i64,
    level: i32,
    out_len: *mut i32,
) -> *mut u8 {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => { set_last_error("plugin not registered".into()); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    let req = OutlineRequest {
        grid_id,
        level,
        ..Default::default()
    };
    match plugin.outline(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            if r.encode(&mut buf).is_ok() {
                if !out_len.is_null() { *out_len = buf.len() as i32; }
                alloc_payload_with_header(buf)
            } else {
                if !out_len.is_null() { *out_len = 0; }
                std::ptr::null_mut()
            }
        },
        Err(e) => { set_last_error(e); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    }
}

/// GetNode (protobuf input — has repeated/oneof fields)
#[no_mangle]
pub unsafe extern "C" fn volvox_grid_get_node_pb(
    data: *const u8, data_len: i32,
    out_len: *mut i32,
) -> *mut u8 {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => { set_last_error("plugin not registered".into()); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    let input = if data.is_null() || data_len <= 0 {
        Vec::new()
    } else {
        std::slice::from_raw_parts(data, data_len as usize).to_vec()
    };
    let req = match GetNodeRequest::decode(input.as_slice()) {
        Ok(r) => r,
        Err(e) => { set_last_error(format!("decode: {}", e)); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    match plugin.get_node(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            if r.encode(&mut buf).is_ok() {
                if !out_len.is_null() { *out_len = buf.len() as i32; }
                alloc_payload_with_header(buf)
            } else {
                if !out_len.is_null() { *out_len = 0; }
                std::ptr::null_mut()
            }
        },
        Err(e) => { set_last_error(e); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    }
}

/// Find (protobuf input — has repeated/oneof fields)
#[no_mangle]
pub unsafe extern "C" fn volvox_grid_find_pb(
    data: *const u8, data_len: i32,
    out_len: *mut i32,
) -> *mut u8 {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => { set_last_error("plugin not registered".into()); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    let input = if data.is_null() || data_len <= 0 {
        Vec::new()
    } else {
        std::slice::from_raw_parts(data, data_len as usize).to_vec()
    };
    let req = match FindRequest::decode(input.as_slice()) {
        Ok(r) => r,
        Err(e) => { set_last_error(format!("decode: {}", e)); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    match plugin.find(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            if r.encode(&mut buf).is_ok() {
                if !out_len.is_null() { *out_len = buf.len() as i32; }
                alloc_payload_with_header(buf)
            } else {
                if !out_len.is_null() { *out_len = 0; }
                std::ptr::null_mut()
            }
        },
        Err(e) => { set_last_error(e); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    }
}

/// Aggregate
#[no_mangle]
pub unsafe extern "C" fn volvox_grid_aggregate(
    grid_id: i64,
    aggregate: i32,
    row1: i32,
    col1: i32,
    row2: i32,
    col2: i32,
    out_len: *mut i32,
) -> *mut u8 {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => { set_last_error("plugin not registered".into()); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    let req = AggregateRequest {
        grid_id,
        aggregate,
        row1,
        col1,
        row2,
        col2,
        ..Default::default()
    };
    match plugin.aggregate(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            if r.encode(&mut buf).is_ok() {
                if !out_len.is_null() { *out_len = buf.len() as i32; }
                alloc_payload_with_header(buf)
            } else {
                if !out_len.is_null() { *out_len = 0; }
                std::ptr::null_mut()
            }
        },
        Err(e) => { set_last_error(e); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    }
}

/// GetMergedRange
#[no_mangle]
pub unsafe extern "C" fn volvox_grid_get_merged_range(
    grid_id: i64,
    row: i32,
    col: i32,
    out_len: *mut i32,
) -> *mut u8 {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => { set_last_error("plugin not registered".into()); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    let req = GetMergedRangeRequest {
        grid_id,
        row,
        col,
        ..Default::default()
    };
    match plugin.get_merged_range(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            if r.encode(&mut buf).is_ok() {
                if !out_len.is_null() { *out_len = buf.len() as i32; }
                alloc_payload_with_header(buf)
            } else {
                if !out_len.is_null() { *out_len = 0; }
                std::ptr::null_mut()
            }
        },
        Err(e) => { set_last_error(e); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    }
}

/// MergeCells
#[no_mangle]
pub unsafe extern "C" fn volvox_grid_merge_cells(
    grid_id: i64,
    range: *const u8, range_len: i32,
    out_len: *mut i32,
) -> *mut u8 {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => { set_last_error("plugin not registered".into()); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    let req = MergeCellsRequest {
        grid_id,
        range: if !range.is_null() && range_len > 0 {
            match CellRange::decode(std::slice::from_raw_parts(range, range_len as usize)) {
                Ok(m) => Some(m),
                Err(e) => { set_last_error(format!("decode 'range': {}", e)); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); }
            }
        } else { None },
        ..Default::default()
    };
    match plugin.merge_cells(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            if r.encode(&mut buf).is_ok() {
                if !out_len.is_null() { *out_len = buf.len() as i32; }
                alloc_payload_with_header(buf)
            } else {
                if !out_len.is_null() { *out_len = 0; }
                std::ptr::null_mut()
            }
        },
        Err(e) => { set_last_error(e); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    }
}

/// UnmergeCells
#[no_mangle]
pub unsafe extern "C" fn volvox_grid_unmerge_cells(
    grid_id: i64,
    range: *const u8, range_len: i32,
    out_len: *mut i32,
) -> *mut u8 {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => { set_last_error("plugin not registered".into()); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    let req = UnmergeCellsRequest {
        grid_id,
        range: if !range.is_null() && range_len > 0 {
            match CellRange::decode(std::slice::from_raw_parts(range, range_len as usize)) {
                Ok(m) => Some(m),
                Err(e) => { set_last_error(format!("decode 'range': {}", e)); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); }
            }
        } else { None },
        ..Default::default()
    };
    match plugin.unmerge_cells(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            if r.encode(&mut buf).is_ok() {
                if !out_len.is_null() { *out_len = buf.len() as i32; }
                alloc_payload_with_header(buf)
            } else {
                if !out_len.is_null() { *out_len = 0; }
                std::ptr::null_mut()
            }
        },
        Err(e) => { set_last_error(e); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    }
}

/// GetMergedRegions
#[no_mangle]
pub unsafe extern "C" fn volvox_grid_get_merged_regions(
    id: i64,
    out_len: *mut i32,
) -> *mut u8 {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => { set_last_error("plugin not registered".into()); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    let req = GridHandle {
        id,
        ..Default::default()
    };
    match plugin.get_merged_regions(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            if r.encode(&mut buf).is_ok() {
                if !out_len.is_null() { *out_len = buf.len() as i32; }
                alloc_payload_with_header(buf)
            } else {
                if !out_len.is_null() { *out_len = 0; }
                std::ptr::null_mut()
            }
        },
        Err(e) => { set_last_error(e); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    }
}

/// GetMemoryUsage
#[no_mangle]
pub unsafe extern "C" fn volvox_grid_get_memory_usage(
    id: i64,
    out_len: *mut i32,
) -> *mut u8 {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => { set_last_error("plugin not registered".into()); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    let req = GridHandle {
        id,
        ..Default::default()
    };
    match plugin.get_memory_usage(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            if r.encode(&mut buf).is_ok() {
                if !out_len.is_null() { *out_len = buf.len() as i32; }
                alloc_payload_with_header(buf)
            } else {
                if !out_len.is_null() { *out_len = 0; }
                std::ptr::null_mut()
            }
        },
        Err(e) => { set_last_error(e); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    }
}

/// Clipboard (protobuf input — has repeated/oneof fields)
#[no_mangle]
pub unsafe extern "C" fn volvox_grid_clipboard_pb(
    data: *const u8, data_len: i32,
    out_len: *mut i32,
) -> *mut u8 {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => { set_last_error("plugin not registered".into()); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    let input = if data.is_null() || data_len <= 0 {
        Vec::new()
    } else {
        std::slice::from_raw_parts(data, data_len as usize).to_vec()
    };
    let req = match ClipboardCommand::decode(input.as_slice()) {
        Ok(r) => r,
        Err(e) => { set_last_error(format!("decode: {}", e)); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    match plugin.clipboard(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            if r.encode(&mut buf).is_ok() {
                if !out_len.is_null() { *out_len = buf.len() as i32; }
                alloc_payload_with_header(buf)
            } else {
                if !out_len.is_null() { *out_len = 0; }
                std::ptr::null_mut()
            }
        },
        Err(e) => { set_last_error(e); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    }
}

/// Export
#[no_mangle]
pub unsafe extern "C" fn volvox_grid_export(
    grid_id: i64,
    format: i32,
    scope: i32,
    out_len: *mut i32,
) -> *mut u8 {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => { set_last_error("plugin not registered".into()); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    let req = ExportRequest {
        grid_id,
        format,
        scope,
        ..Default::default()
    };
    match plugin.export(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            if r.encode(&mut buf).is_ok() {
                if !out_len.is_null() { *out_len = buf.len() as i32; }
                alloc_payload_with_header(buf)
            } else {
                if !out_len.is_null() { *out_len = 0; }
                std::ptr::null_mut()
            }
        },
        Err(e) => { set_last_error(e); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    }
}

/// Import (protobuf input — has repeated/oneof fields)
#[no_mangle]
pub unsafe extern "C" fn volvox_grid_import_pb(
    data: *const u8, data_len: i32,
    out_len: *mut i32,
) -> *mut u8 {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => { set_last_error("plugin not registered".into()); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    let input = if data.is_null() || data_len <= 0 {
        Vec::new()
    } else {
        std::slice::from_raw_parts(data, data_len as usize).to_vec()
    };
    let req = match ImportRequest::decode(input.as_slice()) {
        Ok(r) => r,
        Err(e) => { set_last_error(format!("decode: {}", e)); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    match plugin.import(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            if r.encode(&mut buf).is_ok() {
                if !out_len.is_null() { *out_len = buf.len() as i32; }
                alloc_payload_with_header(buf)
            } else {
                if !out_len.is_null() { *out_len = 0; }
                std::ptr::null_mut()
            }
        },
        Err(e) => { set_last_error(e); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    }
}

/// Print (protobuf input — has repeated/oneof fields)
#[no_mangle]
pub unsafe extern "C" fn volvox_grid_print_pb(
    data: *const u8, data_len: i32,
    out_len: *mut i32,
) -> *mut u8 {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => { set_last_error("plugin not registered".into()); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    let input = if data.is_null() || data_len <= 0 {
        Vec::new()
    } else {
        std::slice::from_raw_parts(data, data_len as usize).to_vec()
    };
    let req = match PrintRequest::decode(input.as_slice()) {
        Ok(r) => r,
        Err(e) => { set_last_error(format!("decode: {}", e)); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    match plugin.print(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            if r.encode(&mut buf).is_ok() {
                if !out_len.is_null() { *out_len = buf.len() as i32; }
                alloc_payload_with_header(buf)
            } else {
                if !out_len.is_null() { *out_len = 0; }
                std::ptr::null_mut()
            }
        },
        Err(e) => { set_last_error(e); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    }
}

/// Archive
#[no_mangle]
pub unsafe extern "C" fn volvox_grid_archive(
    grid_id: i64,
    name: *const u8, name_len: i32,
    action: i32,
    data: *const u8, data_len: i32,
    out_len: *mut i32,
) -> *mut u8 {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => { set_last_error("plugin not registered".into()); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    let req = ArchiveRequest {
        grid_id,
        name: if !name.is_null() && name_len > 0 {
            match std::str::from_utf8(std::slice::from_raw_parts(name, name_len as usize)) {
                Ok(s) => s.to_string(),
                Err(e) => { set_last_error(format!("invalid utf-8 in 'name': {}", e)); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); }
            }
        } else { String::new() },
        action,
        data: if !data.is_null() && data_len > 0 {
            std::slice::from_raw_parts(data, data_len as usize).to_vec()
        } else { Vec::new() },
        ..Default::default()
    };
    match plugin.archive(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            if r.encode(&mut buf).is_ok() {
                if !out_len.is_null() { *out_len = buf.len() as i32; }
                alloc_payload_with_header(buf)
            } else {
                if !out_len.is_null() { *out_len = 0; }
                std::ptr::null_mut()
            }
        },
        Err(e) => { set_last_error(e); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    }
}

/// ResizeViewport
#[no_mangle]
pub unsafe extern "C" fn volvox_grid_resize_viewport(
    grid_id: i64,
    width: i32,
    height: i32,
    out_len: *mut i32,
) -> *mut u8 {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => { set_last_error("plugin not registered".into()); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    let req = ResizeViewportRequest {
        grid_id,
        width,
        height,
        ..Default::default()
    };
    match plugin.resize_viewport(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            if r.encode(&mut buf).is_ok() {
                if !out_len.is_null() { *out_len = buf.len() as i32; }
                alloc_payload_with_header(buf)
            } else {
                if !out_len.is_null() { *out_len = 0; }
                std::ptr::null_mut()
            }
        },
        Err(e) => { set_last_error(e); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    }
}

/// SetRedraw
#[no_mangle]
pub unsafe extern "C" fn volvox_grid_set_redraw(
    grid_id: i64,
    enabled: i32,
    out_len: *mut i32,
) -> *mut u8 {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => { set_last_error("plugin not registered".into()); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    let req = SetRedrawRequest {
        grid_id,
        enabled: enabled != 0,
        ..Default::default()
    };
    match plugin.set_redraw(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            if r.encode(&mut buf).is_ok() {
                if !out_len.is_null() { *out_len = buf.len() as i32; }
                alloc_payload_with_header(buf)
            } else {
                if !out_len.is_null() { *out_len = 0; }
                std::ptr::null_mut()
            }
        },
        Err(e) => { set_last_error(e); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    }
}

/// Refresh
#[no_mangle]
pub unsafe extern "C" fn volvox_grid_refresh(
    id: i64,
    out_len: *mut i32,
) -> *mut u8 {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => { set_last_error("plugin not registered".into()); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    let req = GridHandle {
        id,
        ..Default::default()
    };
    match plugin.refresh(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            if r.encode(&mut buf).is_ok() {
                if !out_len.is_null() { *out_len = buf.len() as i32; }
                alloc_payload_with_header(buf)
            } else {
                if !out_len.is_null() { *out_len = 0; }
                std::ptr::null_mut()
            }
        },
        Err(e) => { set_last_error(e); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    }
}

/// LoadDemo
#[no_mangle]
pub unsafe extern "C" fn volvox_grid_load_demo(
    grid_id: i64,
    demo: *const u8, demo_len: i32,
    out_len: *mut i32,
) -> *mut u8 {
    let plugin = match get_volvox_grid_service_plugin() {
        Some(p) => p,
        None => { set_last_error("plugin not registered".into()); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    };
    let req = LoadDemoRequest {
        grid_id,
        demo: if !demo.is_null() && demo_len > 0 {
            match std::str::from_utf8(std::slice::from_raw_parts(demo, demo_len as usize)) {
                Ok(s) => s.to_string(),
                Err(e) => { set_last_error(format!("invalid utf-8 in 'demo': {}", e)); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); }
            }
        } else { String::new() },
        ..Default::default()
    };
    match plugin.load_demo(req) {
        Ok(r) => {
            clear_last_error();
            let mut buf = Vec::new();
            if r.encode(&mut buf).is_ok() {
                if !out_len.is_null() { *out_len = buf.len() as i32; }
                alloc_payload_with_header(buf)
            } else {
                if !out_len.is_null() { *out_len = 0; }
                std::ptr::null_mut()
            }
        },
        Err(e) => { set_last_error(e); if !out_len.is_null() { *out_len = 0; } return std::ptr::null_mut(); },
    }
}



// =============================================================================
// Memory Management & Error Retrieval
// =============================================================================

/// Free memory allocated by native API functions.
/// The allocation size is recovered from the prepended header.
#[no_mangle]
pub unsafe extern "C" fn volvox_grid_free(ptr: *mut u8) {
    free_payload_with_header(ptr);
}

/// Returns a pointer to the last error message (UTF-8, not null-terminated).
/// The pointer is valid until the next FFI call into this module.
/// Returns null if no error has occurred. Writes the byte length to `out_len`.
#[no_mangle]
pub unsafe extern "C" fn volvox_grid_last_error(out_len: *mut i32) -> *const u8 {
    LAST_ERROR.with(|e| {
        let msg = e.borrow();
        if msg.is_empty() {
            if !out_len.is_null() { *out_len = 0; }
            return std::ptr::null();
        }
        if !out_len.is_null() { *out_len = msg.len() as i32; }
        msg.as_ptr()
    })
}

// Module: volvoxgrid_v1

