use std::collections::VecDeque;

use crate::proto::volvoxgrid::v1 as pb;

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct EventTarget {
    pub kind: i32,
    pub band: i32,
    pub slot_index: i32,
    pub slot_kind: i32,
    pub sub_mode: i32,
    pub custom_key: String,
    pub text: String,
    pub int_value: i64,
    pub status_flags: u32,
    pub data: Vec<u8>,
}

impl EventTarget {
    pub fn data_cell() -> Self {
        Self {
            kind: pb::GridTargetKind::GridTargetDataCell as i32,
            ..Self::default()
        }
    }

    pub fn background() -> Self {
        Self {
            kind: pb::GridTargetKind::GridTargetBackground as i32,
            ..Self::default()
        }
    }

    pub fn to_proto(&self) -> pb::GridEventTarget {
        pb::GridEventTarget {
            kind: self.kind,
            band: self.band,
            slot_index: self.slot_index,
            slot_kind: self.slot_kind,
            custom_key: self.custom_key.clone(),
            text: self.text.clone(),
            int_value: self.int_value,
            status_flags: self.status_flags,
            data: self.data.clone(),
            sub_mode: self.sub_mode,
        }
    }

    pub fn heap_size_bytes(&self) -> usize {
        self.custom_key.capacity() + self.text.capacity() + self.data.capacity()
    }
}

impl Default for EventTarget {
    fn default() -> Self {
        Self {
            kind: pb::GridTargetKind::GridTargetUnspecified as i32,
            band: pb::IndicatorBand::Unspecified as i32,
            slot_index: -1,
            slot_kind: 0,
            sub_mode: 0,
            custom_key: String::new(),
            text: String::new(),
            int_value: 0,
            status_flags: 0,
            data: Vec::new(),
        }
    }
}

/// All possible grid events.
///
/// Events are generated by the engine in response to user interaction
/// (mouse, keyboard, editing, scrolling, drag/drop, etc.) and queued
/// for delivery to the platform layer via `EventQueue`.
#[derive(Clone, Debug)]
pub enum GridEventData {
    CellFocusChanging {
        old_row: i32,
        old_col: i32,
        new_row: i32,
        new_col: i32,
    },
    CellFocusChanged {
        old_row: i32,
        old_col: i32,
        new_row: i32,
        new_col: i32,
    },
    SelectionChanging {
        old_ranges: Vec<(i32, i32, i32, i32)>,
        new_ranges: Vec<(i32, i32, i32, i32)>,
        active_row: i32,
        active_col: i32,
    },
    SelectionChanged {
        old_ranges: Vec<(i32, i32, i32, i32)>,
        new_ranges: Vec<(i32, i32, i32, i32)>,
        active_row: i32,
        active_col: i32,
    },
    EnterCell {
        row: i32,
        col: i32,
        target: EventTarget,
    },
    LeaveCell {
        row: i32,
        col: i32,
        target: EventTarget,
    },
    BeforeEdit {
        row: i32,
        col: i32,
    },
    StartEdit {
        row: i32,
        col: i32,
    },
    AfterEdit {
        row: i32,
        col: i32,
        old_text: String,
        new_text: String,
    },
    CellEditValidate {
        row: i32,
        col: i32,
        edit_text: String,
    },
    CellEditChange {
        text: String,
    },
    KeyDownEdit {
        session_id: i64,
        key_code: i32,
        modifier: i32,
    },
    KeyPressEdit {
        session_id: i64,
        key_ascii: i32,
    },
    KeyUpEdit {
        session_id: i64,
        key_code: i32,
        modifier: i32,
    },
    EditValidationRequest {
        request_id: i64,
        session_id: i64,
        row: i32,
        col: i32,
        value: pb::EditorValue,
    },
    EditorListItemsRequest {
        request_id: i64,
        session_id: i64,
        data_source_id: String,
        filter_text: String,
        offset: i32,
        limit: i32,
    },
    CellEditConfigureStyle {
        row: i32,
        col: i32,
    },
    CellEditConfigureWindow {
        row: i32,
        col: i32,
    },
    BeforeDropdownOpen {
        row: i32,
        col: i32,
        x: f32,
        y: f32,
        width: f32,
        height: f32,
        dropdown: pb::ListEditorParams,
        current_value: String,
        selected_index: i32,
    },
    DropdownClosed,
    DropdownOpened,
    CustomEditorAction {
        session_id: i64,
        row: i32,
        col: i32,
        action_id: String,
        payload: Option<pb::StructValue>,
    },
    CellChanged {
        row: i32,
        col: i32,
        old_text: String,
        new_text: String,
    },
    RowStatusChange {
        row: i32,
        status: crate::row::RowStatus,
    },
    BeforeSort {
        col: i32,
    },
    AfterSort {
        col: i32,
    },
    Compare {
        request_id: i64,
        row1: i32,
        row2: i32,
        col: i32,
    },
    BeforeNodeToggle {
        row: i32,
        collapse: bool,
    },
    AfterNodeToggle {
        row: i32,
        collapse: bool,
    },
    TreeChildrenRequested {
        node_id: String,
        row: i32,
        request_id: i64,
    },
    BeforeTreeNodeToggle {
        node_id: String,
        row: i32,
        collapse: bool,
    },
    AfterTreeNodeToggle {
        node_id: String,
        row: i32,
        collapse: bool,
    },
    TreeNodeActivate {
        node_id: String,
        row: i32,
    },
    TreeNodeContextMenu {
        node_id: String,
        row: i32,
        x: i32,
        y: i32,
    },
    BeforeScroll {
        old_top_row: i32,
        old_left_col: i32,
        new_top_row: i32,
        new_left_col: i32,
    },
    AfterScroll {
        old_top_row: i32,
        old_left_col: i32,
        new_top_row: i32,
        new_left_col: i32,
    },
    ScrollTooltip {
        text: String,
    },
    BeforeUserResize {
        row: i32,
        col: i32,
    },
    AfterUserResize {
        row: i32,
        col: i32,
    },
    AfterUserFreeze {
        frozen_rows: i32,
        frozen_cols: i32,
    },
    BeforeMoveColumn {
        col: i32,
        new_position: i32,
    },
    AfterMoveColumn {
        col: i32,
        old_position: i32,
    },
    BeforeMoveRow {
        row: i32,
        new_position: i32,
    },
    AfterMoveRow {
        row: i32,
        old_position: i32,
    },
    BeforeMouseDown {
        row: i32,
        col: i32,
        target: EventTarget,
    },
    MouseDown {
        button: i32,
        modifier: i32,
        x: f32,
        y: f32,
    },
    MouseUp {
        button: i32,
        modifier: i32,
        x: f32,
        y: f32,
    },
    MouseMove {
        button: i32,
        modifier: i32,
        x: f32,
        y: f32,
        target: EventTarget,
    },
    Click {
        row: i32,
        col: i32,
        hit_area: i32,
        interaction: i32,
        target: EventTarget,
    },
    DblClick {
        row: i32,
        col: i32,
        target: EventTarget,
    },
    KeyDown {
        key_code: i32,
        modifier: i32,
    },
    KeyPress {
        key_ascii: i32,
    },
    KeyUp {
        key_code: i32,
        modifier: i32,
    },
    CustomRenderCell {
        row: i32,
        col: i32,
        x: f32,
        y: f32,
        width: f32,
        height: f32,
        text: String,
    },
    DragStart {
        row: i32,
        col: i32,
    },
    DragOver {
        row: i32,
        col: i32,
        x: f32,
        y: f32,
    },
    DragDrop {
        row: i32,
        col: i32,
    },
    DragComplete {
        success: bool,
    },
    TypeAheadStarted {
        col: i32,
        text: String,
    },
    TypeAheadEnded,
    PullToRefreshTriggered,
    PullToRefreshCanceled,
    DataRefreshing,
    DataRefreshed,
    FilterData {
        row: i32,
        col: i32,
        text: String,
    },
    Error {
        code: i32,
        message: String,
    },
    BeforePageBreak {
        row: i32,
    },
    StartPage {
        page: i32,
    },
    GetHeaderRow {
        page: i32,
    },
    Copy,
    Cut,
    Paste,
}

/// FIFO event queue that collects engine-generated events for delivery
/// to the platform layer (Android, Flutter, Web, etc.).
#[derive(Clone, Debug)]
pub struct QueuedGridEvent {
    pub event_id: i64,
    pub data: GridEventData,
}

impl GridEventData {
    pub fn heap_size_bytes(&self) -> usize {
        match self {
            GridEventData::AfterEdit {
                old_text, new_text, ..
            } => old_text.capacity() + new_text.capacity(),
            GridEventData::CellEditValidate { edit_text, .. } => edit_text.capacity(),
            GridEventData::CellEditChange { text } => text.capacity(),
            GridEventData::EditorListItemsRequest {
                data_source_id,
                filter_text,
                ..
            } => data_source_id.capacity() + filter_text.capacity(),
            GridEventData::CellChanged {
                old_text, new_text, ..
            } => old_text.capacity() + new_text.capacity(),
            GridEventData::ScrollTooltip { text } => text.capacity(),
            GridEventData::CustomRenderCell { text, .. } => text.capacity(),
            GridEventData::TypeAheadStarted { text, .. } => text.capacity(),
            GridEventData::FilterData { text, .. } => text.capacity(),
            GridEventData::Error { message, .. } => message.capacity(),
            GridEventData::TreeChildrenRequested { node_id, .. }
            | GridEventData::BeforeTreeNodeToggle { node_id, .. }
            | GridEventData::AfterTreeNodeToggle { node_id, .. }
            | GridEventData::TreeNodeActivate { node_id, .. }
            | GridEventData::TreeNodeContextMenu { node_id, .. } => node_id.capacity(),
            GridEventData::EnterCell { target, .. }
            | GridEventData::LeaveCell { target, .. }
            | GridEventData::BeforeMouseDown { target, .. }
            | GridEventData::MouseMove { target, .. }
            | GridEventData::Click { target, .. }
            | GridEventData::DblClick { target, .. } => target.heap_size_bytes(),
            _ => 0,
        }
    }
}

impl QueuedGridEvent {
    pub fn heap_size_bytes(&self) -> usize {
        self.data.heap_size_bytes()
    }
}

/// FIFO event queue that collects engine-generated events for delivery
/// to the platform layer (Android, Flutter, Web, etc.).
pub struct EventQueue {
    queue: VecDeque<QueuedGridEvent>,
}

impl EventQueue {
    pub fn new() -> Self {
        Self {
            queue: VecDeque::new(),
        }
    }

    pub fn heap_size_bytes(&self) -> usize {
        let mut bytes = self.queue.capacity() * std::mem::size_of::<QueuedGridEvent>();
        for event in &self.queue {
            bytes += event.heap_size_bytes();
        }
        bytes
    }

    /// Push an event onto the back of the queue.
    pub fn push(&mut self, event: GridEventData) {
        if let GridEventData::LeaveCell { row, col, target } = &event {
            // Drop a transient data-cell hover that entered and left before delivery.
            let cancels_pending_enter = self.queue.back().is_some_and(|back| {
                target.kind == pb::GridTargetKind::GridTargetDataCell as i32
                    && back.event_id == 0
                    && matches!(
                        &back.data,
                        GridEventData::EnterCell {
                            row: enter_row,
                            col: enter_col,
                            target: enter_target,
                        } if enter_row == row && enter_col == col && enter_target == target
                    )
            });
            if cancels_pending_enter {
                self.queue.pop_back();
                return;
            }
        }
        if matches!(event, GridEventData::MouseMove { .. }) {
            if let Some(back) = self.queue.back_mut() {
                if back.event_id == 0 && matches!(back.data, GridEventData::MouseMove { .. }) {
                    back.data = event;
                    return;
                }
            }
        }
        self.push_with_id(0, event);
    }

    /// Push an event with an optional correlation id.
    ///
    /// `event_id = 0` means "no correlation id".
    pub fn push_with_id(&mut self, event_id: i64, event: GridEventData) {
        self.queue.push_back(QueuedGridEvent {
            event_id,
            data: event,
        });
    }

    /// Pop the next event from the front of the queue, or `None` if empty.
    pub fn pop(&mut self) -> Option<QueuedGridEvent> {
        self.queue.pop_front()
    }

    /// Inspect the next event without removing it from the queue.
    pub fn peek(&self) -> Option<&QueuedGridEvent> {
        self.queue.front()
    }

    /// Drain all pending events into a `Vec`, leaving the queue empty.
    pub fn drain(&mut self) -> Vec<QueuedGridEvent> {
        self.queue.drain(..).collect()
    }

    /// Returns `true` if there are no pending events.
    pub fn is_empty(&self) -> bool {
        self.queue.is_empty()
    }

    /// Returns the number of pending events.
    pub fn len(&self) -> usize {
        self.queue.len()
    }
}

impl Default for EventQueue {
    fn default() -> Self {
        Self::new()
    }
}
