use std::collections::VecDeque;

/// All possible grid events.
///
/// Events are generated by the engine in response to user interaction
/// (mouse, keyboard, editing, scrolling, drag/drop, etc.) and queued
/// for delivery to the platform layer via `EventQueue`.
#[derive(Clone, Debug)]
pub enum GridEventData {
    CellFocusChanging {
        old_row: i32,
        old_col: i32,
        new_row: i32,
        new_col: i32,
    },
    CellFocusChanged {
        old_row: i32,
        old_col: i32,
        new_row: i32,
        new_col: i32,
    },
    SelectionChanging {
        old_ranges: Vec<(i32, i32, i32, i32)>,
        new_ranges: Vec<(i32, i32, i32, i32)>,
        active_row: i32,
        active_col: i32,
    },
    SelectionChanged {
        old_ranges: Vec<(i32, i32, i32, i32)>,
        new_ranges: Vec<(i32, i32, i32, i32)>,
        active_row: i32,
        active_col: i32,
    },
    EnterCell {
        row: i32,
        col: i32,
    },
    LeaveCell {
        row: i32,
        col: i32,
    },
    BeforeEdit {
        row: i32,
        col: i32,
    },
    StartEdit {
        row: i32,
        col: i32,
    },
    AfterEdit {
        row: i32,
        col: i32,
        old_text: String,
        new_text: String,
    },
    CellEditValidate {
        row: i32,
        col: i32,
        edit_text: String,
    },
    CellEditChange {
        text: String,
    },
    KeyDownEdit {
        key_code: i32,
        modifier: i32,
    },
    KeyPressEdit {
        key_ascii: i32,
    },
    KeyUpEdit {
        key_code: i32,
        modifier: i32,
    },
    CellEditConfigureStyle {
        row: i32,
        col: i32,
    },
    CellEditConfigureWindow {
        row: i32,
        col: i32,
    },
    DropdownClosed,
    DropdownOpened,
    CellChanged {
        row: i32,
        col: i32,
        old_text: String,
        new_text: String,
    },
    RowStatusChange {
        row: i32,
        status: i32,
    },
    BeforeSort {
        col: i32,
    },
    AfterSort {
        col: i32,
    },
    Compare {
        row1: i32,
        row2: i32,
        col: i32,
        result: i32,
    },
    BeforeNodeToggle {
        row: i32,
        collapse: bool,
    },
    AfterNodeToggle {
        row: i32,
        collapse: bool,
    },
    BeforeScroll {
        old_top_row: i32,
        old_left_col: i32,
        new_top_row: i32,
        new_left_col: i32,
    },
    AfterScroll {
        old_top_row: i32,
        old_left_col: i32,
        new_top_row: i32,
        new_left_col: i32,
    },
    ScrollTooltip {
        text: String,
    },
    BeforeUserResize {
        row: i32,
        col: i32,
    },
    AfterUserResize {
        row: i32,
        col: i32,
    },
    AfterUserFreeze {
        frozen_rows: i32,
        frozen_cols: i32,
    },
    BeforeMoveColumn {
        col: i32,
        new_position: i32,
    },
    AfterMoveColumn {
        col: i32,
        old_position: i32,
    },
    BeforeMoveRow {
        row: i32,
        new_position: i32,
    },
    AfterMoveRow {
        row: i32,
        old_position: i32,
    },
    BeforeMouseDown {
        row: i32,
        col: i32,
    },
    MouseDown {
        button: i32,
        modifier: i32,
        x: f32,
        y: f32,
    },
    MouseUp {
        button: i32,
        modifier: i32,
        x: f32,
        y: f32,
    },
    MouseMove {
        button: i32,
        modifier: i32,
        x: f32,
        y: f32,
    },
    Click {
        row: i32,
        col: i32,
        hit_area: i32,
        interaction: i32,
    },
    DblClick {
        row: i32,
        col: i32,
    },
    KeyDown {
        key_code: i32,
        modifier: i32,
    },
    KeyPress {
        key_ascii: i32,
    },
    KeyUp {
        key_code: i32,
        modifier: i32,
    },
    CustomRenderCell {
        row: i32,
        col: i32,
        x: f32,
        y: f32,
        width: f32,
        height: f32,
        text: String,
    },
    DragStart {
        row: i32,
        col: i32,
    },
    DragOver {
        row: i32,
        col: i32,
        x: f32,
        y: f32,
    },
    DragDrop {
        row: i32,
        col: i32,
    },
    DragComplete {
        success: bool,
    },
    TypeAheadStarted {
        col: i32,
        text: String,
    },
    TypeAheadEnded,
    DataRefreshing,
    DataRefreshed,
    FilterData {
        row: i32,
        col: i32,
        text: String,
    },
    Error {
        code: i32,
        message: String,
    },
    BeforePageBreak {
        row: i32,
    },
    StartPage {
        page: i32,
    },
    GetHeaderRow {
        page: i32,
    },
    Copy,
    Cut,
    Paste,
}

/// FIFO event queue that collects engine-generated events for delivery
/// to the platform layer (Android, Flutter, Web, etc.).
#[derive(Clone, Debug)]
pub struct QueuedGridEvent {
    pub event_id: i64,
    pub data: GridEventData,
}

impl GridEventData {
    pub fn heap_size_bytes(&self) -> usize {
        match self {
            GridEventData::AfterEdit {
                old_text, new_text, ..
            } => old_text.capacity() + new_text.capacity(),
            GridEventData::CellEditValidate { edit_text, .. } => edit_text.capacity(),
            GridEventData::CellEditChange { text } => text.capacity(),
            GridEventData::CellChanged {
                old_text, new_text, ..
            } => old_text.capacity() + new_text.capacity(),
            GridEventData::ScrollTooltip { text } => text.capacity(),
            GridEventData::CustomRenderCell { text, .. } => text.capacity(),
            GridEventData::TypeAheadStarted { text, .. } => text.capacity(),
            GridEventData::FilterData { text, .. } => text.capacity(),
            GridEventData::Error { message, .. } => message.capacity(),
            _ => 0,
        }
    }
}

impl QueuedGridEvent {
    pub fn heap_size_bytes(&self) -> usize {
        self.data.heap_size_bytes()
    }
}

/// FIFO event queue that collects engine-generated events for delivery
/// to the platform layer (Android, Flutter, Web, etc.).
pub struct EventQueue {
    queue: VecDeque<QueuedGridEvent>,
}

impl EventQueue {
    pub fn new() -> Self {
        Self {
            queue: VecDeque::new(),
        }
    }

    pub fn heap_size_bytes(&self) -> usize {
        let mut bytes = self.queue.capacity() * std::mem::size_of::<QueuedGridEvent>();
        for event in &self.queue {
            bytes += event.heap_size_bytes();
        }
        bytes
    }

    /// Push an event onto the back of the queue.
    pub fn push(&mut self, event: GridEventData) {
        self.push_with_id(0, event);
    }

    /// Push an event with an optional correlation id.
    ///
    /// `event_id = 0` means "no correlation id".
    pub fn push_with_id(&mut self, event_id: i64, event: GridEventData) {
        self.queue.push_back(QueuedGridEvent {
            event_id,
            data: event,
        });
    }

    /// Pop the next event from the front of the queue, or `None` if empty.
    pub fn pop(&mut self) -> Option<QueuedGridEvent> {
        self.queue.pop_front()
    }

    /// Drain all pending events into a `Vec`, leaving the queue empty.
    pub fn drain(&mut self) -> Vec<QueuedGridEvent> {
        self.queue.drain(..).collect()
    }

    /// Returns `true` if there are no pending events.
    pub fn is_empty(&self) -> bool {
        self.queue.is_empty()
    }

    /// Returns the number of pending events.
    pub fn len(&self) -> usize {
        self.queue.len()
    }
}

impl Default for EventQueue {
    fn default() -> Self {
        Self::new()
    }
}
